### ISSUE TITLE
Module fortios_vpn_ssl_settings: banned_cipher doesn't work

### ISSUE THREAD

**Issue by ikreb7** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#10]
Hello,

I want to ban some cipher for SSL VPN. But it works only for one value, i.g.: `banned_cipher: "3DES"`. I tried also `banned_cipher: '"3DES" "SHA1" "STATIC"'`. But then I get this error message: 

`fatal: [localhost]: FAILED! => 
{"changed": false, "msg": "value of banned_cipher must be one of: RSA, DH, DHE, ECDH, ECDHE, DSS, ECDSA, AES, AESGCM, CAMELLIA, 3DES, SHA1, SHA256, SHA384, STATIC, got: '3DES' 'SHA1' 'STATIC' found in vpn_ssl_settings"}`

This is my playbook:
```
  ....
  - name: Configure SSL VPN settings
    fortios_vpn_ssl_settings:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      ssl_verify:  "{{ ssl_verify }}"
      vpn_ssl_settings:
        banned_cipher: '"3DES" "SHA1" "STATIC"'
```

At the cli it works with `set banned-cipher "3DES" "SHA1" "STATIC".
