### ISSUE TITLE
Is check mode supported or not?

### ISSUE THREAD

**Issue by jantari** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#103]
Hello,

I am currently evaluating Fortinet solutions for the first time, so not intimately familiar with the platform yet - sorry if this is just user error.

Basically, I am currently looking into and trying out the ansible collection for fortios as well as the terraform provider for managing our devices. Part of the workflow we're imagining would be to run a "diff" or "plan" on every new commit/change to evaluate its impact and correctness before accepting it to the actual firewall infrastructure.

I saw in the release notes for Versions `1.1.0` to `1.1.2` that check mode is now supported: [Link to release notes](https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/release.html?highlight=check)

However, when trying this out with the following setup:

    Firewall:
        - Physical hardware
        - Fortinet FortiGate 100E
        - Firmware v6.4.4 build1803 (GA)
        - Mode: NAT (NGFW)
        - NGFW mode: Policy-based
    
    Ansible:
        - ansible 3.2.0
        - ansible-base 2.10.7
        - fortinet.fortios collection version 2.0.1

I noticed that check mode appears to be unsupported by 99% of the modules in the collection, and the one I did find that "supported" it (where it didn't just skip the task) reported false results: it reported a change when really there was none.

---

My full explanation with examples below:

### This is the current configuration on my fortigate

    jantari-forti100e # show system interface lan
    config system interface
        edit "lan"
            set vdom "root"
            set ip 192.168.252.1 255.255.254.0
            set allowaccess ping fabric
            set type hard-switch
            set stp enable
            set device-identification enable
            set role lan
            set snmp-index 9
        next
    end

### This is a task that wasn't skipped, but reported a change when run in check mode

    - name: Configure LAN interface
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: present
        system_interface:
          name: lan
          mode: static
          ip: "{{ lan_network | ansible.netcommon.ipaddr('1') }}"
          role: lan
          allowaccess: [ping, fabric]
          stp: enable
          device_identification: enable
          type: hard-switch
      vars:
        vdom: root
        lan_network: 192.168.252.0/23

### This is me running that task in check mode with ansible-playbook

    $ ansible-playbook site.yml --check --diff -v

    [ ... truncated ... ]

    TASK [Configure LAN interface] *************************************************
    changed: [jantari-forti100e] => changed=true
      meta:
        allowaccess: ping fabric
        device-identification: enable
        ip: 192.168.252.1/23
        mode: static
        name: lan
        role: lan
        stp: enable
        type: hard-switch

    [ ... truncated ... ]

most other tasks in the plays were just skipped with messages like this:

    TASK [Local LAN to RZ over VPN] *************************************************
    skipping: [jantari-forti100e] => changed=false
      msg: remote module (fortios_firewall_policy) does not support check mode
	  
and so on and so forth, 99% of tasks are just being skipped. Some examples are:

    msg: remote module (fortios_log_fortianalyzer_setting) does not support check mode
    msg: remote module (fortios_vpn_ipsec_phase1_interface) does not support check mode
    msg: remote module (fortios_vpn_ipsec_phase2_interface) does not support check mode
    msg: remote module (fortios_system_dhcp_server) does not support check mode
    msg: remote module (fortios_system_virtual_switch) does not support check mode
    msg: remote module (fortios_firewall_address) does not support check mode

### Subsequently running the playbook without check mode

    $ ansible-playbook site.yml

    [ ... truncated ... ]

    TASK [Configure LAN interface] *************************************************
    ok: [jantari-forti100e]

    [ ... truncated ... ]

it reports no change when *actually* applying / running without check mode. This is correct, as there was no change - but the reported change I got in check mode is therefore wrong?

### Verifying the configuration on the fortigate after the playbook run

    jantari-forti100e # show system interface lan
    config system interface
        edit "lan"
            set vdom "root"
            set ip 192.168.252.1 255.255.254.0
            set allowaccess ping fabric
            set type hard-switch
            set stp enable
            set device-identification enable
            set role lan
            set snmp-index 9
        next
    end

As we can see, nothing changed indeed.

---

If there is further information I can provide or tests I should run I can do that for a few more weeks, as long as I have my FG100E demo device :)

I also thought about bringing this up with our partner and Fortigate contacts who enabled the demo directly, but I felt that GitHub here might be the more direct route to the right people. Also, this is perhaps affecting other customers too so I wanted to ask the question publicly.

Thanks! And please do tell me if I'm doing something wrong!

EDIT: corrected ruined indentations in code examples

**Comment by JieX19** [comment]
Hi @jantari,

Yea, check_mode is only supported in fortios_system_interface so far. We're expanding the feature in most of the modules and will have a new release recently.

I tested the feature on my device and everything works fine. The first task is a Dry-run and it does not do any changes on the device, the second task is just skipped because the check_mode feature is not available in t the module.

**1: Current configuration for interface port1:**
```
FortiGate-VM (root) # show system interface port1
config system interface
edit "port1"
set vdom "root"
set ip 192.168.21.18 255.255.255.0
set allowaccess ping https ssh http
set type physical
set snmp-index 1
next
end
```
**2: First task won't change any thing on my device because it's a dry-run and second task is just skipped as check_mode is not supported in this module.**

```
- hosts: fortigate
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    vdom: "root"
  tasks:
  - name: Configure IPv4 interface
    fortios_system_interface:
      vdom: "{{ vdom }}"
      state: "present"
      access_token: "{{ fortios_access_token }}"
      system_interface:
        allowaccess:
          - "http"
          - "https"
          - "ping"
          - "ssh"
        name: "port1"

  - name: Configure Ipv4 address
    fortios_firewall_address:
      vdom: "{{ vdom }}"
      state: "present"
      access_token: "{{ fortios_access_token }}"
      firewall_address:
        allow_routing: "enable"
        comment: "second address"
        visibility: "enable"
        name: "costco.com"
```

**3. Results after running the playbook:**
The first task is just a dry-run
![check_mode](https://user-images.githubusercontent.com/59745792/117508248-1da2b380-af3d-11eb-91b6-7733dee6fa89.PNG)

The second task is skipped as expected
![Inkedskipped_LI](https://user-images.githubusercontent.com/59745792/117508497-8b4edf80-af3d-11eb-90fa-26d2fcd99052.jpg)

It's a bit wired that you did not change any thing but it reported changes. Can you help try another interface and don't change anything to see if there's any changes occur.

Thanks,
Jie
