### ISSUE TITLE
fortios_configuration_fact selector documentation

### ISSUE THREAD

**Issue by george10000** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#108]
Where can I view fortios_configuration_fact selector example return information? I'm trying to gather facts but am unaware what selector/subset will provide them. For example, what selector would provide device model information? 

Apologies, I'm not super familiar with fortios.

**Comment by george10000** [comment]
The hardware_status selector, which I would think holds this info comes back blank. Possibly because I'm running FOS v5.6.13?

**Comment by JieX19** [comment]
Hi @george10000,

Yes, version FOS 5.6 is not compatible with fortios galaxy collection. Please upgrade the firmware to FOS6.0 or later.

Documentation for fortios_configuration_fact https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_configuration_fact.html.
```
  tasks:
  - name: Get multiple selectors info
    fortios_configuration_fact:
        selectors:
            - selector: firewall_address
              params:
                name: "gmail.com"
        - selector: system_interface
        - selector: log_eventfilter
          params: {}
```

Documentation for fortios_monitor_fact https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_monitor_fact.html

This is the documentation for fortios galaxy collection https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/index.html.
