### ISSUE TITLE
Documentation issue in system_central_management

### ISSUE THREAD

**Issue by alex-eoi** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#112]
Hi,
i just stumbled upon a documentation issue using the `system_central_management` module. The module documentation says the parameter `server_type` is a string. According to the schema this parameter is expected to be a list.

Wrong:
```
    - name: Configure central management
      fortios_system_central_management:
        system_central_management:
          ... 
          server_list:
            - id: '1'
              server_address: '10.10.10.10'
              server_type: 'update'
```

Correct:
```
    - name: Configure central management
      fortios_system_central_management:
        system_central_management:
          ... 
          server_list:
            - id: '1'
              server_address: '10.10.10.10'
              server_type:
                      - 'update'
```

Unfortunately I'm not sure against which branch i have to issue a pull request against.

Kind regards,
Alex
