### ISSUE TITLE
Implement a static route that already exist play goes in failed

### ISSUE THREAD

**Issue by apellini** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#113]
With this play:

```
---
- name: Static route
  hosts: fortinet
  collections:
    - fortinet.fortios
  vars:
    config:
      route:
        - dst: 10.1.1.0/27
          device: ABC_PPP_P_OUT_9
          distance: 1
          gateway: 10.1.2.18
          vdom: PROD
       - dst: 10.1.2.128/27
         device: ABC_PPP_S_OUT_2
         distance: 1
         gateway: 10.1.2.26
         vdom: SYS
  tasks:
    - name: Configure route
      fortios_router_static:
        vdom: "{{ item.vdom }}"
        state: "present"
        router_static:
          dst: "{{ item.dst }}"
          device: "{{ item.device }}"
          distance: "{{ item.distance }}"
          gateway: "{{ item.gateway }}"
      loop: "{{ config.route }}"
```

When it is launched on first time it creates the route, instead if we launch a second time the playbook it encounters in error with this error:

```
  meta:
    build: 6828
    error: -15
    http_method: POST
    http_status: 500
    name: static
    old_revision: 21.6.0.4139306907121805100.1621358599
    path: router
    revision: 23.6.0.4139306907121805100.1621358599
    revision_changed: true
    serial: dsadasdasda
    status: error
    vdom: PROD
    version: v6.0.10
  msg: Error in repo
```

We expect an OK message because the route exists and it is identical,

Out Ansible Version:

```
ansible [core 2.11.1] 
  config file = /iii/NetDevOps/bbbbb/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.4 (default, Apr 14 2021, 10:57:48) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
  jinja version = 2.11.3
  libyaml = True
```

Ansible FortiOS Galaxy Collection:

fortinet.fortios              2.0.2
