### ISSUE TITLE
fortios_router_bgp unable to add new neighbor

### ISSUE THREAD

**Issue by toy4two** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#12]
it appears this ansible module is doing a PUT which works to update bgp parameters except the neighbors which must be done with a POST which doesn't currently work and you have to revert to a CURL inside a playbook to make it work.

Example of a working POST to accomplish this.  

curl -X POST "https://myfirewall.com:443/api/v2/cmdb/router/bgp/neighbor?vdom=test&access_token=apikeygoeshere" -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -d "{ \"ip\": 9.9.9.9, \"remote-as\": \"65000\" }"

Failure to do a POST to add a neighbor will delete existing entries and you will never be able to add more than a single neighbor.

**Comment by luchoArg33** [comment]
Hi,
I've found the same problem but I didn't know that changing a PUT with a POST would solve the issue. I can't use the module incrementally as everytime I try to add a new neighbor previous neighbors have to be specified in the playbook otherwise the play will erase old configuration.
Below you'll find a packet capture that I've made in my lab. Hope that helps to see the problem... =)

[Ansible-bgp-capture,2 peers 2.zip](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/files/4644381/Ansible-bgp-capture.2.peers.2.zip)

Cheers,
Luis

**Comment by chillancezen** [comment]
hello @toy4two @luchoArg33 ,
the issue that you can't use `remote-as` in current galaxy collection has been fixed https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/7, but it will be in next release very soon. You are still able to use the new galaxy collection binary here: 
```
$wget https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/releases/download/release_2020_05/fortinet-fortios-1.0.11.tar.gz
$ansible-galaxy collection install -f fortinet-fortios-1.0.11.tar.gz
```

and then configure more than one neighbors in your playbook.(note the api is not designed to update the neighbors incrementally, you have to input all your neighbors every time you have to update the bgp neighbors )

here is an example:
```
$cat hosts
[fortigates]
fortigate01 ansible_host=192.168.190.130 ansible_user="admin" ansible_password="password"

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios

$cat feature_09.yml
- hosts: fortigate01
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
   - name: Configure router bgp.
     fortios_router_bgp:
        vdom:  "{{ vdom }}"
        router_bgp:
            neighbor:
                - ip: '192.168.1.2'
                  remote_as: '1112'
                - ip: '192.168.1.1'
                  remote_as: '1111'
$ansible-playbook -i hosts  feature_09.yml
```

once new FortiOS galaxy is released, you don't have to download the binary and install like that way, I will keep the issue open util release is ready.

thanks again for the issue.
Link
