### ISSUE TITLE
Documention seems outdated for access_token usage in inventory file

### ISSUE THREAD

**Issue by a25484189** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#120]
Hi,

I tried to use to use an access token in the inventory file as described in [the documentation](https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.2/playbook.html).

But I only got the following error message: "Please provide access token or username/password to login".

Afterwards I added the access_token as parameter to my task (which uses fortios_monitor_fact modul) which worked.

The documentation is probably a bit outdated.

PS: I used version 2.0.2

**Comment by chillancezen** [comment]
hi @a25484189 , 

you also need to reference the access token in tasks.
```
- hosts: fortigate03
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
   - name: Configure global attributes.
     fortios_system_global:
        vdom:  "{{ vdom }}"
        access_token: "{{ fortios_access_token }}" #if you prefer access token based authentication, add this line.
        system_global:
            hostname: 'CustomHostName'
```

could you please try it?
