### ISSUE TITLE
Ansible config backup

### ISSUE THREAD

**Issue by ryanmerolle** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#122]
If you enabled discussions in this project, this issue would be better suited in a discussion than an issue.

Normally, I use the {{ ansible_network_os }}_config to backup.  Currently, I shell / scp in ansible to grab the sys_config  in order to backup the device.

Unfortunately, this cycles the hashes everytime I pull said config, creating a diff event in git even when config really did not change from my last backup.

Given the recent changes to the collection, is there a better way to approach this?  Should I use config_facts or soemthing else?

Suggestions would greatly be appreciated!

**Comment by ryanmerolle** [comment]
Looking through the docs it looks like:

```
- name: Backup a virtual domain.
  fortios_monitor_fact:
     selector: 'system_config_backup'
     vdom: 'root'
     params:
         scope: 'global'
  register: backupinfo

- name: Save the backup information.
  copy:
     content: '{{ backupinfo.meta.raw }}'
     dest: './local.backup'
```

My question is, does this backup all vdoms when multiple vdoms are present, or does it just backup the config global section?
