### ISSUE TITLE
Issue with creating addr objects in FortiManager

### ISSUE THREAD

**Issue by mpsikorski** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#131]
Hi,

we tried to use the new Ansible (ansible-2.9.23-1.el7.noarch centos7) modules for creating address objects in Fortimanager v6.2.8-build1435 and wrote the following playbook:
```
---
- name: Address and Address Group Creation
  hosts: FORTINET_FORTIMANAGER
  connection: httpapi
  collections:
  - fortinet.fortimanager
  gather_facts: no
  vars:
    ansible_network_os: fortinet.fortimanager.fortimanager
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  vars_prompt:
  - name: "ansible_user"
    prompt: "Username"
    private: no
    default: "{{ lookup('env', 'USER') }}"
  - name: "ansible_password"
    prompt: "Password"

  tasks:
   - name: Create an ipv6 address
     fmgr_firewall_address6:
        workspace_locking_adom: "XTC_6_2"
        workspace_locking_timeout: 300
        adom: "XTC_6_2"
        state: "present"
        enable_log: yes
        bypass_validation: False
        firewall_address6:
           comment: "TESTv6"
           ip6: "1000:2000:3000:4000::/64"
           name: "Testv6"
           type: "ipprefix"
           visibility: enable
```
Unfortunatly this playbook just locks and unlocks the ADOM XTC_6_2 and doesn't create an address.
I hope that this the right place for support - your hardware support team told us to ask you here.

Best regards,
Maxime
