### ISSUE TITLE
fortios_system_interface: using secondaryip throws AssertionError

### ISSUE THREAD

**Issue by Smoetzak** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#135]
When using fortios_system_interface: if secondaryip parameter is set, an AssertionError is thrown.

The documentation https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_system_interface.html describes the parameter as a list.

Here is the task:

```
---
- name: Configure lan interface 
  fortios_system_interface:
    vdom:  "root"
    state: "present"
    system_interface:
      name: "lan"
      ip: "192.168.1.100/24"
      allowaccess: "ping,https,ssh,fabric"
      device_identification: enable
      stp: enable
      secondary_IP: "enable" 
      secondaryip: 
        -      
          id: "1"
          allowaccess: "ping,https,ssh,fabric"
          detectprotocol: "ping"
          ip: "192.168.1.99/24"   
      role: lan
      type: hard-switch
```

Here is the result:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AssertionError
fatal: [smoetwall]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-4098phh0odk9/ansible-tmp-1633639654.6839573-4103-238557894423186/AnsiballZ_fortios_system_interface.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-4098phh0odk9/ansible-tmp-1633639654.6839573-4103-238557894423186/AnsiballZ_fortios_system_interface.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-4098phh0odk9/ansible-tmp-1633639654.6839573-4103-238557894423186/AnsiballZ_fortios_system_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_interface', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_interface', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_system_interface_payload_wl10rfos/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_interface.py\", line 13060, in <module>\n  File \"/tmp/ansible_fortios_system_interface_payload_wl10rfos/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_interface.py\", line 13037, in main\n  File \"/tmp/ansible_fortios_system_interface_payload_wl10rfos/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 266, in check_schema_versioning\n  File \"/tmp/ansible_fortios_system_interface_payload_wl10rfos/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 207, in check_schema_versioning_internal\n  File \"/tmp/ansible_fortios_system_interface_payload_wl10rfos/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 196, in check_schema_versioning_internal\nAssertionError\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

fortios_system_interface works well when not using secondaryip.

**Comment by Smoetzak** [comment]
Hello


Thanks for looking into this.
I've tried deleting the allowaccess entry as it is not required, but still got the assertion error:

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AssertionError
fatal: [smoetwall]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-8057k8j2tcd1/ansible-tmp-1634025784.6439543-8063-279106765419072/AnsiballZ_fortios_system_interface.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-8057k8j2tcd1/ansible-tmp-1634025784.6439543-8063-279106765419072/AnsiballZ_fortios_system_interface.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-8057k8j2tcd1/ansible-tmp-1634025784.6439543-8063-279106765419072/AnsiballZ_fortios_system_interface.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_interface', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_interface', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_system_interface_payload_bik3u3py/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_interface.py\", line 13060, in <module>\n  File \"/tmp/ansible_fortios_system_interface_payload_bik3u3py/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_interface.py\", line 13037, in main\n  File \"/tmp/ansible_fortios_system_interface_payload_bik3u3py/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 266, in check_schema_versioning\n  File \"/tmp/ansible_fortios_system_interface_payload_bik3u3py/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 207, in check_schema_versioning_internal\n  File \"/tmp/ansible_fortios_system_interface_payload_bik3u3py/ansible_fortios_system_interface_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 196, in check_schema_versioning_internal\nAssertionError\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`


They task now looks like this:

```
- name: Configure lan interface 
  fortios_system_interface:
    vdom:  "root"
    state: "present"
    system_interface:
      name: "lan"
      ip: "192.168.1.100/24"
      allowaccess: "ping,https,ssh,fabric"
      device_identification: enable
      stp: enable
      secondary_IP: "enable"
      secondaryip: 
        -      
          id: "1"
          detectprotocol: "ping"    # This is required, otherwise I get KeyError: 'detectprotocol'
          ip: "192.168.1.99/24"   
      role: lan
      type: hard-switch
```
