### ISSUE TITLE
"hardware status" returns empty result set

### ISSUE THREAD

**Issue by kaon1** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#136]
Running ansible playbook to call "hardware status" I receive 200 OK but the result set is empty. I'm expecting to see the model_name in the result.

Tried with 2 different modules (json_generic and configuration_fact) and 2 types of authentication (token and un/pw).

Playbook1 attempt:
```
    - name: get hardware status
      fortinet.fortios.fortios_json_generic:
        json_generic:
          method: "GET"
          path: "/api/v2/cmdb/hardware/status"
        access_token: "{{ access_token }}"
      register: info
```
Playbook2 attempt:
```
    - name: get hardware status
      fortinet.fortios.fortios_configuration_fact:
        selector: hardware_status
        access_token: "{{ access_token }}"
      register: info
```

ansible result:
```
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "enable_log": null,
            "filters": null,
            "formatters": null,
            "params": null,
            "selector": "hardware_status",
            "selectors": null,
            "sorters": null,
            "vdom": "root"
        }
    },
    "meta": {
        "build": 1232,
        "http_method": "GET",
        "http_status": 200,
        "name": "status",
        "path": "hardware",
        "results": {},
        "revision": "redacted",
        "serial": "redacted",
        "status": "success",
        "vdom": "root",
        "version": "v6.2.8"
    }
}
```

httpd log entry:
```
[httpsd 439 - 1633655605     info] fweb_debug_final[203] -- Completed GET request for "/api/v2/cmdb/system/interface" (HTTP 200 OK)
```

Attempted this on two different FortiGate's. One running v6.0 another on v6.2. My client machine is using python3.6.8, ansible 2.9.5 using the latest galaxy collection
