### ISSUE TITLE
fortios_vpn_ipsec_phase1_interface module not functioning!

### ISSUE THREAD

**Issue by bradley-rose** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#137]
The `fortios_vpn_ipsec_phase1_interface` module is not working correctly as the documentation would specify. None of the required parameters are accepted as input. Here is my basic playbook: 

```
---
hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  gather_facts: no
  tasks: 
  - name: Create IPSec Phase 1 Configuration
    fortios_vpn_ipsec_phase1_interface:
      vdom: "{{ vdom }}"
      state: "present"
      access_token: "{{ access_token }}"
      vpn_ipsec_phase1_interface:
        name: "test_VPN"
        interface: "port3"
```

I started with an extremely minimal configuration to see what parameters would be required. The first error message that was output was: 
> _"FAILED: "changed": [...] invalid gateway address\n node_check_object fail! for remote-gw 0.0.0.0\n"_

As soon as I add in a "remote-gw" into the configuration, I get an error suggesting that this parameter is unsupported.

```
---
hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  gather_facts: no
  tasks: 
  - name: Create IPSec Phase 1 Configuration
    fortios_vpn_ipsec_phase1_interface:
      vdom: "{{ vdom }}"
      state: "present"
      access_token: "{{ access_token }}"
      vpn_ipsec_phase1_interface:
        name: "test_VPN"
        interface: "port3"
        remote-gw: 10.69.69.69
```

This playbook produces this error:

> _"Unsupported parameters for (fortios_vpn_ipsec_phase1_interface) module: vpn_ipsec_phase1_interface.remote-gw. Supported parameters include: vdom, vpn_ipsec_phase1_interface, access_token, enable_log, state."_

I'm not entirely sure how to proceed with building out this task. The required parameters don't appear to be supported by the module.
