### ISSUE TITLE
Errors using fortios_system_switch_interface library to create software switch!

### ISSUE THREAD

**Issue by bradley-rose** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#139]
I'm attempting to create a very simple software switch on an otherwise factory-default FortiGate. I'm using the bare minimum required parameters, and the module is throwing HTTP_Status 500 with a message: "Error in repo." The [official documentation is here](https://docs.ansible.com/ansible/latest/collections/fortinet/fortios/fortios_system_switch_interface_module.html) for reference.

Here is my playbook.yml:  

```yml
---
- hosts: fg
  collections: 
  - fortinet.fortios
  connection: httpapi
  gather_facts: no
  tasks:
  - name: Software Switch
    include_role:
      name: switch
```

./roles/switch/tasks/main.yml:  
```yml
---
# tasks file for creating Software Switch
- name: Create Software Switch for LAN Interface Grouping
  fortios_system_switch_interface:
    vdom: "{{ vdom }}"
    state: "present"
    system_switch_interface: 
      name: "default_name"
```

Not sure what to make of this. I obviously cannot create the software switch considering the one and only required parameter is throwing an error.

**Comment by JieX19** [comment]
Hi @bradley-rose 

I tried the module on fortios version 7.0.1 and it works. Can you just run the playbook below to see if there're any errors?

Set up the hosts file before running the playbook:
1. create the default hosts file under /etc/ansible/hosts (You may need to create the directory by yourself)
    $ sudo vim /etc/ansible/hosts
2. Here's an example for the hosts file
    ```
    [fortigates]
    fortigate01 enable_log=True ansible_host=192.168.23.21

    [fortigates:vars]
    ansible_network_os=fortinet.fortios.fortios
    access_token=stgyq3yG15d1475z9qqb80kzs4gf5r (It's generated from GUI)
    ```


Here's the playbook I used:
```
- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Configure software switch interfaces by grouping physical and WiFi interfaces.
    fortios_system_switch_interface:
      vdom:  "{{ vdom }}"
      state: "present"
      access_token: "{{ access_token }}"
      system_switch_interface:
        name: "wifi"
        vdom: "{{ vdom }}"
```

The latest fortios collection doc is https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/index.html, please look up the doc for your reference.

**Comment by bradley-rose** [comment]
I've got a hosts file configured and well in use for both this issue. I hadn't posted it initially as it was lengthy and full of variables and data. Here's a truncated hosts file (I'm using the YAML hosts file format): 

```yml
---
all:
  vars:
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    ansible_network_os: fortinet.fortios.fortios
    vdom: "root"
  children:
    test:
      vars: 
        ansible_user: "admin"
        ansible_password: "admin"
      hosts:
        FGhostname:
          ansible_host: <IP Address omitted>
```

I'm not using an API key as I plan on developing this configuration to be used for bulk deployments. I am unable to create a single API key that works for all devices, so I'm resorting to using a username and password. That said, this FortiGate is close to factory default, so I've got the username as `admin` and the password as `admin`.

That said, I'm just about to sleep. I'll try the above playbook tomorrow morning. Thank you for giving this a run.

**Comment by bradley-rose** [comment]
Unsure what the issue was. Must have had some formatting errors. Here is the working playbook using the above hosts file: 

```yml
---
- hosts: all
  collections: 
  - fortinet.fortios
  connection: httpapi
  gather_facts: no
  tasks:
  - name: Configuring a SW int
    fortios_system_switch_interface:
      vdom:  "{{ vdom }}"
      state: "present"
      system_switch_interface:
        name: "Internal"
        type: "switch"
        vdom: "{{ vdom }}"
        member: 
        - interface_name: "port3"
        - interface_name: "port4"
        span: "disable"
```
