### ISSUE TITLE
Error using fortios_firewall_policy module to create firewall policies!

### ISSUE THREAD

**Issue by bradley-rose** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#140]
Similar to [this issue](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/139), I'm receiving an HTTP_Status 500 with an error message of "error in repo" on a very simple firewall policy creation.

```yml
---
- hosts: fg
  collections: 
  - fortinet.fortios
  connection: httpapi
  gather_facts: no
  tasks:
  - name: Firewall Policy
    include_role:
      name: firewall
```

./roles/firewall/tasks/main.yml:  
```yml
- name: Create basic firewall policy
  fortios_firewall_policy:
    vdom: "{{ vdom }}"
    state: "present"
    firewall_policy:
      policyid: "1"
```

I cannot find a way to get this module to create any form of firewall policy. I've tried for the last few hours to make a single policy, and I'm getting thrown the same error each time.
