### ISSUE TITLE
FortiOS v7 support 

### ISSUE THREAD

**Issue by vingertop** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#142]
Hi All, 

Will there be support for FortiOS v7 anytime soon in this collection ?
Running v7.0.1 build0157 (GA) :

**Playbook :** 

`- hosts: fortigate
  connection: httpapi
  collections:
    - fortinet.fortios
  
  vars:
    vdom: "specific vdom"
    host: "{{ ansible_host}}"
    username: "{{ansible_ssh_user }}"
    password: "{{ ansible_ssh_pass }}"
    date: "{{ lookup('pipe', 'date +%Y-%m-%d-%Hh%Mm') }}"
    ansible_python_interpreter: /usr/bin/python3
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: "{{ ansible_port }}"
    ansible_network_os: fortinet.fortios.fortios

  tasks:
  - name: Create backup directory
    file: 
      path: "./backup/{{customer}}/{{location}}"
      state: directory

  - name: backup global settings
    fortios_system_config_backup_restore:
     config: "system config backup"
     host:  "{{ ansible_host }}"
     username: "{{ ansible_ssh_user }}"
     password: "{{ ansible_ssh_pass }}"
     #vdom: "{{ vdom}}"
     backup: "yes"
     https: True
     ssl_verify: False
     scope: "global"
     filename: "./backup/{{customer}}/{{location}}/{{inventory_hostname}}-global{{date}}.cfg"
`

**Output:**
`fatal: [xxxxxxxxxxxxxxxxxx]: FAILED! => changed=false 
  meta:
    resp:
      http_status: 401
      text: |-
        <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
        <html><head>
        <title>401 Unauthorized</title>
        </head><body>
        <h1>Unauthorized</h1>
        <p>This server could not verify that you
        are authorized to access the document
        requested.  Either you supplied the wrong
        credentials (e.g., bad password), or your
        browser doesn't understand how to supply
        the credentials required.</p>
        <p>Additionally, a 401 Unauthorized
        error was encountered while trying to use an ErrorDocument to handle the request.</p>
        </body></html>
    status: 500
  msg: Error
`

**Comment by JieX19** [comment]
@vingertop We recommend to use access_token, it can be generated on the GUI and you got to save the generated token so that you can access it in the future. 

<img width="300" alt="rest_api_admin" src="https://user-images.githubusercontent.com/59745792/139490776-0b08c73d-5366-43dc-be69-bcc09b3544e5.PNG">


But if you wanna use username and password, you can just simply configured the default inventory at **/etc/ansible/host**, which is the **default inventory path** for Ansible to look for. you may need to create ansible/host directory by yourself. In this way, tasks will be authenticated and executed automatically without writing username and password in the palybook.

```
[fortigates]
fortigate01 ansible_host=192.168.190.130 ansible_user="admin" ansible_password="password"
```

Or using the username and password in the playbook as follows:

```
- hosts: fortigates
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   ansible_user: admin
   ansible_password: your_password
  tasks:
  - name: Backup a virtual domain.
    fortios_monitor_fact:
      selector: 'system_config_backup'
      vdom: 'root'
      params:
       scope: 'global'
    register: backupinfo

  - name: Save the backup information.
    copy:
      content: '{{ backupinfo.meta.raw }}'
      dest: './local.backup'
~                             
```

The backup file would be stored at the location you assigned as follows:
<img width="464" alt="backup" src="https://user-images.githubusercontent.com/59745792/139493822-4290a2fa-b57f-439c-8e59-211fc96e4646.PNG">
