### ISSUE TITLE
cannot use Ansible to create a policy with multiple services

### ISSUE THREAD

**Issue by elvis0206** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#143]
I tried to use ansible for fortigate firewall policy creation with multiple services(like HTTP & HTTPS) and have errors. Like below example.
If there is only one service, like only HTTP, that no problems to be created by ansible.
Any ideas?

-name: Add Policy
   fortios_firewall_policy:
     vdom: FG-traffic      
     state: "present"       
     firewall_policy:
       name: "test_policy"
       policyid: 0
       action: "accept"
       dstaddr:
        -
         name: "192.168.30.101"
       dstintf: 
        -
         name: "Port2_VLAN30"
       srcaddr: 
        -
         name: "192.168.20.101"
       srcintf: 
        -
         name: "Port1_VLAN20"
       service: 
        -
         name: "HTTP HTTPS"
       schedule: "always"
       nat: "enable"

**Comment by elvis0206** [comment]
Thanks @mbdraks . Works with your example.

However, if there are multiple policies with different service, we cannot hard code the service name. Instead, a loop will be needed. Can have your suggestion on this?

[policy.csv](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/files/7451745/policy.csv)
.

**Comment by JieX19** [comment]
@elvis0206  Can you please provide us the playbook you used when creating multiple policies with multiple services?

**Comment by elvis0206** [comment]
@JieX19 

Here you are, also provided the policy csv. I think there a problem when looping the services. I'm still try to solve it
The playbook work without any problems when there is only one service in each policy.

thanks in advance

Playbook below
=============================================================
---
- hosts: all
  collections:
    - community.general
    - fortinet.fortios

  tasks:
  - name: Read policy from csv
    local_action: read_csv path=policy.csv
    register: policy

  - name: Add Policy
    loop: "{{ policy.list }}"
    loop_control: 
      loop_var: pol
    fortios_firewall_policy:
        vdom: FG-traffic      
        state: "present"       
        firewall_policy:
            name: "{{ pol.name }}"
            policyid: 0
            action: "accept"
            dstaddr:
             -
                name: "{{ pol.dstaddr }}"
            dstintf: 
             -
                name: "{{ pol.dstintf }}"
            srcaddr: 
             -
                name: "{{ pol.srcaddr }}"
            srcintf: 
             -
                name: "{{ pol.srcintf }}"
            service: 
             - name: "{{ pol.service }}"
            schedule: "always"
            nat: "enable"

[policy.csv](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/files/7457179/policy.csv)

**Comment by JieX19** [comment]
@elvis0206 Thanks for the info! 

There's a way to deal with this issue by using a built-in module called **set_fact**, which can help preprocess the value of 'service'. In this way, for example, the value of 'service' for policyid_0 will be saved in a list at once. 

We can use the preprocessed value of the 'service' in the second task (Add policy), so all the values in 'service' are applied without any looping.

Here's a doc to illustrate how to use the set_fact module in a task. https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-use-the-set-fact-module-in-a-task

**Comment by elvis0206** [comment]
@JieX19 Thanks for the demo link

I tried this before.

However, from the demo, it assumes only to create one address group and the addresses(vars: demo_input) is hard coded. If I need to create multiple address groups by ansible, I will put the addresses into csv and loop through the group name and addresses column. 
Therefore, I'm not sure how to use the set_fact module.

**Comment by elvis0206** [comment]
@JieX19   I can create the policy using your suggestion now. However, there are still some problems

As policy1 only need ALL_TCP and HTTP, policy2 only need ALL_ICMP and HTTPS, if I use the suggested way to create the polices, all services will be configured to policy1 and policy2. 


Playbook below
---
- hosts: all
  collections:
    - community.general
    - fortinet.fortios
  vars:
    list: []
    list2: []

  tasks:
  - name: Read address objects
    local_action: read_csv path=policy.csv
    register: policy

  - name: Loop service for each policy
    set_fact:
      list: "{{ list + [ item.service.split(',') ] }}"
    with_items: "{{ policy.list }}"
  
  # - debug: var=list

  - set_fact:
      list2: "{{ list2 + [{'name': item.strip(' ')}] }}"
    with_items: "{{ list }}"

  - debug: var=list2

  - name: Add Policy
    loop: "{{ policy.list }}"
    loop_control: 
      loop_var: pol
    fortios_firewall_policy:
        vdom: FG-traffic      
        state: "present"       
        firewall_policy:
            name: "{{ pol.name }}"
            policyid: 0
            action: "accept"
            dstaddr:
             -
                name: "{{ pol.dstaddr }}"
            dstintf: 
             -
                name: "{{ pol.dstintf }}"
            srcaddr: 
             -
                name: "{{ pol.srcaddr }}"
            srcintf: 
             -
                name: "{{ pol.srcintf }}"
            service: "{{ list2 }}" 
            schedule: "always"
            nat: "enable"

![image](https://user-images.githubusercontent.com/42794088/139804666-f11562c6-169c-4afb-af2c-fb9e296ffaab.png)

**Comment by jantari** [comment]
That is expected.

```yaml
- name: Loop service for each policy
  set_fact:
    list: "{{ list + [ item.service.split(',') ] }}"
  with_items: "{{ policy.list }}"
```

Here you are looping through all policies and keep appending the service-names to the same one variable ("`list`"). Therefore, `list` now contains all 4 service names from the CSV. What you want is not one global list of all services ever mentioned in the CSV, you want just the specific services mentioned *per row*. You want this:

```yaml
- name: Add Policy
  fortios_firewall_policy:
    vdom: FG-traffic
    state: "present"
    firewall_policy:
      name: "{{ pol.name }}"
      policyid: '{{ loop_index + 1 }}' # +1 because policyid 0 is the implicit deny rule
      action: "accept"
      dstaddr:
        - name: "{{ pol.dstaddr }}"
      dstintf:
        - name: "{{ pol.dstintf }}"
      srcaddr:
        - name: "{{ pol.srcaddr }}"
      srcintf:
        - name: "{{ pol.srcintf }}"
      service: >
        [ {% for service in pol.service.split(',') %} { 'name': '{{ service | trim }}' }, {% endfor %} ]
      schedule: "always"
      nat: "enable"
  loop: "{{ policy.list }}"
  loop_control:
    loop_var: pol
    index_var: loop_index
```

However I would recommend JSON or YAML over CSV as a format for defining your firewall policies. It's much easier to define lists like this then and you get to make multi-line strings such as policy comments without deranging the format. Also you're not able to leave comments inside the CSV file itself, YAML supports comments starting with `#` so you can have some extra explanation or documentation next to your policies.
