### ISSUE TITLE
fortios_configuration_fact: formatters parameter seems to have no effect

### ISSUE THREAD

**Issue by robertegithub** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#147]
Based on the example here, https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.1.3/fortios_configuration_fact.html, it looks like we would use the elements in the results ("fields") to filter on?

```
  - name: fact gathering with filters
    fortios_configuration_fact:
        vdom: ""
        filters:
         - name==port1
         - vlanid==0
        sorters:
         - name,vlanid
         - management-ip
        formatters:
         - name
         - management-ip
         - vlanid
        selector: 'system_interface' 
```

The "name", "management-ip", and "vlanid" are parameters for the fortios_system_interface, and although there is no example output shown, we would expect the output for that selector will show only those three items (?).

However, using a similar task configuration:

```
    - name: Get the configuration
      fortinet.fortios.fortios_configuration_fact:
        selector: 'system_dns'
        formatters:
         - primary
         - secondary
         - domain
      register: existing_config
```

We get (existing_config):

```
ok: [test_host] => {
    "msg": {
        "changed": false,
        "failed": false,
        "meta": {
            "build": 1911,
            "http_method": "GET",
            "http_status": 200,
            "name": "dns",
            "path": "system",
            "results": {
                "cache-notfound-responses": "disable",
                "dns-cache-limit": 5000,
                "dns-cache-ttl": 1800,
                "dns-over-tls": "disable",
                "domain": [],
                "interface": "",
                "interface-select-method": "auto",
                "ip6-primary": "::",
                "ip6-secondary": "::",
                "primary": "1.2.3.4",
                "retry": 2,
                "secondary": "8.8.8.8",
                "server-hostname": [],
                "source-ip": "0.0.0.0",
                "ssl-certificate": "Fortinet_Factory",
                "timeout": 5
            },
            "revision": "3c01569921dc79dd81cc6fea70bff2c4",
            "serial": "FG1K...",
            "status": "success",
            "vdom": "root",
            "version": "v6.4.7"
        }
    }
}
```

The task details show that the formatters are being used:

```
ok: [test_host] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": null,
            "filters": null,
            "formatters": [
                "primary",
                "secondary",
                "domain"
            ],
            "params": null,
            "selector": "system_dns",
            "selectors": null,
            "sorters": null,
            "vdom": "root"
        }
...
```

But the output is not being filtered

Versions:

```
ansible-playbook [core 2.11.6] 
  config file = /home/user/ansible/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/ansible/ansible/venv3.9.7/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/ansible/ansible/venv3.9.7/bin/ansible-playbook
  python version = 3.9.9 (main, Nov 16 2021, 03:05:18) [GCC 7.5.0]
  jinja version = 3.0.2
```

```
user@host:ansible$ ansible-galaxy collection list

# /home/user/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.netcommon     2.4.0  
ansible.utils         2.4.2  
fortinet.fortios      2.1.3  
junipernetworks.junos 2.6.0  
```
