### ISSUE TITLE
Move firewall policy to absolute position

### ISSUE THREAD

**Issue by jantari** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#148]
After #53 it is now possible to move a policy relative to another, e.g. "move ID 2000 to the spot right above ID 342"

However this is tedious and requires one to know both the ID of the policy one wants to move (that is a given of course) AND the ID of the policy one wants to move relative to AND the knowlege which of the two move operations (before or a after) has to be used to achieve the desired result.

For example, when I want to move a policy to the very top (position 1) I cannot use "after:" logic because there is no rule above the desired position.

Instead I have to figure out the ID of the rule in position 1 and then move my new rule "before" it.
For the last rule I have to use "after". This is a hassle and means one cannot simply loop over all policies and set their desired position in the policy table, e.g. when I have an ordered list of my policies I would like to be able to just do:

```yaml
- name: Move all policies to their correct position
  fortios_firewall_policy:
    vdom: "{{ vdom }}"
    access_token: "{{ fortios_access_token | default(omit) }}"
    action: move
    self: '{{ item.id }}'
    position: '{{ index }}'
  loop: '{{ policies[:-1] }}'
  loop_control:
    index_var: index
```

and one cannot simply loop through the policies in their intended order and move each policy before the next one because that doesn't end up actually sorting them properly. For example using this task:

```yaml
- name: Move all policies to their correct position
  fortios_firewall_policy:
    vdom: "{{ vdom }}"
    access_token: "{{ fortios_access_token | default(omit) }}"
    action: move
    self: '{{ item.id }}'
    before: '{{ ansible_loop.nextitem.id }}'
  loop: '{{ _policies[:-1] }}'
  loop_control:
    extended: true
```

would result in the following:

| Intended Policy order | Before Task (wrong order) | After Task (still wrong order) |
|---|---|---|
| 1 | 1 | 1 |
| 2 | 2 | 4 |
| 3 | 5 | 5 |
| 4 | 3 | 2 |
| 5 | 4 | 3 |

So one has to get the current positions of all policies, then calculate which policies need to be moved relative to which other policy and whether a before or after move has to be made to end up with the correct order in the end, then execute this overly complex moving-logic WHILST hoping that no race condition occurs during all this time due to policies being moved by someone or something else in the which would invalidate our pre-calculated sorting plan of attack.

If we could just say "move policy 42 to position 0" this would be trivial and fast.
