### ISSUE TITLE
Feature request: fortios_configuration_fact: Allow filtering (formatters) on nested elements

### ISSUE THREAD

**Issue by robertegithub** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#151]
Currently formatters work on only the highest level keys for selectors (at least for nested lists of dicts). So something like this:

```
    - name: Get the current config
      fortinet.fortios.fortios_configuration_fact:
        selector:  'system_ntp'
        formatters:  
          - ntpsync
          - source-ip
          - ntpserver
```

will return:

```
ok: [172.20.21.22] => {
    "ansible_facts": {
        "running_conf": {
            "ntpserver": [
                {
                    "authentication": "disable",
                    "id": 1,
                    "interface": "",
                    "interface-select-method": "auto",
                    "key": "",
                    "key-id": 0,
                    "ntpv3": "disable",
                    "server": "1.2.3.4"
                }
            ],
            "ntpsync": "enable",
            "source-ip": "172.20.21.22",
        }
    },
    "changed": false
}
```

What we'd like is to be able to filter on nested dict and list elements, like:

```
    - name: Get the current config
      fortinet.fortios.fortios_configuration_fact:
        selector:  'system_ntp'
        formatters:  
          - ntpsync
          - source-ip
          - ntpserver[0].server
```

so that we only get:

```
ok: [172.20.21.22] => {
    "ansible_facts": {
        "running_conf": {
            "ntpserver": [
                {
                    "server": "1.2.3.4"
                }
            ],
            "ntpsync": "enable",
            "source-ip": "172.20.21.22",
        }
    },
    "changed": false
}
```
