### ISSUE TITLE
Major bug while using fortios_certificate_local on FortiOS 7.0.2

### ISSUE THREAD

**Issue by winromulus** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#152]
Hi,

I'm experiencing a very weird situation with `fortios_certificate_local`
Creating a new certificate with it results in an "invisible" certificate that does not show up in the GUI or the CLI or in config backup, but it's there somewhere since manually creating another certificate with the same domain results in an error.
Values used:
```
      certificate_local:
        acme_domain: "gateway.domain.com"
        acme_email: "mail@mail.mail"
        enroll_protocol: acme2
        name: "gateway"
```

Creating a certificate using the CLI and the values above results in a proper certificate (visible everywhere)
I'm not sure what's going on and where that "invisible" certificate is stored because I've searched for it everywhere.
