### ISSUE TITLE
Bug in fortios_system_dns_database while using member_path

### ISSUE THREAD

**Issue by winromulus** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#154]
Hi,

There seems to be a bug in `fortios_system_dns_database` when using `member_path`:

```
    - name: setup - dns - entries
      fortios_system_dns_database:
        access_token: "{{ access_token }}"
        state: "present"
        member_state: "present"
        member_path: "dns_entry:id"
        system_dns_database:
          name: domain.com
          dns_entry: 
            - id: 2
              hostname: entry
              ip: 8.8.8.8
```

Running the above results in:
```
AssertionError: Invalid top level parameter name:system_dns_database
fatal: [gateway]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/romeo/.ansible/tmp/ansible-local-18082eso2xnst/ansible-tmp-1639327477.603307-18143-276916254570120/AnsiballZ_fortios_system_dns_database.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/romeo/.ansible/tmp/ansible-local-18082eso2xnst/ansible-tmp-1639327477.603307-18143-276916254570120/AnsiballZ_fortios_system_dns_database.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/romeo/.ansible/tmp/ansible-local-18082eso2xnst/ansible-tmp-1639327477.603307-18143-276916254570120/AnsiballZ_fortios_system_dns_database.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_dns_database', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_system_dns_database', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_system_dns_database_payload_ljbmufze/ansible_fortios_system_dns_database_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_dns_database.py\", line 1251, in <module>\n  File \"/tmp/ansible_fortios_system_dns_database_payload_ljbmufze/ansible_fortios_system_dns_database_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_dns_database.py\", line 1230, in main\n  File \"/tmp/ansible_fortios_system_dns_database_payload_ljbmufze/ansible_fortios_system_dns_database_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_system_dns_database.py\", line 428, in fortios_system\n  File \"/tmp/ansible_fortios_system_dns_database_payload_ljbmufze/ansible_fortios_system_dns_database_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 490, in do_member_operation\n  File \"/tmp/ansible_fortios_system_dns_database_payload_ljbmufze/ansible_fortios_system_dns_database_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 342, in _process_sub_object\nAssertionError: Invalid top level parameter name:system_dns_database\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
```

**Comment by Raimond56** [comment]
Hello,

Same error happens with module fortinet.fortios.fortios_vpn_ssl_settings when using member_path

```
    - name: Configure new group to VPN settings
      fortinet.fortios.fortios_vpn_ssl_settings:
        member_path: authentication_rule:id/groups:name
        member_state: present
        vpn_ssl_settings:
          authentication_rule:
            -
              id: 1
              groups:
                - name: new_group
              portal: full-access
```

```
AssertionError: Invalid top level parameter name:vpn_ssl_settings
fatal: [test_host]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/rilves/.ansible/tmp/ansible-local-3741s51mlyp1/ansible-tmp-1639647239.9711313-3788-15467833097856/AnsiballZ_fortios_vpn_ssl_settings.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/rilves/.ansible/tmp/ansible-local-3741s51mlyp1/ansible-tmp-1639647239.9711313-3788-15467833097856/AnsiballZ_fortios_vpn_ssl_settings.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/rilves/.ansible/tmp/ansible-local-3741s51mlyp1/ansible-tmp-1639647239.9711313-3788-15467833097856/AnsiballZ_fortios_vpn_ssl_settings.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_fortinet.fortios.fortios_vpn_ssl_settings_payload_LSR9AP/ansible_fortinet.fortios.fortios_vpn_ssl_settings_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_vpn_ssl_settings.py\", line 4276, in <module>\n  File \"/tmp/ansible_fortinet.fortios.fortios_vpn_ssl_settings_payload_LSR9AP/ansible_fortinet.fortios.fortios_vpn_ssl_settings_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_vpn_ssl_settings.py\", line 4255, in main\n  File \"/tmp/ansible_fortinet.fortios.fortios_vpn_ssl_settings_payload_LSR9AP/ansible_fortinet.fortios.fortios_vpn_ssl_settings_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_vpn_ssl_settings.py\", line 876, in fortios_vpn_ssl\n  File \"/tmp/ansible_fortinet.fortios.fortios_vpn_ssl_settings_payload_LSR9AP/ansible_fortinet.fortios.fortios_vpn_ssl_settings_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 490, in do_member_operation\n  File \"/tmp/ansible_fortinet.fortios.fortios_vpn_ssl_settings_payload_LSR9AP/ansible_fortinet.fortios.fortios_vpn_ssl_settings_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 342, in _process_sub_object\nAssertionError: Invalid top level parameter name:vpn_ssl_settings\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by Raimond56** [comment]
This seems to work now with 2.1.4 version and tested with python 3.9

**Comment by Raimond56** [comment]
This is still an issue. Tested again with 2.1.5 
No error is given, but group does not get added to the authentication rule - ansible reports back "ok"
This time also tested with users and the results are the same. Only check member_path up until authentication rule.

These are the playsbooks I tested with:
```
  - name: add VPN group to VPN settings correct portal
      fortinet.fortios.fortios_vpn_ssl_settings:
        member_state: present
        member_path: authentication_rule:id/groups:name
        vpn_ssl_settings:
          authentication_rule:
            - 
              id: 1 
              groups: 
                - name: new_test_group
              portal: full-access

  - name: add VPN group to VPN settings correct portal
      fortinet.fortios.fortios_vpn_ssl_settings:
        member_state: present
        member_path: authentication_rule:id/users:name
        vpn_ssl_settings:
          authentication_rule:
            - 
              id: 1 
              users: 
                - name: new_test_group
              portal: full-access

```
