### ISSUE TITLE
fortios_system_zone

### ISSUE THREAD

**Issue by afly007** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#159]
```
  - name: Add the new interface to the OOBM-Switches zone
     the zone.
    fortios_system_zone:
      vdom:  "{{ vdom }}"
      state: "present"
      access_token: "{{ fortios_access_token }}" 
      system_zone:
        interface: 
        -
            interface_name: "OOBM-TEST-21"
        intrazone: "deny"
        name: "OOBM-Switches"
```

How do I update an existing zone that already has members populated?  The code above overwrites the Zone membership.

Thanks

**Comment by JieX19** [comment]
Hi @afly007 

This is a knowing limitation for our current API implementation. One workaround you can do is using the set_fact module to preprocess your interfaces and then apply the prepared data in the next task.

Here's an example about using set_fact in a playbook.
https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-use-the-set-fact-module-in-a-task

```
- hosts: fortigateslab
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: 'root'
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    demo_input: 'port3, port4, port5, OOBM-TEST-21'
    demo_members: []
  tasks:
    - name: Process input content
      set_fact:
        demo_members: "{{ demo_members + [{'interface_name': item.strip(' ')}] }}"
      with_items:
        - "{{demo_input.split(',')}}"
  
   - name: Add the new interface to the OOBM-Switches zone
     fortios_system_zone:
      vdom:  "{{ vdom }}"
      state: "present"
      access_token: "{{ fortios_access_token }}" 
      system_zone:
        interface:  '{{ demo_members }}'
        intrazone: "deny"
        name: "OOBM-Switches"
```
In the above example, the only thing you care about is the variable 'demo_input', you can get the current values of the zone 'OOBM-Switches' and add them to the demo_input and keep all the wanted values in it. The second task will take the variable 'demo_members' and apply all the values in it to the param 'interface'.

**Comment by JieX19** [comment]
Hi @afly007 

Member operation for FortiOS subattributes has been supported since 2.1.3. It allows adding one or more members to an existing list without overwriting the current values. 

https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_system_zone.html

Using 'member_path' and 'member_state' to do the task. 

```
   - name: Add the new interface to the OOBM-Switches zone
     fortios_system_zone:
      vdom:  "{{ vdom }}"
      state: "present"
      member_state: present
      member_path: tagging:name/tags:name (your_own_value)
      access_token: "{{ fortios_access_token }}" 
      system_zone:
        interface:  '{{ demo_members }}'
        intrazone: "deny"
        name: "OOBM-Switches"
        tagging:
          name: (your_own_value)
          tags:
              name: (your_own_value)
```
