### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by trump4coin** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#165]
Hi

i have installed in my lab a fortimanager in version 6.4.
```
admin@debiantemplate:~/40gate/ansible/playbook$ ansible-playbook -i hosts  fmgr_system_route.yml

PLAY [fortimanager] *************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: too many values to unpack (expected 2)
fatal: [11.22.33.44]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
11.22.33.44             : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0


```
```
The full traceback is:
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 147, in run
    res = self._execute()
  File "/home/admin/.local/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 620, in _execute
    self._connection = self._get_connection(cvars, templar)
  File "/home/admin/.local/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 953, in _get_connection
    socket_path = start_connection(self._play_context, options, self._task._uuid)
  File "/home/admin/.local/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 1144, in start_connection
    for level, message in result['messages']:
ValueError: too many values to unpack (expected 2)
fatal: [11.22.33.44]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```

Host files:

```
[fortimanager]
11.22.33.44 ansible_host=11.22.33.44

[fmgr_api:children]

[all:vars]
ansible_network_os=fortimanager
ansible_user=admin
ansible password= password
ansible_httpapi_use_ssl=true
ansible_httpapi_validate_certs=false
ansible_httpapi_timeout=300

```
the playbook is

```
- hosts: fortimanager
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Routing table configuration.
     fmgr_system_route:
        bypass_validation: False
        state: present
        system_route:
           device: port1
           dst: '222.222.22.0/24'
           gateway: 222.222.222.1
           seq_num: 1

```
Any idea becuase i am stucking ...

**Comment by JieX19** [comment]
hi @trump4coin 

It's something related to the environment. You probably need to reinstall fortimanger collection on your device.

I'd like to show my configurations:

Hosts file:

[fortimanagers]
fortimanager01 ansible_host=192.168.2.12 ansible_user=admin ansible_password=123

[fortimanagers:vars]
ansible_network_os=fortinet.fortimanager.fortimanager

```
- hosts: fortimanager01
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
  - name: Routing table configuration.
    fmgr_system_route:
        bypass_validation: False
        state: present
        system_route:
           device: port2
           dst: '222.222.22.0/24'
           gateway: 222.222.222.1
           seq_num: 1
```

Did you try other modules? Are there any errors when using other modules?

BTW, it's an issue regarding fortimanager, I will move it to fortimanger branch.
