### ISSUE TITLE
fortios_monitor_fact system_interface not returning vlan and aggregate interfaces

### ISSUE THREAD

**Issue by kaon1** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#170]
```
 tasks:
    - fortinet.fortios.fortios_monitor_fact:
        vdom: "root"
        selector: 'system_interface'
        params:
          scope: global
          include_vlan: Yes
          include_aggregate: Yes
      register: fortios_facts
```

The above task only returns the physical interfaces and does not return the VLAN or Aggregate interfaces. 

I'm running this on a `FortiGate 200E v6.2.9 build1234 (GA`

`ansible-playbook 2.9.5`
`python version = 3.6.8`
