### ISSUE TITLE
Issue on setting TACACS Server

### ISSUE THREAD

**Issue by apellini** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#18]
On this task of a playbook:

`
- name: Configure TACACS Server

  fortinet.fortios.fortios_user_tacacsplus:
    host: '{{ ansible_host }}'
    username: '{{ fgt.user }}'
    password: '{{ ansible_password }}'
    ssl_verify: '{{ fgt.ssl_verify }}'
    https: '{{ fgt.https }}'
    user_tacacsplus:
      name: '{{ item.name }}'
      server: '{{ item.ip }}'
      key: '{{ item.key }}'
  loop: '{{ tacacs }}'
`

with following var:

`tacacs:
  - name: 'TACACS1'
    ip: 'A.B.C.D'
    key: 'TEST'
  - name: 'TACACS2'
    ip: 'A.B.C.E'
    key: 'TEST'`

Using this module I receive following error:

`, "module_stderr": "No handlers could be found for logger \"fortiosapi\"\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-29434cU0Yv3/ansible-tmp-1592042001.96-29645-5032706405044/AnsiballZ_fortios_user_tacacsplus.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-29434cU0Yv3/ansible-tmp-1592042001.96-29645-5032706405044/AnsiballZ_fortios_user_tacacsplus.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-29434cU0Yv3/ansible-tmp-1592042001.96-29645-5032706405044/AnsiballZ_fortios_user_tacacsplus.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_user_tacacsplus', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_fortinet.fortios.fortios_user_tacacsplus_payload_gmFvoF/ansible_fortinet.fortios.fortios_user_tacacsplus_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_user_tacacsplus.py\", line 412, in <module>\n  File \"/tmp/ansible_fortinet.fortios.fortios_user_tacacsplus_payload_gmFvoF/ansible_fortinet.fortios.fortios_user_tacacsplus_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_user_tacacsplus.py\", line 402, in main\n  File \"/tmp/ansible_fortinet.fortios.fortios_user_tacacsplus_payload_gmFvoF/ansible_fortinet.fortios.fortios_user_tacacsplus_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_user_tacacsplus.py\", line 333, in fortios_user\n  File \"/tmp/ansible_fortinet.fortios.fortios_user_tacacsplus_payload_gmFvoF/ansible_fortinet.fortios.fortios_user_tacacsplus_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_user_tacacsplus.py\", line 324, in is_successful_status\nTypeError: 'NoneType' object has no attribute '__getitem__'\n"`

On group_var I have defined:

`
fgt:
  ssl_verify: False
  https: False
  user: 'xxxxx'

ansible_connection: httpapi
ansible_network_os: fortinet.fortios.fortios
`

For using with a trial fortinet api with only http.

Other modules as example 'fortinet.fortios.fortios_log_syslogd_setting' are working properly.

My env is based on:

Ansible: 2.9.9
Python: 2.7.5
Fortinet Ansible Collections: 1.0.9

I have tried to do the configuration manually and it works properly so seems something on this module.

Regards,

apellini

**Comment by chillancezen** [comment]
hi @apellini 

you missed a keyword `state` in your playbook:

```

- name: Configure TACACS Server

  fortinet.fortios.fortios_user_tacacsplus:
    host: '{{ ansible_host }}'
    username: '{{ fgt.user }}'
    password: '{{ ansible_password }}'
    ssl_verify: '{{ fgt.ssl_verify }}'
    https: '{{ fgt.https }}'
    state: 'present' #<================================== here
    user_tacacsplus:
      name: '{{ item.name }}'
      server: '{{ item.ip }}'
      key: '{{ item.key }}'
  loop: '{{ tacacs }}'
```


thanks,
Link
