### ISSUE TITLE
Creating a firewall rule with multiple services

### ISSUE THREAD

**Issue by cardosocristian** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#182]
I am trying to create a firewall policy with more than one service released in the same rule, but I have not been successful, I even tried with With_items to see if a loop occurred and inserted several unsuccessful services.

```
- collections:
  - fortinet.fortios
  connection: httpapi
  hosts: 2600f
  vars:
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    vdom: root
  tasks:
  - name: Configurando regra de firewall teste
    with_items:
      - HTTP
      - HTTPS
    fortios_firewall_policy:
      vdom: interna
      state: present
      firewall_policy:
        srcintf:
          -
            name: "vlan2853"
        srcaddr:
          -
            name: "253-v4"
        dstintf:
          -
            name: "vlan2729"
        dstaddr:
          -
            name: "REDE30-v4"
        schedule: "always"
        service:
          -
            name: "{{ item }}"
        action: "accept"
        nat: "disable"
        status: "enable"
        policyid: "55"
        name: "REDE-v4-253-OUT-13"
```

When I try to use with_items, with HTTP and HTTPS, it only inserts HTTPS, which is the last value of the loop.

Trying to insert like this:

```
Service:
      - name: ' "HTTP" "HTTPS" '
```

I activated the click debug mode in Fortinet to evaluate the insertion of the rule in this way and occurred this way:

```config firewall policy
edit 55
set uuid 1b61f0f2-ccad-51ec-515d-4cb5c7f26ea9
set name FARM-v4-253-OUT-13
set srcintf vlan2853
set dstintf vlan2729
set srcaddr 253-v4
set dstaddr REDE30-v4
unset srcaddr6
unset dstaddr6
unset src-vendor-mac
set action accept
set schedule always
abort

[cmf_restore_err_redir:3281] restoring stdout/stderr. redir_fd: 12, save_fd1: 13, save_fd2: 14
[cmf_restore_err_redir:3281] restoring stdout/stderr. redir_fd: 17, save_fd1: 18, save_fd2: 19
```

Is there any way to insert more than one service via playbook?

**Comment by JieX19** [comment]
@cardosocristian 

May I know what Fortios collection you used for the above task? We've fixed the issue for a long period. Can you please install **ansible-galaxy collection install fortinet.fortios:2.1.4**  and try it again?

**Comment by cardosocristian** [comment]
Hi @JieX19, I used the ansible-galaxy collection install fortinet.fortios:1.1.7 version because the latest version generates warnings on execution and in an internet article, a Fortinet employee in a Linkedin article suggested using the specific version for FortiOS 6.4.0 as I am using version 6.4.8

**Comment by JieX19** [comment]
@cardosocristian  What do you mean the latest version has warnings? I just installed it and nothing happened. Also, FortiOS has upgraded to 7.0, which has more features and improvements.

Here's an example for this module:
```
- hosts: fortigates
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: config firewall policy
    fortios_firewall_policy:
      state: present
      vdom: root
      enable_log: True
      access_token: "{{ access_token }}"
      firewall_policy:
        policyid: 6
        srcaddr: 
         - name: all
        dstaddr: 
         - name: gmail.com
        srcintf: 
         - name: port3
        dstintf: 
         - name: port8
        service: 
          - name: HTTP
          - name: HTTPS
        action: accept
        schedule: always
        nat: enable
        ssl_ssh_profile: certificate-inspection
        dnsfilter_profile: terr-test-rdmstr
        utm_status: enable
```
In the above example, you can simply apply all the services at once.

**Comment by JieX19** [comment]
@cardosocristian Since Ansible Fortios Collection 2.0.0, we've had many improvements on the modules and supported more FOS versions. So I would suggest upgrading both FortiOS and Collection versions.

For your question, you have to install the latest version of FortiOS Collection. 

Using command:  **ansible-galaxy collection install fortinet.fortios:2.1.4**

**Comment by JieX19** [comment]
@cardosocristian Please take a look at the documentation page https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.1.5/version.html, you will see the major changes from 2.0.0.

You don't have to use a specific collection version, you can use the command **ansible-galaxy collection install fortinet.fortios** and it will pick the latest version of the collection for you.

**Comment by cardosocristian** [comment]
@JieX19 I installed version 2.1.4 just like you mentioned, I didn't receive any more warnings, but when running the playbook according to your example, in the case of multiple services

```
service:
     - name: HTTP
     - name: HTTPS
```

Using your example, I was able to run the playbook successfully.

I had assembled the playbook based on what is in this URL from the ansible website: https://docs.ansible.com/ansible/latest/collections/fortinet/fortios/fortios_firewall_policy_module.html#ansible-collections-fortinet-fortios-fortios- firewall-policy-module

In the website documentation there is a space line between the dash and the name

See a small snippet of code

```
  service:
         -
            name: "default_name_141 (source firewall.service.custom.name firewall.service.group.name)"
        service_negate: "enable"
        session_ttl: "143"
        sgt:
         -
            id:  "145"
```

As it was on the Ansible site, this way I did

```
service:
     -
        name: HTTP
        name: HTTPS
```

with that he ended up always identifying with one.

I don't know if it was a mistake by the docs on the Ansible site to put the code there, but as there is unusual spacing in the documentation, I thought it was the default as it was.

Thank you for your help.
