### ISSUE TITLE
fortios_monitor_fact for backup is not working with 

### ISSUE THREAD

**Issue by ginigangadharan** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#186]
As per the document, to backup the FOS system, use module `fortios_monitor_fact` and its `selector: system_config_backup`. But the `system_config_backup` option is not available in the module !

Any idea? 

Thanks in advance.

**Variables**

```shell
[fortios:vars]
ansible_user=admin
ansible_ssh_pass='Admin#123'
ansible_host_key_checking=false
ansible_network_os=fortinet.fortios.fortios
ansible_connection=ansible.netcommon.httpapi
ansible_httpapi_use_ssl=True
ansible_httpapi_validate_certs=False
```

**Task**

```yaml
    - name: Backup global settings
      fortinet.fortios.fortios_monitor_fact:
        selector: 'system_config_backup'
        vdom: 'root'
        params:
            scope: 'global'
```

**Error**

```shell
TASK [Backup global settings] **********************************************************************************
fatal: [fg01]: FAILED! => {"changed": false, "msg": "value of selector must be one of: firewall_acl6, firewall_ippool, webfilter_malicious-urls, fortiguard_redirect-portal, firewall_policy-lookup, system_acquired-dns, wifi_interfering_ap, system_botnet-domains, firewall_address-dynamic, vpn_ocvpn_status, wifi_vlan-probe, system_sandbox_status, system_running-processes, system_storage, router_ipv4, log_historic-daily-remote-logs, webfilter_malicious-urls_stat, ips_anomaly, wanopt_peer_stats, wifi_network_status, log_hourly-disk-usage, wifi_region-image, system_object_usage, wifi_euclid, system_current-admins, system_sandbox_test-connect, system_interface_speed-test-status, user_info_query, firewall_central-snat-map, wifi_rogue_ap, system_config-revision_info, ips_hold-signatures, utm_antivirus_stats, system_3g-modem, endpoint-control_installer_download, network_arp, firewall_address-fqdns, wifi_firmware, user_fsso, switch-controller_managed-switch_port-stats, endpoint-control_installer, utm_app-lookup, system_firmware, system_interface_dhcp-status, user_banned_check, system_botnet-domains_stat, wifi_matched-devices, system_external-resource_entry-list, webfilter_fortiguard-categories, system_fortimanager_backup-details, firewall_internet-service-match, router_policy6, virtual-wan_sla-log, system_security-rating, switch-controller_managed-switch_dhcp-snooping, system_time, log_local-report-list, vpn-certificate_cert-name-available, firewall_shaper, system_available-interfaces, system_fortimanager_status, system_sensor-info, system_status, firewall_gtp, nsx_instance, web-ui_custom-language_download, wanopt_history, log_forticloud, system_vdom-link, utm_blacklisted-certificates, webcache_stats, system_config-revision_file, user_device, system_dhcp, router_lookup, system_ipam_status, utm_blacklisted-certificates_statistics, log_device_state, vpn_one-click_status, system_sniffer, system_firmware_upgrade-paths, router_ospf_neighbors, system_sandbox_stats, wanopt_webcache, network_lldp_neighbors, log_local-report_download, system_config-error-log_download, firewall_load-balance, vpn_ocvpn_meta, system_sandbox_cloud-regions, firewall_address-fqdns6, firewall_proxy_sessions, firewall_acl, system_link-monitor, system_com-log_download, user_device_query, fortiguard_service-communication-stats, switch-controller_managed-switch_status, system_available-certificates, registration_forticloud_domains, switch-controller_fsw-firmware, system_ha-table-checksums, fortiview_statistics, router_ipv6, endpoint-control_registration_summary, firewall_gtp-runtime-statistics, firewall_uuid-list, router_statistics, system_config_usb-filelist, firewall_internet-service-details, firewall_internet-service-reputation, endpoint-control_ems_cert-status, system_config-script, user_banned, system_sdn-connector_nsx-security-tags, system_object-tagging_usage, system_com-log_update, system_global-resources, system_ipconf, switch-controller_mclag-icl_eligible-peer, user_fortitoken-cloud_status, firewall_per-ip-shaper, wifi_network_list, ips_exceed-scan-range, log_current-disk-usage, license_status, firewall_session, firewall_ippool_mapping, virtual-wan_members, switch-controller_managed-switch_faceplate-xml, firewall_security-policy, wifi_client, endpoint-control_record-list, videofilter_fortiguard-categories, webfilter_category-quota, log_forticloud-report-list, log_policy-archive_download, wifi_ap-names, system_debug_download, system_automation-action_stats, log_fortianalyzer-queue, network_ddns_servers, system_nat46-ippools, system_vdom-resource, system_modem, firewall_proxy-policy, nsx_service_status, azure_application-list, log_forticloud-report_download, user_info_thumbnail, system_sdn-connector_status, vpn_ipsec, endpoint-control_ems_status-summary, firewall_dnat, firewall_multicast-policy, switch-controller_validate-switch-prefix, system_security-rating_history, system_lte-modem_status, fortiview_sandbox-file-details, endpoint-control_summary, system_csf, license_forticare-resellers, switch-controller_managed-switch_models, endpoint-control_profile_xml, wifi_ap_status, user_device-category, system_ntp_status, firewall_gtp-statistics, utm_application-categories, router_lookup-policy, system_performance_status, system_ha-history, license_forticare-org-list, system_security-rating_lang, system_global-search, router_bgp_paths6, vpn_one-click_members, system_interface_kernel-interfaces, switch-controller_managed-switch_health, system_timezone, firewall_sdn-connector-filters, router_bgp_paths-statistics, webfilter_trusted-urls, system_usb-log, network_lldp_ports, system_fortiguard-blacklist, firewall_policy, system_ha-statistics, switch-controller_matched-devices, system_crash-log_download, network_dns_latency, system_fortimanager_backup-summary, firewall_shaper_multi-class-shaper, system_sniffer_download, user_detected-device, system_botnet_stat, system_vm-information, system_security-rating_supported-reports, user_fortitoken, system_botnet, user_info_thumbnail-file, vpn_ssl_stats, system_ha-checksums, webfilter_override, log_stats, system_csf_pending-authorizations, system_resolve-fqdn, log_fortianalyzer, log_ips-archive_download, wifi_meta, system_interface-connected-admins-info, system_config-revision, router_bgp_neighbors, user_collected-email, ips_rate-based, switch-controller_detected-device, webproxy_pacfile_download, registration_forticloud_device-status, firewall_policy6, endpoint-control_ems_status, system_acme-certificate-status, router_policy, switch-controller_managed-switch_transceivers, fortiview_proxy-statistics, user_firewall, firewall_multicast-policy6, user_device-type, switch-controller_managed-switch_cable-status, system_automation-stitch_stats, system_traffic-history_interface, network_ddns_lookup, wifi_managed_ap, system_interface_transceivers, system_traffic-history_top-applications, firewall_uuid-type-lookup, virtual-wan_interface-log, network_reverse-ip-lookup, firewall_health, router_bgp_neighbors6, wifi_unassociated-devices, system_security-rating_status, registration_forticloud_disclaimer, wifi_ap_channels, system_botnet-domains_hits, system_ipam_list, log_event, system_config-sync_status, network_fortiguard_live-services-latency, fortiview_sandbox-file-list, system_fortiguard_server-info, vpn_ssl, system_check-port-availability, log_av-archive_download, license_fortianalyzer-status, virtual-wan_health-check, firewall_address6-dynamic, system_config_restore-status, router_bgp_paths, endpoint-control_avatar_download, system_resource_usage, system_certificate_download, system_ha-peer, system_sandbox_connection, log_forticloud_connection, system_interface_poe, ips_metadata, system_interface, extender-controller_extender, firewall_local-in, wifi_spectrum, firewall_consolidated-policy, switch-controller_managed-switch, system_trusted-cert-authorities, vpn_ocvpn_members, got: system_config_backup"}
```

**Environment**

```shell
$  ansible-galaxy collection list |grep forti
fortinet.fortios       2.1.6  

$  ansible --version |head -1
ansible [core 2.11.12] 
```

**Comment by JieX19** [comment]
Hi @ginigangadharan,

The backup API has been moved to 'fortios_monitor' since 2.1.6 due to the backend API changes. 

Below is an example to backup the FOS system:

```
- hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Backup a virtual domain.
    fortios_monitor:
     access_token: "{{ access_token }}"
     selector: 'backup.system.config'
     vdom: 'root'
     params:
         scope: 'vdom'    -------------> use 'global' if you wanna back up the whole system.
    register: backupinfo

  - name: Save the backup information.
    copy:
     content: '{{ backupinfo.meta.raw }}'
     dest: './local.backup'
```

Let me know if you have any questions.

**Comment by JieX19** [comment]
@ginigangadharan FYI, this is the doc for 2.1.6 https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.1.6/fortios_monitor.html

**Comment by ginigangadharan** [comment]
@JieX19 
Thank you. I did not notice that. 

between, do we have an option to backup to a TFTP location?
(like the command `execute backup config tftp {{ backup_filename }} {{  tftp_server }}`)

**Comment by JieX19** [comment]
@ginigangadharan REST API has not supported TFTP currently. I will tag it in 'feature request category'. We review the list regularly with the API team to decide on prioritization.

**Comment by JieX19** [comment]
@markwell-ch  We've made some improvements for both the new firmware and Ansible modules. Can you please upgrade the FOS version to 7.0.2 or above?

The issue is caused by the incompatible interface of firmware and RESTAPI. If you wanna back up with 6.4.9, you need to install the ansible collection of 2.1.4, and the module's name also changes.

```
- hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Backup a virtual domain.
    fortios_monitor_fact:   ----------> module's name is different
     selector: 'system_config_backup'    ----------> selector's name is different
     vdom: 'root'
     params:
         scope: 'vdom'  -----------> use 'global' if you wanna back up the whole system.
    register: backupinfo

  - name: Save the backup information.
    copy:
     content: '{{ backupinfo.meta.raw }}'
     dest: './local.backup'
```
