### ISSUE TITLE
Module fortios_router_route_map fails in collection version >2.1.5

### ISSUE THREAD

**Issue by markwell-ch** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#189]
Hi,

When running the following task using collection version 2.1.6 against a Fortigate-VM with FortiOS 7.2.0 the task completes. But the route-map contains an empty rule. This also applies to other rule options and also when multiple rules are defined.
Using version 2.1.5. of fortinet.fortios everything works as expected.

Ansible Task:

```
  - name: add route map
    fortinet.fortios.fortios_router_route_map:
      vdom: '{{ vdom }}'
      access_token: '{{ fortios_access_token }}'
      state: present
      router_route_map:
        name: TEST_IN
        comments: ''
        rule:
          - action: permit
            set_local_preference: 300
```

expected configuration:
```
config router route-map
    edit "TEST_IN"
        config rule
            edit 1
                set set-local-preference 300
            next
        end
    next
end
```

actual configuration:
```
config router route-map
    edit "TEST_IN"
        config rule
            edit 1
            next
        end
    next
end
```
