### ISSUE TITLE
system_global/edit_vdom_prompt is wrongly stated as unsupported since FortiOS v6.4.4

### ISSUE THREAD

**Issue by patrikspiess** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#194]
When trying to set  edit-vdom-prompt in global configuration the task tells me it's not supported anymore sice FortiOS 6.4.4 which is wrong.

```
tasks:
    - name: set global configuration
      fortios_system_global:
        vdom: "{{ vdom }}"
        access_token: "{{ api_token }}"
        system_global:
          edit_vdom_prompt: "enable"
```

This tasks outputs the following warning when played with -v:

```
"version_check_warning": {
        "matched": false,
        "mismatches": [
            "option edit_vdom_prompt(enable) not supported since v6.4.4"
       ],
       "system_version": "v7.0.6"
    }
```

If I check all the CLI guides on docs.fortinet.com I see that all FortiOS versions from 6.4.4 an later still support this setting. I proved it with FortiOS v6.4.5, v6.4.9, v7.0.2, v7.0.3 and v7.0.6.

This warning should be removed.
