### ISSUE TITLE
module fortios_system_zone: issue with member_path

### ISSUE THREAD

**Issue by Batman781** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#195]
We're having issue with fortios_system_zone and member_path.
Ansible version: 2.1.5

```
 - name: add ipsec to Zone TEST_ZONE
    fortios_system_zone:
      vdom:  "{{ vdom }}"
      state: "present"
      member_state: "present"
      member_path: interface:interface_name
      system_zone:
        interface:
          - interface_name: "port10"
        name: "TEST_ZONE"
```
```
fatal: [fortivmtest]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": null,
            "member_path": "interface:interface_name",
            "member_state": "present",
            "state": "present",
            "system_zone": {
                "description": null,
                "interface": [
                    {
                        "interface_name": "port10"
                    }
                ],
                "intrazone": null,
                "name": "TEST_ZONE",
                "tagging": null
            },
            "vdom": "root"
        }
    },
    "meta": [
        {
            "build": 1157,
            "http_method": "POST",
            "http_status": 404,
            "mkey": "TEST_ZONE",
            "name": "zone",
            "object_path": "/system/zone/TEST_ZONE/interface/port10",
            "path": "system",
            "serial": "SERIAL",
            "status": "error",
            "vdom": "root",
            "version": "v7.2.0"
        }
    ]
```

**Comment by JieX19** [comment]
Hi @Batman781 

The member_path for the module is tagging:name, here's the doc for this module https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_system_zone.html

**Comment by Batman781** [comment]
Sorry but seems don't work, could you provide an example to clarify?
I want to add port10 to already present zone named "TEST_ZONE"
```
 - name: add ipsec to Zone TEST_ZONE
    fortios_system_zone:
      vdom:  "{{ vdom }}"
      state: "present"
      member_state: "present"
      member_path: tagging:name
      system_zone:
        interface:
          - interface_name: "port10"
        name: "TEST_ZONE"
```
i got this error with tagging:name

    **"msg": "parameter system_zone.tagging is empty"**

and i don't know how to set tagging

**Comment by JieX19** [comment]
@Batman781 

You can just add the interface_name to the interface list. But be careful, the entire interface list will be overwrotten. 

```
tasks:
  - name: add ipsec to Zone TEST_ZONE
    fortios_system_zone:
      vdom:  "{{ vdom }}"
      state: "present"    ---------------->  It will update the system_zone object if there're already some interfaces in the zone.
      system_zone:
        interface:
          - interface_name: port10         
          - interface_name: port9
          - interface_name: port8
        name: "TEST_ZONE"
```

I checked the member operation feature, it only supports adding one or more members to a list if the list has a mkey. The backend does not support it either, if you configure the system zone by adding new interfaces on CLI, it will overwrite the existing interfaces as well. 

Here's a workaround, using Ansible set_fact module, you can add/delete an interface from the 'demo_input' param.
https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-use-the-set-fact-module-in-a-task

**Comment by MaxxLiu22** [comment]
HI,

I have just tested the member operation on fortios_system_zone with Ansible FOS 2.4.0, and it works as expected. I will proceed to close this case. If you have any further questions, please feel free to reopen it or create a new case.
```
  - fortios_system_zone:
      vdom:  "{{ vdom }}"
      state: "present"
      member_state: "present"
      member_path: interface:interface_name
      system_zone:
        interface:
          - interface_name: "port4"
        name: "TEST_ZONE"
```

Thanks,
Maxx
