### ISSUE TITLE
system_global\edit vdom_mode does not work

### ISSUE THREAD

**Issue by oswinfox** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#198]
Hello all, 

I tried on a fotigate F100 (FortiOS 6.4.9) to enable the multi-vdom as follow in my playbook: 

```
   - name: Configure global attributes.
     fortios_system_global:
        vdom:  "{{ vdom }}"
        access_token: "EXAMPLE"
        system_global:
            vdom_mode: "multi-vdom"
````

But I got this error from Ansible: 

`"Unsupported parameters for (fortios_system_global) module: system_global.vdom_mode. Supported parameters include: system_global, vdom, access_token."`

It seems like this option is not working anymore, can someone help me please? 

Kind regards
