### ISSUE TITLE
fortios_system_admin "403 Forbidden" on PUT and password change problem

### ISSUE THREAD

**Issue by diLLec** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#20]
The fortios_system_admin does not work correctly on local users, AFTER the user has been created. 
Fields like `password` or `trusthost1` can't be set after the user has been created while fields like `ip6_trusthost1` can be set. 

Setting a "bad" field causes the fortigate to respond with 
```
meta:
    build: 1112
    error: -5
    http_method: POST
    http_status: 500
    name: admin
    path: system
    revision: d9dc8f06fa8927ed36c3c9d16587ee9f
    revision_changed: false
    serial: FGT
    status: error
    vdom: global
    version: v6.2.4
```

Further, if a password is specified the fortigate issues a `403 Forbidden` which leads to 
an exception:

```
      File "/tmp/ansible_fortios_system_admin_payload_8tor90d0/ansible_fortios_system_admin_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 182, in set
      File "/tmp/ansible_fortios_system_admin_payload_8tor90d0/ansible_fortios_system_admin_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py", line 214, in formatresponse
    IndexError: list index out of range
```

From what I can see the problem does not occur on `remote_auth: "enable"` users.

**Comment by chillancezen** [comment]
ETA: 6/18/2020

**Comment by chillancezen** [comment]
hi @diLLec,

- #### `password` issue.
changing password via Ansible(cmdb) is not supported, we must use CLI or monitor APIs instead. 
```
[httpsd 190 - 1592532203    error] _api_cmdb_v2_config[1204] -- Modification of the 'password' field of system.admin is forbidden.
[httpsd 190 - 1592532203    error] api_return_http_result[645] -- API error 403 raised
```

- #### `trusthost1 ` issue. 
the target must be a masked network.
```
- hosts: fortigate01
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Configure system admin.
    fortios_system_admin:
      vdom:  "{{ vdom }}"
      state: "present"
      system_admin:
         name: 'admin'
         trusthost1: '130.140.25.23/32'  <======watch out .
```

thanks,
Link.
