### ISSUE TITLE
"couldn't resolve module/action 'fortios_configuration_fact'

### ISSUE THREAD

**Issue by ebenitezj** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#200]
Hi all,

When I run AWX:

FAILED! => {"reason": "couldn't resolve module/action 'fortios_configuration_fact'. This often indicates a misspelling, missing collection, or incorrect module path.

My Fortigate have 6.4.5 version and galaxy collection is 2.1.5

In AWX I have a Template that calls comms/backup_config_prueba.yml
![image](https://user-images.githubusercontent.com/78102239/190356374-8c2cc54a-bf61-42bf-b5fb-7852fc4ca6a0.png)

**backup_config_prueba.yaml:**
---
- name: Extracción de configuración
  hosts: "{{inventario}}"
  gather_facts: "{{gather_facts_local}}"
  connection: httpapi
  collections:
    - fortinet.fortios

  roles:
    - role: backup_config

role **backup_config**
--- 
- name: get all configuration
  fortios_configuration_fact:
    selector: system_global
    vdom: global 
  register: system_info

I dont know why my playbook doesn't work

**Comment by MaxxLiu22** [comment]
Hi @ebenitezj ,

Thank you for raising this issue. From the error msg, there would be some inappropriate format around. From the configuration you provide, there would be an extra space before the arguments 'selector' and 'vdom', since they are sub-arguments of fortios_configuraton_fact,
```
- hosts: fortigates
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    vdom: "root"
  tasks:
  - name: Extracción de configuración
    fortios_configuration_fact:
      access_token: "token"
      enable_log: "yes"
      vdom: "global"
      selector: 'system_global'
```
if that not fix the problem, you can try to upgrade fortinet.fortios to latest version by run ``ansible-galaxy collection install fortinet.fortios:2.1.7``

Thanks,
Maxx
