### ISSUE TITLE
Add "append" option to the 'fortios_firewall_addrgrp' module

### ISSUE THREAD

**Issue by unbreakabl3** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#206]
Hello, dear developers.

There is an option called "append" exists now in FortiOS 6.4.x at least. Is it possible to add this to the fortios_firewall_addrgrp module?

![image](https://user-images.githubusercontent.com/13556249/195579049-be383e37-4096-4e5b-98b3-1058b01816fa.png)

Thank you very much in advance.

**Comment by Nenq** [comment]
bump, definitely missing this feature...

**Comment by Nenq** [comment]
A workaround can be made like this:

1. Create a list
```
    - name: loop through hosts and add to fact
      set_fact:
        result: "{{ result + [{'name': item}] }}"
      with_inventory_hostnames:
        - all
```
2. Add that fact to the member function
```
    - name: Configure IPv4 address groups.
      fortios_firewall_addrgrp:
        state: present
        access_token: "{{ fortios_access_token }}"
        firewall_addrgrp:
          member: "{{ result }}"
          name: servers
```

**Comment by MaxxLiu22** [comment]
Hi all,

Yes, you can use the member operation to append a member in this way. I will go ahead and close this case. You're welcome to reopen it if the issue persists or if you have any further questions.
```
  tasks:
  - fortios_firewall_addrgrp:
      firewall_addrgrp:
        member:
          - name: login.windows.net
        name: G Suite
      state: present
      vdom: root
      member_state: present
      member_path: member:name
    name: append to addrgrp
```
Thanks,
Maxx
