### ISSUE TITLE
fortios_configuration_fact: urlencode filters

### ISSUE THREAD

**Issue by jplitza** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#208]
The following task invocation:
```yaml
- fortinet.fortios.fortios_configuration_fact:
    selector: firewall_policy
    vdom: root
    filters:
      - 'dstintf==VLAN 10'
```
yields this error (boiled down):
```
ansible.module_utils.connection.ConnectionError: URL can't contain control characters. '/api/v2/cmdb/firewall/policy?vdom=root&filter=dstintf==VLAN 10' (found at least ' ')
```
Manually putting in `%20` instead of the space works, but that should probably be handled by the module (not least due to security concerns).
