### ISSUE TITLE
Any way to append the address in address group

### ISSUE THREAD

**Issue by foxpatil** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#213]
I had successful playbook which creates address group and add one address object into that group, but i want to append the object in address list under same address group

**Comment by MaxxLiu22** [comment]
Hi @foxpatil ,

We can use member operation to append objects into an existing item, we need to set member_path to the location where you want to append an object and set member_state to present, here I append a member "SSLVPN_TUNNEL_ADDR1" to a existing address group "test", you are free to use it, if you still have questions please let me know.
```
- hosts: fortigates
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
    vdom: root
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  tasks:
  - name: Configure IPv4 address groups.
    fortios_firewall_addrgrp:
      vdom: root
      state: present
      member_path: member:name
      member_state: present
      access_token: "j41kmh4Nrshg40f5GNmwnznpc3QfGr"
      firewall_addrgrp:
        member:
        - name: SSLVPN_TUNNEL_ADDR1
        name: test
```
Thanks,
Maxx
