### ISSUE TITLE
Quetion with ipv4 policies

### ISSUE THREAD

**Issue by PVD619** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#218]
Hello everyone:
Is it  possible to add two or more object networks as a src or service in fmgr_pkg_firewall_policy.yml

**Comment by MaxxLiu22** [comment]
Hi @PVD619 ,

Thank you for raising this issue, this is related ansible FMG, but I can still reproduce this issue on my side, and have reported it to the development team. I will let you know once there is a fix update.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @PVD619 ,

This issue caused by API schema change, we suggest to set ``bypass_validation: True`` as a temporary solution, following code is for your reference, please let me know if you still have questions.
```
- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Configure IPv4 policies.
     fmgr_pkg_firewall_policy:
        bypass_validation: True
        adom: root
        pkg: default # package name
        state: present
        pkg_firewall_policy:
           action: accept 
           comments: ansible-comment
           dstaddr: all
           dstintf: any
           name: ansible-test-policy
           nat: disable
           policyid: 9
           schedule: always
           service:  
            - "ALL_ICMP" 
            - "ALL_TCP"
           srcaddr: 
            - "gmail.com"
            - "SSLVPN_TUNNEL_ADDR1"
           srcintf: any
           status: disable
```

Thanks,
Maxx
