### ISSUE TITLE
timeout while run playbook

### ISSUE THREAD

**Issue by shokrymohamedshokry** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#221]
```
- hosts: fortigate03
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
   - name: Configure global attributes.
     fortios_system_global:
        vdom:  "{{ vdom }}"
        access_token: "{{ fortios_access_token }}" #if you prefer access token based authentication, add this line.
        system_global:
           admintimeout: "60"
```
When i trying to run any forti playbook like the previous one i got these error 
i try to run the play with many version of python also with ansible core and ansible navigator but the issue

Error

TASK [get disk event user and memory event user at once.] **********************
Anexception occurred during task execution. To see the full traceback, use -vvv. The error was: See the timeout setting options in the Network Debug and Troubleshooting Guide.
fatal: [fortigate03]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-local-25zdc3i_3m/ansible-tmp-1675683463.5755718-89-261122461764262/AnsiballZ_fortios_log_fact.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-local-25zdc3i_3m/ansible-tmp-1675683463.5755718-89-261122461764262/AnsiballZ_fortios_log_fact.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-local-25zdc3i_3m/ansible-tmp-1675683463.5755718-89-261122461764262/AnsiballZ_fortios_log_fact.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_log_fact', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_log_fact', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_fortios_log_fact_payload_hv1xc81x/ansible_fortios_log_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_log_fact.py\", line 2733, in <module>\n  File \"/tmp/ansible_fortios_log_fact_payload_hv1xc81x/ansible_fortios_log_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_log_fact.py\", line 2697, in main\n  File \"/tmp/ansible_fortios_log_fact_payload_hv1xc81x/ansible_fortios_log_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_log_fact.py\", line 2315, in fortios_log_fact\n  File \"/tmp/ansible_fortios_log_fact_payload_hv1xc81x/ansible_fortios_log_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/module_utils/fortios/fortios.py\", line 526, in log_get\n  File \"/tmp/ansible_fortios_log_fact_payload_hv1xc81x/ansible_fortios_log_fact_payload.zip/ansible/module_utils/connection.py\", line 195, in __rpc__\nansible.module_utils.connection.ConnectionError: command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Thanks for assistance
