### ISSUE TITLE
fortios  "msg": "Error in repo"}

### ISSUE THREAD

**Issue by shokrymohamedshokry** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#222]
When I run any playbook using fortios collection i got this error `( "vdom": "root", "version": "v6.4.11"}, "msg": "Error in repo"}) ` at the end of task and return with failed status.

````

PLAY RECAP *********************************************************************************************************************************************
fortigate03                : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

[shokry@hq-ans-eng forti]$ ansible-navigator run -m stdout nic.yml

PLAY [fortigate04] *********************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************
ok: [fortigate04]

TASK [Display NIC informationn] *********************************************************************************************************************************************
fatal: [fortigate04]: FAILED! => {"changed": false, "meta": {"build": 2030, "http_method": "PUT", "http_status": 403, "name": "nic", 
"path": "********rdware", "serial": "FG4H0ETB20903251", "status": "error", "vdom": "root", "version": "v6.4.11"}, 
"msg": "Error in repo"}

PLAY RECAP *********************************************************************************************************************************************
fortigate04                : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

````

example of the playbook

````
- hosts: fortigate04
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 8443
  tasks:
  - name: Display NIC informationn
    fortios_hardware_nic:
      vdom:  "{{ vdom }}"
      access_token: "{{ Fortitoken }}"
      hardware_nic:
        nic: "ha"

````

fortios version 2.2.2
ansible version [core 2.13.3]
python version  3.9.13
