### ISSUE TITLE
modules/tasks requiring global scope fail for devices in multi-vdom mode

### ISSUE THREAD

**Issue by jgun-at-redhat** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#226]
### Scenario 1: fortios_system_snmp_user module (resolved with config change)
- attempting to create an SNMP user results in "Error in repo" response
- "scope global" not present in gui for fortios 6.x
- requires config from cli similar to following before it will work:
```
config system accprofile
    edit "ansible-profile"
        set scope global
```
- could be resolved with a "setup" or "requirements" section in collection readme?

### Scenario 2: fortios_system_admin module (not yet resolved)
- attempting to create an admin user results in "Error in repo" response, even with "set scope global" present in ansible admin accprofile
```
  - name: Configure admin users - result in error in repo
    fortios_system_admin:
      vdom:  "root"
      state: "present"
      system_admin:
        [SNIP]
```
- tried various permutations of vdom parameters, specifying "vdom: global" results in an error that lists a VDOM that is not referenced in the play, and is neither "root" nor "global" (obfuscated here as "SOMEVDOMNAME")
`"cli_error": "current vf=SOMEVDOMNAME\nentry not found in datasource`
```
  - name: Configure admin users - results in entry not found in datasource
    fortios_system_admin:
      vdom:  "global"
      state: "present"
      system_admin:
        [SNIP]
```

### thoughts
Everything I have written and tested against my "non-vdom" fortigate VM instance seems to work in accordance with the documentation and examples. Some of those same playbooks run against a "multi-vdom" instance deployed from the same source, with an otherwise identical config fail, while others are successful. The common denominator for those things that fail are the tasks where the equivalent CLI command would need to be run in the "config global" context.
