### ISSUE TITLE
Parameter output_path in fortios_export_config_playbook  has no effect

### ISSUE THREAD

**Issue by oelu** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#227]
Hi all, 

the parameter `output_path` in `fortios_export_config_playbook` has no effect, or is not respected. The output is always saved in the current folder. Looks like a bug to me. 

We tested with the following playbook:
```
- name: Export playbooks.
  hosts: fortigates
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    ansible_httpapi_use_ssl: true
    ansible_httpapi_port: 443
    vdom: "root"
  tasks:
    - name: Export multiple palybooks
      fortinet.fortios.fortios_export_config_playbook:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        selectors:
          - selector: firewall_policy
        output_path: "./config"
```
Best regards
Olivier

**Comment by jgun-at-redhat** [comment]
Just to add - this is not environment specific. I've recreated the problem across several ansible/AAP/AWX environments. 

Looking at the python source, the variable storing the output path parameter is just not used anywhere after being validated.

**Comment by MaxxLiu22** [comment]
Hi @oelu @jgun-at-redhat ,

Thank you for raising this issue, I can reproduce this problem and have reported it to the development team. Here is a workaround solution for temporary reference. I will let you know if that is fixed.

```
- name: Export playbooks.
  hosts: fortigates
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    module_name: firewall_policy
    vdom: root
    ansible_httpapi_use_ssl: 'yes'
    ansible_httpapi_validate_certs: 'no'
    ansible_httpapi_port: 443
  tasks:
    - name: Export multiple palybooks
      fortinet.fortios.fortios_export_config_playbook:
        vdom: "root"
        access_token: "3jGnNqbsdfww47btqw1H5rr7d78dcN"
        selectors:
          - selector: "{{ module_name }}"
        output_path : ""
    - name: move file
      shell: mv {{'./' + module_name + '_playbook.yml'}} {{'./config/' + module_name +'_playbook.yml'}}
```

Thanks,
Maxx
