### ISSUE TITLE
Error in Repo

### ISSUE THREAD

**Issue by mattpainter701** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#230]
Backup job, cant figure out why it always shows 'error in repo'

fatal: [FG71F-HA]: FAILED! => {"changed": false, "meta": {"action": "backup", "build": 444, "http_method": "POST", "http_status": 403, "name": "config", "path": "system", "serial": "<serialnumber>", "status": "error", "vdom": "root", "version": "v7.0.9"}, "msg": "Error in repo"}

```
[fortigate]
FG71F-HA ansible_host=192.168.1.1 ansible_user=user ansible_password=password123

[dc_fortigate:vars]
ansible_network_os=fortinet.fortios.fortios
fortios_access_token=sdfdsafdsafdsafasdfsdf

  GNU nano 6.2                                                                                    
- hosts: fortigate
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 8080
   ansible_httpapi_timeout: 60
  tasks:
  - name: Backup a virtual domain.
    fortios_monitor:
     access_token: "{{ fortios_access_token }}"
     selector: 'backup.system.config'
     vdom: 'root'
     params:
        scope: 'global'
    register: backupinfo

  - name: Save the backup information.
    copy:
     content: '{{ backupinfo.meta.raw }}'
     dest: './local.backup'


```
