### ISSUE TITLE
405 Not supported for system_global OS7.2.3

### ISSUE THREAD

**Issue by lewis-green** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#237]
When doing a task with fortios_system_global I get a 405 method not supported. (FortiOS 7.2.3)

```
    - name: Set System Global
      fortios_system_global:
        access_token: "{{ fortinet_access_token }}"
        enable_log: true
        vdom: "{{ vdom }}"
        system_global:
          hostname: 'test'
```

In the log it says POST is not allowed. I took the call and did it in Postman with a PUT and it works. 

It looks like the REST Method is wrong?
