### ISSUE TITLE
Configure second syslog device

### ISSUE THREAD

**Issue by ziyedbe** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#241]
I m trying to configure the second syslog device using fortios_log_syslogd_setting module but i can't find a way to do that and there is no mention to that in the documentation.   
This is my playbook

```YAML
- hosts: fortigates
  gather_facts: False
  collections:
    - fortinet.fortios
  connection: httpapi
  vars_files:
  - ../vars/vars.yml
  tasks:
  - name: Global settings for remote syslog server.
    fortios_log_syslogd_setting:
      vdom:  "global"
      log_syslogd_setting:
        facility: "kernel"
        server: "XX.XX.XX.XX"
        source_ip: "0.0.0.0"
        status: "enable"
```

This is the response, as you can see "log.syslogd" is the only one changed
```JSON
    "meta": {
        "build": XXXX,
        "http_method": "PUT",
        "http_status": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "name": "setting",
        "path": "log.syslogd",
        "revision": "XXX",
        "revision_changed": false,
        "serial": "XXX",
        "status": "success",
        "vdom": "global",
        "version": "XXX"
    }
```
