### ISSUE TITLE
fortios_system_zone cannnot be state absent of member_path

### ISSUE THREAD

**Issue by miyuk** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#247]
# Overview

`fortios_system_zone` cannnot be absent state that already deleted params.

# Environment
ansible: 2.13.3
fortinet.forios collection: 2.2.3
fortigate: 7.2.4

# Reproduction steps

1. Create zone `test` with no interfaces.
```
config system zone
  edit "test"
  next
end
````
2. Run ansible playbook to delete zone interfaces such as `port2`.
```yaml
---
- hosts: fortigate
  gather_facts: false
  collections:
    - fortinet.fortios
  tasks:
    - name: delete zone interface
      fortios_system_zone:
        vdom: root
        state: present
        member_path: interface:interface_name
        member_state: absent
        system_zone:
          name: test
          interface:
            - interface_name: port2
```
3. Raise exception
```
fatal: [fortigate]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": false,
            "member_path": "interface:interface_name",
            "member_state": "absent",
            "state": "present",
            "system_zone": {
                "description": null,
                "interface": [
                    {
                        "interface_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                    }
                ],
                "intrazone": null,
                "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "tagging": null
            },
            "vdom": "root"
        }
    },
    "meta": [
        {
            "build": 1396,
            "child_mkey": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "child_path": "interface",
            "http_method": "DELETE",
            "http_status": 404,
            "mkey": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "name": "zone",
            "object_path": "/system/zone/********/interface/********",
            "path": "system",
            "serial": "**********",
            "status": "error",
            "vdom": "root",
            "version": "v7.2.4"
        }
    ]
}
```
# Expected behavior

No error, and zone interface `port2` is absent (no changed)
