### ISSUE TITLE
Creating API user failed with ansible 

### ISSUE THREAD

**Issue by faizan-syed** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#258]
Hi ,
My ansible playbook is failing when I am trying to create API admin user from the api profile while giving trusthost IP address. It worked fine without ipv4_trusthost but when I defined it as below it failed

```

  - name: Create An API User if not present
    debugger: on_failed
    fortios_system_api_user:
      vdom: "root"
      state: "present"
      system_api_user:
        name: "api_admin"
        accprofile: "api_profile"
        vdom:
          - name: "root"  
        trusthost:
          - 
            id: "112"
            ipv4_trusthost: "10.250.180.0 255.255.255.0"
            type: "ipv4-trusthost"
```

It failed with below error

```
fatal: [d2a-fw-01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": false,
            "member_path": null,
            "member_state": null,
            "state": "present",
            "system_api_user": {
                "accprofile": "api_profile",
                "api_key": null,
                "comments": null,
                "cors_allow_origin": null,
                "name": "api_admin",
                "peer_auth": null,
                "peer_group": null,
                "schedule": null,
                "trusthost": [
                    {
                        "id": 112,
                        "ipv4-trusthost": "10.250.180.0 255.255.255.0",
                        "ipv6-trusthost": null,
                        "type": "ipv4-trusthost"
                    }
                ],
                "vdom": [
                    {
                        "name": "root"
                    }
                ]
            },
            "vdom": "root"
        }
    },
    "meta": {
        "build": 2030,
        "error": -5,
        "cli_error": "current vf=root:0\ncurrent vf=root:0\nTrusthost IP address can not be empty!\nobject check operator error, -651, discard the setting\nCommand fail. Return code -651\nCommand fail. Return code 1\n",
        "http_method": "POST",
        "http_status": 500,
        "name": "api-user",
        "path": "system",
        "revision": "0444168f0027d4cb9354b94d60036821",
        "revision_changed": false,
        "serial": "FGVM02TM22012120",
        "status": "error",
        "vdom": "root",
        "version": "v6.4.11"
    },
    "msg": "Error in repo"
}
[d2a-fw-01] TASK:.firewall : Create An API User if not present (debug)> User interrupted execution

```

@FTNT-HQCM @MaxxLiu22
https://docs.ansible.com/ansible/latest/collections/fortinet/fortios/fortios_system_api_user_module.html

Need help in this ? why in the output  ipv4_trusthost changed to  ipv4-trusthost automatically ???
    - Link Zheng (@chillancezen)
    - Jie Xue (@JieX19)
    - Hongbin Lu (@fgtdev-hblu)
    - Frank Shen (@frankshen01)
    - Miguel Angel Munoz (@mamunozgonzalez)
    - Nicolas Thomas (@thomnico)
