### ISSUE TITLE
Error creating fortios_firewall_policy - "msg": "Error in repo"

### ISSUE THREAD

**Issue by KingJim1984** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#272]
Hello I try to add an simple firewall policy to my fortigate. But the deployment failed

```
---
- name: Configure IPSec VPN on Fortigate
  hosts: fortigate
  gather_facts: no
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 7443
  tasks:
    - name: Configure IPv4/IPv6 policies for Azure.
      fortios_firewall_policy:
        access_token: "{{ fortigate_api_token }}"
        vdom: root #"{{ fortigate_vdom }}"
        state: present #"{{ create_delete }}"
        firewall_policy:
          policyid: 0
          name: "Test"          
          status: "enable"
          srcintf:
           - name: WLAN
          dstintf:
           - name: SD-WAN
          srcaddr: 
           - name: all
          dstaddr:
           - name: all
          service: 
          - name: HTTP
          - name: HTTPS
          action: "accept"
          schedule: "always"
```

Error message in Ansible:
```
TASK [Configure IPv4/IPv6 policies for Azure.] *********************************
fatal: [fortigate]: FAILED! => {"changed": false, "meta": {"build": 1575, "http_method": "PUT", "http_status": 405, "name": "policy", "path": "firewall", "serial": "FGT60F***************", "status": "error", "vdom": "root", "version": "v7.2.6"}, "msg": "Error in repo"}

```

diagnose debug application httpsd -1
```
[httpsd 30476 - 1696585394     info] handle_cli_req_v2[3200] -- no method found for requested action: (null)
[httpsd 30476 - 1696585394     info] handle_cli_req_v2[3318] -- returning to original vdom "root"
[httpsd 30476 - 1696585394  warning] api_return_http_result[1275] -- API error 405 raised
[httpsd 30476 - 1696585394     info] fweb_debug_final[318] -- Completed PUT request for "/api/v2/cmdb/firewall/policy" (HTTP 405)
```
