### ISSUE TITLE
HA settings: hbdev - only first device is set

### ISSUE THREAD

**Issue by raphis** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#276]
I set the following settings in HA:

```
fortinet_ha_settings:
  group_id: 15
  group_name: fw-ws-forti
  password: "{{ vault_fortinet_hagroup_password }}"
  override: enable
  monitor: [agg1, port15]
  hbdev: [ha, port1]
```

This is then given to the ansible collection as follows:
```
- name: Configure HA.
  fortios_system_ha:
    vdom:  "{{ fortinet_default_vdom }}"
    access_token: "{{ fortinet_token }}"
    system_ha: "{{ fortinet_ha_settings }}"
```

**Problem description:**
The array given for "hbdev" is not really set on the device (tested on 7.2). We always end up in the situation that only the first interface is set (in our case ha). For monitoring interfaces it's working properly and all defined interfaces show up in the config.

No error is given when this is configured. Config is accepted and pushed without errors.

**Comment by MaxxLiu22** [comment]
Hi @raphis ,

Thank you for raising this question, I checked this setting through CLI and found "hbdew" needs input another value "priority" after defining interface, once I adjust the script, the config can be fully passed to FGT, let me know if that doesn't work for you.
``` 
FortiGate-VM64 (ha) # set hbdev port1 
<integer>    the priority of the interface, range <0-512>

FortiGate-VM64 (ha) # set hbdev port1 3 port2 5
```
```
  - fortios_system_ha:
      vdom: root
      system_ha:
        hbdev: [port1, 7, port2, 8]
```

Thanks,
Maxx
