### ISSUE TITLE
Can not set Admin SSH keys. "Error in Repo"

### ISSUE THREAD

**Issue by TafkaMax** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#288]
I have the same problem with FortiOS ansible module, as I had with the FortiSwitch one.

https://github.com/fortinet-ansible-dev/ansible-galaxy-fortiswitch-collection/issues/7

**Comment by TafkaMax** [comment]
NVM. It seems to be a problem with changing existing Admin user and 'PUT' command.

https://community.fortinet.com/t5/Support-Forum/Fortigate-API-works-for-everything-but-admin-password-change/td-p/80126

https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/20

**Comment by MaxxLiu22** [comment]
Hi @TafkaMax ,

Thank you for raising this issue, I find this argument is specially handled by API just like ``image content``, ``certificate``, so we had better save the SSH key into a singe file (for example ssh_key.txt) with single quotation marks wrapped like 
```
`ssh-rsa AAAAB3NzaC1yc...yxs91pxVWYTA9A6y67KtksOUIp/k26ihDxECTo2XdJ9WXTUEurYwl49H8= root@maxx'
```
and refer it in your ansible script like
``` 
  tasks:
  - name: Configure admin users.
    fortios_system_admin:
      vdom: root
      state: present
      system_admin:
        accprofile: super_admin
        name: new_admin355
        ssh_public_key1: "{{ lookup( 'file', 'ssh_key.txt') | string  }}"
```
please let me know if that doesn't solve your problem in your FGT and FSW.

Thanks,
Maxx
