### ISSUE TITLE
There must be at least 1 server certificate configured

### ISSUE THREAD

**Issue by arnoldthebat** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#299]
Using fortinet.fortios.fortios_firewall_vip - version 2.3.5

Attempting to add in a VIP of type 'server-load-balance'

Code snippet:

```
- name: Configure Virtual Servers.
      fortinet.fortios.fortios_firewall_vip:
        vdom:  "{{ vdom }}"
        state: "present"
        access_token: "{{ fortigate_access_token }}"
        enable_log: true
        firewall_vip:
          extintf: any
          extip: "{{ fortigate_vip_extip }}"
          extport: "{{ fortigate_vip_extport }}"
          http_ip_header: enable
          http_multiplex: enable
          name: "{{ fortigate_vip_name }}"
          server_type: https
          ldb_method: static
          type: server-load-balance
          ssl_mode: full
          ssl_certificate: 'my_cert'
          monitor:
            - 
              name : 'health check'
          realservers:
            "{{ vip_entries }}"
```

Error:
`There must be at least 1 server certificate configured.\nattribute set operator error, -56, discard the setting\nCommand fail`

Setting the following on the FW 
`diag deb en`
`diag deb cli 8`

On the CLI, the last command we see is `unset ssl-certificate` and then abort with error 56.

For ref, setting the `server_type` to `http` then running the above works. The certificate wont get set of course.

Also see: https://stackoverflow.com/questions/77959671/ansible-fortigate-vip-configuration-with-ssl-certificate for another user experiencing the same issue

Tried 2.3.5 - 2.3.3 versions of the collection with the same output error

Setting the cert manually after changing the type to https, and adding in the certs allows subsequent changes to be made to the VIP. Any cert changes however are ignored.

Note that this fails on FortiOS7.4.3 but works on FortiOS7.2.7 so related to a small change in the payload since in 7.4.3 its changed to an array:

FortiOS7.4.3
```
ssl-certificate : 
0 : 
name : "my_cert"
```

FortiOS7.2.7
```
ssl-certificate : 
q_origin_key : "my_cert"
```
