### ISSUE TITLE
federated-upgrade 7.2.7>7.2.8 problem

### ISSUE THREAD

**Issue by luca-219** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#304]
Hi,

I would use federated-upgrade , but upgrade status are or failed or "upgrade to 7.2.8 shortly" but is a permanent status. 

ansible --version
ansible [core 2.15.9]
ansible-galaxy --version
ansible-galaxy [core 2.15.9]

Is a single fortigate 40F and federated upgrade in gui work fine.
my playbook
`- hosts: fgt_40
  collections:
    - fortinet.fortios
  connection: httpapi
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Coordinate federated upgrades within the Security Fabric.
    fortios_system_federated_upgrade:
      vdom:  "{{ vdom }}"
      #access_token: "mNsw0Nnzrmqt574HHddcQyt3s0Qp7x"
      system_federated_upgrade:
        failure_device: "FGT40FXXXXXXX"
        failure_reason: "none"
        #ha_reboot_controller: "<your_own_value>"
        next_path_index: "0"
        node_list:
         -
            coordinating_fortigate: "FGT40FXXXXXX"
            device_type: "fortigate"
            #maximum_minutes: "15"
            serial: "FGT40FXXXXX"
            #setup_time: "<your_own_value>"
            #time: "16:49 2024/03/18"
            timing: "immediate"
            upgrade_path: "7-2-8"
        status: "disabled"
        upgrade_id: "10"
`
command output
changed: [fgt_40] => {
    "changed": true,
    "diff": {},
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": false,
            "member_path": null,
            "member_state": null,
            "system_federated_upgrade": {
                "failure_device": "FGT40FXXXXXXX",
                "failure_reason": "none",
                "ha_reboot_controller": null,
                "next_path_index": 0,
                "node_list": [
                    {
                        "coordinating_fortigate": "FGT40FXXXXXXX",
                        "device_type": "fortigate",
                        "maximum_minutes": null,
                        "serial": "FGT40FXXXXXX",
                        "setup_time": null,
                        "time": null,
                        "timing": "immediate",
                        "upgrade_path": "7-2-8"
                    }
                ],
                "status": "disabled",
                "upgrade_id": 10
            },
            "vdom": "root"
        }
    },
    "meta": {
        "build": 1577,
        "http_method": "PUT",
        "http_status": 200,
        "name": "federated-upgrade",
        "old_revision": "01fbe5d3199b93757321895fa0046cef",
        "path": "system",
        "revision": "242f20dac03cd425b065d818f5a11a3a",
        "revision_changed": true,
        "serial": "FGTXXXXXX",
        "status": "success",
        "vdom": "root",
        "version": "v7.2.7"
    }
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************************
alta                       : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by JieX19** [comment]
Hi @luca-219 

" but upgrade status are or failed or "upgrade to 7.2.8 shortly" but is a permanent status", just wondering if the module works fine sometimes?

Could you please set enable_log = True to get more info from the log? it's usually saved in /tmp/fortios.ansible.log

**Comment by luca-219** [comment]
Hi JieX19 , no never work , now I haven't fortinet to update and I can't take a log , but the problem is with 
"timing: "immediate""  doesn't work , with schedule work.

**Comment by lnxtxyz** [comment]
Hi

From my experience `timing: "immediate"` doesn't work either.

My solution which works:
```yaml
- name: Do federated upgrade
  fortinet.fortios.fortios_system_federated_upgrade:
    system_federated_upgrade:
# ...
      node_list:
        - serial: "{{ fortigate_serialno }}"
          coordinating_fortigate: "{{ fortigate_serialno }}"
          device_type: "fortigate"
          timing: "scheduled"
          time: "{{ lookup('pipe', 'date -u -d \"now + 5 minute\" \"+%H:%M %Y/%m/%d UTC\"') }}" # ugly
          upgrade_path: "{{ fortigate_federated_upgrade_path }}"
# ...
      status: "initialized"
```
