### ISSUE TITLE
fortios_system_global timezone not working with FortiOS 7.4.2 and higher

### ISSUE THREAD

**Issue by connect-cloud** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#306]
https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/blob/44771120d0868cde6a24f8a280920f9733bbc8a4/plugins/modules/fortios_system_global.py#L1631

From FortiOS 7.4.2 the configuration of the timezone in the global system config is not done with numbers anymore but whith a timezone string e.g. 'Europe/Amsterdam' but the fortios_system_global.py module does not allow this configuration.

My playbook:
```
    - name: Fortigate global config version > 7.4.2
      fortios_system_global:
        system_global:
          timezone: "Europe/Amsterdam"
      when: fortigate_version is version("7.4.2",'>')
```
