### ISSUE TITLE
IPv4 Virtual Wire Pair Policy

### ISSUE THREAD

**Issue by ziyedbe** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#310]
Hello,

I m looking for a way to automate adding IPv4 Virtual Wire Pair Policies using Ansible but i can't find a module to do that.

Thank you !

**Comment by MaxxLiu22** [comment]
Hi @ziyedbe ,

Thank you for your question. IPv4 Virtual Wire Pair Policies are configured similarly to [firewall policies](https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_firewall_policy.html). [Here's how to set up a wire pair policy](https://docs.fortinet.com/document/fortigate/7.4.3/administration-guide/166804/virtual-wire-pair#:~:text=To%20create%20a%20virtual%20wire,traffic%20is%20allowed%20to%20flow.). I hope this information is helpful for you. Please let me know if you have any further questions or if this doesn't address your inquiry.

Thanks,
Maxx

**Comment by ziyedbe** [comment]
Hello @MaxxLiu22 ,
Thank you for your answer, but i m looking for a way to configure IPv4 Virtual Wire Pair Policies using ansible not via the GUI or command lines.

Thank you !

**Comment by MaxxLiu22** [comment]
Hi @ziyedbe ,

Sorry for misunderstanding your question. Here, I've prepared an example to create a VWP and allow traffic in both directions. I hope this is helpful to solve your question. Let me know if this doesn't satisfy your needs.
```
  tasks:
  - name: Configure virtual wire pairs.
    fortios_system_virtual_wire_pair:
      vdom: root
      state: present
      system_virtual_wire_pair:
        member:
        - interface_name: port4
        - interface_name: port5
        name: VWP
  - name: Configure IPv4/IPv6 policies.
    fortios_firewall_policy:
      vdom: root
      state: present
      firewall_policy:
        action: accept
        comments: example
        dstaddr:
        - name: all
        dstintf:
        - name: port4
        - name: port5
        name: VWP_policy
        policyid: '4'
        service:
        - name: ALL
        srcaddr:
        - name: all
        srcintf:
        - name: port4
        - name: port5
        schedule: always
```
Thanks,
Maxx
