### ISSUE TITLE
Feature Request module_defaults group

### ISSUE THREAD

**Issue by AndreiSucu** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#320]
Hello,

I've stumbled upon the need to sometimes use access_token within my tasks.
After doing some research I've found out that I can use the "access_token" parameter with module defaults like this:

```
- hosts: localhost
  gather_facts: false
  tasks:
    - fortinet.fortios.fortios_alertemail_setting
  module_defaults: 
      - fortios_alertemail_setting: 
          access_token:  "{{ api_token }}"
      - fortinet.fortios.fortios_system_sdwan: 
          access_token:  "{{ api_token `}}"`
      - fortinet.fortios.fortios_configuration_fact: 
          access_token:  "{{ api_token }}"
      - fortios_firewall_address: 
          access_token:  "{{ api_token }}"
      - fortios_firewall_addrgrp: 
          access_token:  "{{ api_token }}"
      - fortinet.fortios.fortios_firewall_dos_policy: 
          access_token:  "{{ api_token }}"
      - fortios_firewall_local_in_policy: 
          access_token:  "{{ api_token }}"
      - fortios_firewall_policy: 
          access_token:  "{{ api_token }}"
                   .
                   .
                   .
```

But as you can see, this is really inconvenient, so I would suggest a feature request to create a module defaults group as described here:

[https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_module_defaults.html#module-defaults-groups](url) 

This implementation would consist of defining "fortios" group as "action_groups" in:

`/site-packages/ansible_collections/fortinet/fortios/meta/runtime.yml
`

```
action_groups:
  fortios:
    - fortios_alertemail_setting
    - fortios_antivirus_exempt_list
    - fortios_antivirus_heuristic
    - fortios_antivirus_mms_checksum
    - fortios_antivirus_notification
    - fortios_antivirus_profile
                  .
                  .
                  .
```

So the playbook would look like this:

```
- hosts: localhost
  gather_facts: false
  tasks:
    - fortinet.fortios.fortios_alertemail_setting
  module_defaults:
    group/fortinet.fortios.fortios:
      access_token: "{{ api_token }}"
```

Pull request 'added "fortios" action_group with all fortios modules #321' opened.

Thank you.

**Comment by MaxxLiu22** [comment]
Hi @AndreiSucu ,

Thank you for your valuable suggestion. I have communicated your needs to our development team for further improvement. At present, the Ansible logic allows you to provide the ``access_token`` only in the first task, with no need to provide it for the following tasks in the same playbook. However, your suggestion is still under consideration.
```
  tasks:
  - name: Interface port2
    fortinet.fortios.fortios_system_interface:
      state: "present"
      access_token: "7Qmrjtng910sQzm0bbckfwNy4GQQ9n"
      system_interface:
        name: port2
        status: up
  - name: Interface port3
    fortinet.fortios.fortios_system_interface:
      state: "present"
      system_interface:
        name: port3
        status: down
```

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @fa-elepape,

Thank you for your suggestion. I will consult with the development team to explore the possibility of implementing this feature. Apologies for the inconvenience caused.

Best regards,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @fa-elepape,

This feature was introduced in Ansible FOS 2.4.2. Please feel free to upgrade and try it when it is convenient for you.
```
- collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: false
  hosts: fortigates
  vars:
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
  module_defaults:      # <-------------------------------------------
    group/fortinet.fortios.fortios:
      vdom: "root"
      enable_log: true
  tasks:
    - name: Configure firewall policy
      fortios_firewall_policy: # vdom: root # enable_log: true
        state: "present"
        firewall_policy:
          policyid: 2
          srcaddr:
            - name: all
          dstaddr:
            - name: FABRIC_DEVICE
          srcintf:
            - name: port1
            - name: port2
          dstintf:
            - name: any
          service:
            - name: HTTPS
            - name: HTTP
            - name: SSH
            - name: PING
            - name: SNMP
          action: accept
          schedule: always
          utm_status: enable

    - name: Get hardware status
      fortios_configuration_fact:
        selector: system_vdom

    - name: Get global attributes
      fortios_monitor_fact:
        selectors:
          - selector: license_status
          - selector: system_status
          - selector: firewall_security-policy
          - selector: firewall_load-balance
            params:
              count: 2

    - name: Configure NTP servers
      fortios_system_ntp:
        system_ntp:
          ntpserver:
            - id: 1
              server: 10.0.0.2
            - id: 2
              server: 10.0.0.100
```

Thanks,
Maxx
