### ISSUE TITLE
full backup 

### ISSUE THREAD

**Issue by milad-24** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#336]
I'm using the fortinet.fortios.fortios_monitor_fact module to create a full backup, but the backup differs slightly from the one obtained through the web UI.

here is my task:

```
    - name: Backup global settings
      fortinet.fortios.fortios_monitor_fact:
        selector: 'system_config_backup'
        vdom: 'root'
        params:
            scope: 'global'
```

differences : 
- config system sso-forticloud-admin
- config system admin

How can I create a backup with the complete sso-forticloud-admin and admin sections?

**Comment by MaxxLiu22** [comment]
Hi @milad-24 ,

Thank you for bringing this issue to my attention and for providing the information. After comparing the API of the GUI and Ansible requests, I noticed that Ansible includes an additional vdom=root in the URL. This could be why some configurations are not being downloaded. Even if you remove the vdom argument from the task, Ansible defaults to setting vdom="root". I would suggest trying to set vdom="" in your task to see if that resolves the issue. on my side, It behaviors just like GUI.
```
  tasks:
    - name: Backup global settings
      fortinet.fortios.fortios_monitor_fact:
        enable_log: "true"
        selector: 'system_config_backup'
        vdom: ''
        params:
            scope: 'global'
```
```
Ansible: /api/v2/monitor/system/config/backup?vdom=root&scope=global
GUI: /api/v2/monitor/system/config/backup?destination=file&scope=global
```
Thanks,
Maxx
