### ISSUE TITLE
Question on fortinet.fortios.fortios_export_config_playbook 

### ISSUE THREAD

**Issue by chr00ted** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#342]
I have a good config on a firewall that I would like to push out to similar model firewalls. We are currently uploading a backup config and editing after the config is applied. I saw fortinet.fortios.fortios_export_config_playbook , is there a way for it to create plays for all selectors? I tried generic:

`
  - name: Will generate the playbooks for each selector/module.
    fortinet.fortios.fortios_export_config_playbook:
      selectors:
          - selector: system_vdom
          - selector: system.snmp_user
          - selector: ips_custom
      output_path: "/scratch"
`

Playbooks were generated with no details though. Any help would be appreciated.

**Comment by MaxxLiu22** [comment]
Hi @chr00ted ,

Thank you for your question. At the moment, we don't have a feature to export all selectors at once, but I've compiled all the selectors for you [here](https://github.com/user-attachments/files/16616894/selectors.json). While it is possible to write a loop to download these playbooks, please note that not all selectors are supported in your FOS version. This may cause some tasks to fail if they are not compatible with your system.

Regarding your concern about playbooks being generated with no details, could you clarify if the playbooks appear empty? In my setup, your script successfully exported the content. May I kindly ask which FOS version you are using? Also, please ensure that there is a configuration present in your specified path.

```
  tasks:
    - name: Read the JSON file
      set_fact:
        selectors: "{{ lookup('file', 'selectors.json') | from_json }}"
    - name: Will generate the playbooks for each selector/module.
      fortinet.fortios.fortios_export_config_playbook:
        selectors:
        - selector: "{{item}}"
        output_path: "./"
      loop: "{{ selectors }}"
```

Thanks,
Maxx
