### ISSUE TITLE
fortios_user_group can't configure "config match" section

### ISSUE THREAD

**Issue by rrobles12** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#35]
Ansible Version:

```
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
```

Ubuntu Version:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

Fortigate VM Version (Trial):

```
FortiGate-VM64 # get system status
Version: FortiGate-VM64 v6.2.3,build1066,191218 (GA)
Virus-DB: 1.00000(2018-04-09 18:07)
Extended DB: 1.00000(2018-04-09 18:07)
Extreme DB: 1.00000(2018-04-09 18:07)
IPS-DB: 6.00741(2015-12-01 02:30)
IPS-ETDB: 0.00000(2001-01-01 00:00)
APP-DB: 6.00741(2015-12-01 02:30)
INDUSTRIAL-DB: 6.00741(2015-12-01 02:30)
Serial-Number: FGVMEVHOGQZIMMA5
IPS Malicious URL Database: 1.00001(2015-01-01 01:01)
Botnet DB: 1.00000(2012-05-28 22:51)
License Status: Valid
Evaluation License Expires: Tue Jul 14 10:27:39 2020
VM Resources: 1 CPU/1 allowed, 1002 MB RAM/2048 MB allowed
Log hard disk: Available
Hostname: FortiGate-VM64
Operation Mode: NAT
Current virtual domain: root
Max number of virtual domains: 1
Virtual domains status: 1 in NAT mode, 0 in TP mode
Virtual domain configuration: disable
FIPS-CC mode: disable
Current HA mode: standalone
Branch point: 1066
Release Version Information: GA
FortiOS x86-64: Yes
System time: Tue Jun 30 08:18:14 2020
```

I'm having issues with the  fortios_user_group module. I can create a new member but I cannot create a match config. When I attempt to run the playbook I get:

`fatal: [192.168.109.128]: FAILED! => {"changed": false, "meta": {"build": 1066, "error": -5, "http_method": "POST", "http_status": 500, "name": "group", "path": "user", "revision": "d2f0305ca077b2443fbea23b5f7648c4", "revision_changed": false, "serial": "FGVMEVOV0E3YRT13", "status": "error", "vdom": "root", "version": "v6.2.3"}, "msg": "Error in repo"}`

The playbook is as follows:

```
  fortios_user_group:
    host: "{{ host }}:{{ portnum }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vdom: "{{ vdom }}"
    https: False
    ssl_verify: False
    state: "present"
    user_group:
      name: "TACACS-admin"
      member:
       -
          name: "ISE"
      match:
       -
          id: "1"
          server_name: "ISE"
          group_name: "test"
```

If I create match config 1 manually on the firewall as follows:

```
config user group
    edit "SSO_Guest_Users"
    next
    edit "Guest-group"
        set member "guest"
    next
    edit "TACACS-admin"
        set member "ISE"
        config match
            edit 1
                set server-name "ISE"
                set group-name "test2"
            next
        end
    next
end
```

and run the playbook I do not get the error message above. However, I still cannot change values that have been manually entered for the config match section. For example, if I change the group name from "test" to "test2" it will not apply it even though the playbook shows this was changed. The group creation works fine, it's just the config match that is not working. Am I doing something wrong?

**Comment by chillancezen** [comment]
hi @rrobles12, thanks for your issue!

could you please run your playbook in newer [`httpapi`](https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/playbook.html) way? the way in your playbook is still using legacy `fortiosapi` which is about to deprecate.


** **Please also install Anisble with Python3 to prevent any Ansible Py2/Py3 compatibility issue**
** **And also install latest FortiOS Galaxy collection.**
```
#pip3 install ansible==2.9.10
#ansible-galaxy collection install fortinet.fortios -f
```

here is my playbook and inventory:
```
$cat test.yml
- hosts: fortigate01
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   TACACS_SERVER: 'ISE'
  tasks:
   - name: Configure TACACS Server
     fortinet.fortios.fortios_user_tacacsplus:
        vdom: 'root'
        state: 'present'
        user_tacacsplus:
            name: '{{ TACACS_SERVER }}'
            server: 'A.B.C.D'
            key: 'TEST'

   - name: Create User Group
     fortios_user_group:
        vdom: 'root'
        state: 'present'
        user_group:
            name: "TACACS-admin"
            member:
             - name: '{{ TACACS_SERVER }}'
            match:
             - id: "1"
               server_name: '{{ TACACS_SERVER }}'
               group_name: "test1"


$cat hosts
[fortigates]
fortigate01 ansible_host=192.168.190.130 ansible_user="admin" ansible_password="<your own password>"

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios
```

and then run you playbook:
```
$ansible-playbook -i hosts test.yml -vvv
``

it works fine for my testbeds and you can modify you playbook and run more again.

thanks,
Link
