### ISSUE TITLE
fortios_monitor_fact: ansible.module_utils.connection.ConnectionError: Method not found

### ISSUE THREAD

**Issue by mbonica703** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#356]
I'm starting out with using ansible to manage some FortiOS devices, with a pretty simple playbook:

```yaml
- name: Get FortiOS version
  hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  vars_prompt:
    - name: 'fortios_access_token'
      prompt: 'Enter your FortiOS access token'
      private: yes
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443


  tasks:
    - name: Get FortiOS version
      fortios_monitor_fact: # This module gets a FortiOS fact
        access_token: "{{ fortios_access_token }}"
        vdom: "{{ vdom }}"
        selector: "system_firmware" # Get the "system_firmware" fact specifically
      register: fortios_version # Make a note of the output and store it in a "fortios_version" variable

    - name: Display local user information
      debug:
        var: fortios_version

```

Running it with `ansible-playbook test-playbook.yaml -i hosts`, and the hosts file looks like this:

```ini
[fortigates]
fortigate01 ansible_host=REDACTED_IP
```

But I get this error output:

```
PLAY [Get FortiOS version] *********************************************************************************

TASK [Gathering Facts] *************************************************************************************
ok: [fortigate01]

TASK [Get FortiOS version] *********************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: Method not found
fatal: [fortigate01]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/vscode/.ansible/tmp/ansible-local-4279s0249g5d/ansible-tmp-1732039928.4735308-4434-278262836383788/AnsiballZ_fortios_monitor_fact.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/vscode/.ansible/tmp/ansible-local-4279s0249g5d/ansible-tmp-1732039928.4735308-4434-278262836383788/AnsiballZ_fortios_monitor_fact.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vscode/.ansible/tmp/ansible-local-4279s0249g5d/ansible-tmp-1732039928.4735308-4434-278262836383788/AnsiballZ_fortios_monitor_fact.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.fortinet.fortios.plugins.modules.fortios_monitor_fact', init_globals=dict(_module_fqn='ansible_collections.fortinet.fortios.plugins.modules.fortios_monitor_fact', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_fortios_monitor_fact_payload_mu2u5bmx/ansible_fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py\", line 3306, in <module>\n  File \"/tmp/ansible_fortios_monitor_fact_payload_mu2u5bmx/ansible_fortios_monitor_fact_payload.zip/ansible_collections/fortinet/fortios/plugins/modules/fortios_monitor_fact.py\", line 3246, in main\n  File \"/tmp/ansible_fortios_monitor_fact_payload_mu2u5bmx/ansible_fortios_monitor_fact_payload.zip/ansible/module_utils/connection.py\", line 199, in __rpc__\nansible.module_utils.connection.ConnectionError: Method not found\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *************************************************************************************************
fortigate01                : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```

My ansible version:

```
ansible [core 2.17.6]
  config file = None
  configured module search path = ['/home/vscode/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vscode/.local/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/vscode/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/vscode/.local/bin/ansible
  python version = 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0] (/home/vscode/.local/venvs/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
 ```
 
 (installed via pipx.)
 
 Dependencies:
 
 ```yaml
 ### Ansible dependencies
roles:

collections:
  # Install a collection from Ansible Galaxy.
  - name: fortinet.fortios
    version: ">=2.3.8"
    source: https://galaxy.ansible.com
  - name: arista.eos
    version: "=10.0.0"
    source: https://galaxy.ansible.com
```

**Comment by MaxxLiu22** [comment]
Hi @mbonica703 ,

Thank you for using our provider, your sctipt looks good and run well on My FOS 7.4.5

**Comment by MaxxLiu22** [comment]
Hi @mbonica703 ,

Thank you for using our collection! Your script looks good and runs well on my FortiGate with version 7.4.5. May I kindly ask which FortiOS version you are using? Additionally, could you please verify that the correct version of the FortiOS collection is installed on your FortiGate by typing the following command ``ansible-galaxy collection list``:

```
root@liang:~/ansible/fgt/github#356# ansible-playbook test-playbook.yaml -i hosts

PLAY [Get FortiOS version] ************************************************************************************

TASK [Gathering Facts] ****************************************************************************************
ok: [fortigate01]

TASK [Get FortiOS version] ************************************************************************************
ok: [fortigate01]

TASK [Display local user information] *************************************************************************
ok: [fortigate01] => {
    "fortios_version.meta.version": "v7.4.5"
}

TASK [Save FortiOS version to a local file] *******************************************************************
ok: [fortigate01]

PLAY RECAP ****************************************************************************************************
fortigate01                : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0    
```

```
root@liang:~/ansible/fgt/github#356# ansible-galaxy collection list

# /root/.ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
amazon.aws                               7.1.0  
ansible.netcommon                        7.0.0  
ansible.utils                            5.0.0  
fortinet.fortianalyzer                   1.7.0  
fortinet.fortiflexvm                     2.2.3  
fortinet.fortimanager                    2.8.0  
fortinet.fortios                         2.3.8     <-------------------------------------
fortinet.fortiswitch                     1.2.5  
```

Thanks,
Maxx

**Comment by mbonica703** [comment]
Maxx,

Thank you for following up!
My current firmware version is `v6.4.14 build2093 (GA)`.

The output of `ansible-galaxy collection list`:

```
# /home/vscode/.ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
fortinet.fortios                         2.3.8  

# /home/vscode/.local/venvs/ansible/lib/python3.11/site-packages/ansible_collections
Collection                               Version
---------------------------------------- -------
amazon.aws                               8.2.1  
ansible.netcommon                        6.1.3  
ansible.posix                            1.5.4  
ansible.utils                            4.1.0  
ansible.windows                          2.5.0  
arista.eos                               9.0.0  
awx.awx                                  24.6.1 
azure.azcollection                       2.7.0  
check_point.mgmt                         5.2.3  
chocolatey.chocolatey                    1.5.3  
cisco.aci                                2.10.1 
cisco.asa                                5.0.1  
cisco.dnac                               6.20.0 
cisco.intersight                         2.0.20 
cisco.ios                                8.0.0  
cisco.iosxr                              9.0.0  
cisco.ise                                2.9.3  
cisco.meraki                             2.18.2 
cisco.mso                                2.9.0  
cisco.nxos                               8.1.0  
cisco.ucs                                1.14.0 
cloud.common                             3.0.0  
cloudscale_ch.cloud                      2.4.0  
community.aws                            8.0.0  
community.ciscosmb                       1.0.9  
community.crypto                         2.22.1 
community.digitalocean                   1.27.0 
community.dns                            3.0.5  
community.docker                         3.13.0 
community.general                        9.5.0  
community.grafana                        1.9.1  
community.hashi_vault                    6.2.0  
community.hrobot                         2.0.2  
community.library_inventory_filtering_v1 1.0.1  
community.libvirt                        1.3.0  
community.mongodb                        1.7.7  
community.mysql                          3.10.3 
community.network                        5.0.3  
community.okd                            3.0.1  
community.postgresql                     3.6.1  
community.proxysql                       1.6.0  
community.rabbitmq                       1.3.0  
community.routeros                       2.19.0 
community.sap_libs                       1.4.2  
community.sops                           1.9.1  
community.vmware                         4.7.1  
community.windows                        2.3.0  
community.zabbix                         2.5.1  
containers.podman                        1.16.1 
cyberark.conjur                          1.3.0  
cyberark.pas                             1.0.27 
dellemc.enterprise_sonic                 2.5.1  
dellemc.openmanage                       9.7.0  
dellemc.powerflex                        2.5.0  
dellemc.unity                            2.0.0  
f5networks.f5_modules                    1.31.0 
fortinet.fortimanager                    2.7.0  
fortinet.fortios                         2.3.7  
frr.frr                                  2.0.2  
google.cloud                             1.4.1  
grafana.grafana                          5.5.1  
hetzner.hcloud                           3.1.1  
ibm.qradar                               3.0.0  
ibm.spectrum_virtualize                  2.0.0  
ibm.storage_virtualize                   2.5.0  
ieisystem.inmanage                       2.0.0  
infinidat.infinibox                      1.4.5  
infoblox.nios_modules                    1.7.0  
inspur.ispim                             2.2.3  
inspur.sm                                2.3.0  
junipernetworks.junos                    8.0.0  
kaytus.ksmanage                          1.2.2  
kubernetes.core                          3.2.0  
kubevirt.core                            1.5.0  
lowlydba.sqlserver                       2.3.4  
microsoft.ad                             1.7.1  
netapp.cloudmanager                      21.22.1
netapp.ontap                             22.12.0
netapp.storagegrid                       21.12.0
netapp_eseries.santricity                1.4.1  
netbox.netbox                            3.20.0 
ngine_io.cloudstack                      2.5.0  
ngine_io.exoscale                        1.1.0  
openstack.cloud                          2.2.0  
openvswitch.openvswitch                  2.1.1  
ovirt.ovirt                              3.2.0  
purestorage.flasharray                   1.31.1 
purestorage.flashblade                   1.18.0 
sensu.sensu_go                           1.14.0 
splunk.es                                3.0.0  
t_systems_mms.icinga_director            2.0.1  
telekom_mms.icinga_director              2.1.2  
theforeman.foreman                       4.2.0  
vmware.vmware                            1.5.0  
vmware.vmware_rest                       3.2.0  
vultr.cloud                              1.13.0 
vyos.vyos                                4.1.0  
wti.remote                               1.0.10 
```

**Comment by sunshinegorgon7** [comment]
I'm seeing the same exact issue on Firmware 7.6.0, while working fine on 7.4.4

ansible-core 2.16.13
Python 3.11.10
FortiOs 2.3.8

**Comment by MaxxLiu22** [comment]
Hi all,

How about setting up ansible_network_os in your environment by adding ``ansible_network_os: fortinet.fortios.fortios`` to your playbook or host file? This might be the reason why the task is failing, let me know if that doesn't solve your question.
```
- name: Get FortiOS version
  hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  # vars_prompt:
  #   - name: 'fortios_access_token'
  #     prompt: 'Enter your FortiOS access token'
  #     private: yes
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    ansible_network_os: fortinet.fortios.fortios   <-----------------------
  tasks:
    - name: Get FortiOS version
      fortios_monitor_fact: # This module gets a FortiOS fact
        access_token: 68g....
        vdom: root
```
host file
```
[fortigates]
fortigate01 ansible_host=10.160.12.12

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios
```
Thanks,
Maxx
