### ISSUE TITLE
fortios_system_zone 2.3.8 : error "parameter system_zone.interface.interface_name is empty"

### ISSUE THREAD

**Issue by imkwx** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#357]
Hello !

It seems like there is a regression in 2.3.8 in fortios_system_zone. While trying to add an interface to a zone like this:

```
- name: Add customer to zone
  fortios_system_zone:
    state: present
    member_state: present
    member_path: interface:interface_name
    system_zone:
      name: "test_zone"
      interface:
        - interface_name: test67_net
    access_token: "{{access_token}}"
```

I get the following error:
`parameter system_zone.interface.interface_name is empty`

This playbook works fine in 2.3.7 though!
After looking at the issues of this repo, it looks like #354

I'll use 2.3.7 for the moment as a workaround!
