### ISSUE TITLE
accprofile: "super_admin" not supported?

### ISSUE THREAD

**Issue by Txalamar** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#363]
Hi,

if I use the default Admin Profile "super_admin" as accprofile the Fortigate returns error :  

```
       "meta": {
        "action": "",
        "build": 2702,
        "cli_error": [
            "entry not found in datasource",
            "value parse error before 'super_admin'",
            "Command fail. Return code -3",
            "cmd_clean_context 0, abort=1"
```

Running the same set off commands (extracted from fortigate debug mode) in CLI does not generate the "error -3 " and ends up succesfully.

Also using a custom Admin Profile in accprofile does work.

My playbook task:

```
  tasks:
   - name: Crear un usuario administrador
     fortios_system_admin:
       state: "present"
       vdom: "{{ vdom }}"
       access_token: "{{ fortios_access_token }}"
       system_admin:
         accprofile: "super_admin"
         accprofile_override: "disable"
         name: "myadmin"
         comments: "My Admin"
         password: "apassword"
         email_to: "user@domain.com"
         force_password_change: "enable"
         allow_remove_admin_session: "enable"
         two_factor: "email"
         two_factor_authentication: "email"
         two_factor_notification: "email"
```

Versions: 
ansible [core 2.17.7]
python version = 3.12.3

**Comment by MaxxLiu22** [comment]
Hi @Txalamar ,

Thank you for bringing this issue to my attention. The playbook runs well on my side. Since you are creating a super admin user, it should be created through the root VDOM path with a super_admin profile user. Could you kindly verify if your {{ vdom }} is set to root? Additionally, could you check if your Ansible FOS provider is updated to version 2.3.9?
```
root@liang:~/ansible/fgt/github#363# ansible-playbook -i hosts github359.yaml 

PLAY [fortigates] **************************************************************

TASK [Crear un usuario administrador] ******************************************
changed: [fortigate01]

PLAY RECAP *********************************************************************
fortigate01                : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


root@liang:~/ansible/fgt/github#363# ansible-galaxy collection list
 
# /root/.ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
amazon.aws                               7.1.0  
ansible.netcommon                        7.0.0  
ansible.utils                            5.0.0  
fortinet.fortianalyzer                   1.8.0  
fortinet.fortiflexvm                     2.2.3  
fortinet.fortimanager                    2.8.2  
fortinet.fortios                         2.3.9  
fortinet.fortiswitch                     1.2.5  
```

Thanks,
Maxx

**Comment by Txalamar** [comment]
Hello Maxx,

thank you for your interest in the issue.

I've verified that the VDOM is root. It indeed is:

Regarding the collection version I was in 2.3.8. I upgraded to 2.3.9 but result did not change.

```
pa@leaf:~/ansible/fortigate$ ansible-galaxy collection list|grep forti
fortinet.fortios                         2.3.9
```

I did also install ansible inside a python venv so now I'm running ansible [core 2.18.1] And the Fortigate I'm using for the development is in v7.4.5.

Here is a snipe with a bit more output than previous:

```
    "meta": {
        "action": "",
        "build": 2702,
        "cli_error": [
            "entry not found in datasource",
            "value parse error before 'super_admin'",
            "Command fail. Return code -3"
        ],
       "error": -3,
        "http_method": "POST",
        "http_status": 500,
        "name": "admin",
        "path": "system",
        "revision": "2d5dd5eaacfe04383dc1f1d2b2f29d89",
        "revision_changed": false,
        "serial": "FGT60ETK**********",
        "status": "error",
        "vdom": "root",
        "version": "v7.4.5"
    },
    "msg": "Error in repo"
```

Mabe my env is completely broken. I'm also experiencing idempotence issues. 1st playbook execution results in a correct "changed" result (using a custom accprofile). Subsequent executions, due to the fact that the object (admin user) already exists, I get an error ("msg": "Error in repo"). And the only way to get rid of that error is to remove all attributes of system_admin except name. That way the playbook exits with an "ok" result.

Best regards,
P.

**Comment by MaxxLiu22** [comment]
It appears that FOS was unable to locate 'super_admin'. If you are accessing the correct VDOM, could you confirm if your credentials have full permissions to use the ``super_admin`` profile? Please note that the credentials must at least be associated with the super_admin profile.

Additionally, I noticed that if you attempt to update an existing user using the ``password`` argument, you might encounter a 403 error. This is because ``password`` can only be created via the fortios_system_admin resource. Updates, however, should be performed using the monitor module as shown below:
```
   - name: change password
     fortios_monitor:
       vdom: "root"
       selector: system.change-password
       params:
           mkey: myadmin2
           old_password: apassword
           new_password: apassword2
```
I hope this helps clarify the issue. Please let me know if you need further assistance!
