### ISSUE TITLE
fortios_router_bgp - diff does not work

### ISSUE THREAD

**Issue by jonasalexandersson** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#364]
Hi!

I can not get fortios_router_bgp to work with --diff.

```
---
- name: 'router_bgp.yml'
  hosts: 'all'
  vars:
    fgt_router_bgp_neighbors:
      - ip: '10.11.11.11'
        remote_as: '65200'
      - ip: '10.12.12.12'
        remote_as: '65200'
  tasks:
    - name: 'fortigate router bgp'
      fortinet.fortios.fortios_router_bgp:
        vdom: '{{ fgt_vdom_name }}'
        router_bgp:
          as: '{{ fgt_router_bgp_as }}'
          neighbor: '{{ fgt_router_bgp_neighbors }}'

...
```
If I change vars, so one neighbor has remote_as 65201, and run again:

```
cat router_bgp.yml
---
- name: 'router_bgp.yml'
  hosts: 'all'
  vars:
    fgt_router_bgp_neighbors:
      - ip: '10.11.11.11'
        remote_as: '65200'
      - ip: '10.12.12.12'
        remote_as: '65201' # <<<<<<<<<<<<<<<<<<<< this is changed
  tasks:
    - name: 'fortigate router bgp'
      fortinet.fortios.fortios_router_bgp:
        vdom: '{{ fgt_vdom_name }}'
        router_bgp:
          as: '{{ fgt_router_bgp_as }}'
          neighbor: '{{ fgt_router_bgp_neighbors }}'
...

# Running with --check --diff
ansible-playbook -v router_bgp.yml -l 9512 -CD
PLAY [router_bgp.yml] ******************************************************************************************************************************************************************************************
TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
ok: [fortigate-01]

TASK [fortigate router bgp] ************************************************************************************************************************************************************************************
ok: [fortigate-01] => changed=false
  meta:
    as: '64701'
    neighbor:
    - ip: 10.11.11.11
      remote_as: '65200'
    - ip: 10.12.12.12
      remote_as: '65201'

PLAY RECAP *****************************************************************************************************************************************************************************************************
fortigate-01             :ok=2 changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0


# Running without --check --diff
ansible-playbook -v router_bgp.yml -l 9512
PLAY [router_bgp.yml] ******************************************************************************************************************************************************************************************
TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
ok: [fortigate-01]

TASK [fortigate router bgp] ************************************************************************************************************************************************************************************
changed: [fortigate-01] => changed=true
  meta:
    build: 1706
    http_method: PUT
    http_status: 200
    name: bgp
    old_revision: 418d4798d376eeffa573d687fcdf0b71
    path: router
    revision: 8a7802ac6d3d46f809b64b7edbb524ee
    revision_changed: true
    serial: XXXXXXXX
    status: success
    vdom: 9512-01
    version: v7.2.10

PLAY RECAP *****************************************************************************************************************************************************************************************************
fortigate-01             :ok=2  changed=1 unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

```
ansible [core 2.16.12]
  python version = 3.12.3 (main, Jan 17 2025, 18:03:48) [GCC 13.3.0] (/data/ansible/venv/bin/python)
  jinja version = 3.1.4
  libyaml = True

ansible-galaxy collection list
# /data/ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
...
fortinet.fortios                         2.3.9
```
