### ISSUE TITLE
Unable to create new policy with fortios_firewall_policy

### ISSUE THREAD

**Issue by yamayama120** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#368]
Target: FortiGate v7.4.4

When I use fortios_firewall_policy to create a new policy, I get an error.
However, when I run this after putting the same settings in the GUI, the execution is ok (changed if partially changed) and can be executed.
Only the new creation fails.

```
---
- hosts: Forti
  gather_facts: no
  collections:
    - fortinet.fortios
  tasks:
  - name: create policy
    fortios_firewall_policy:
      vdom: "{{ vdom }}"
      state: present
      access_token: "{{ access_token }}"
      firewall_policy:
        name: test
        srcintf: 
          - name: "NW1"
        srcaddr: 
          - name: "TEST-NW1"
        dstintf: 
          - name: "WAN"
        dstaddr: 
          - name: "all"
        service: 
          - name: "HTTP"
        policyid: "1"
```

**Comment by net-luis-santana** [comment]
Hello @yamayama120 

I believe it is because the ID parameter is missing in the rule

Try the following:

`---
- hosts: Forti
  gather_facts: no
  collections:
    - fortinet.fortios
  tasks:
  - name: create policy
    fortios_firewall_policy:
      vdom: "{{ vdom }}"
      state: present
      access_token: "{{ access_token }}"
      firewall_policy:
        id: 99
        name: test
        srcintf: 
          - name: "NW1"
        srcaddr: 
          - name: "TEST-NW1"
        dstintf: 
          - name: "WAN"
        dstaddr: 
          - name: "all"
        service: 
          - name: "HTTP"
        policyid: "1"`

It is worth remembering that if there are existing rules, the ID of the new policy cannot be the same.

Otherwise, it will update the policy with the respective ID.

**Comment by yamayama120** [comment]
Hello @net-luis-santana 

Some of the information is abbreviated, but please check here.

```
{"changed": false, meta:{"build":2662, "cli_error": [], "error": -56, "http_method": "POST", "http_status": 500, "name": "policy", "path": "firewall", （omission）,"status": "error", (omission),"version": "v7.4.4"}, "msg": "Error in repo"}
```

**Comment by net-luis-santana** [comment]
I had the same error and fixed it by changing the policy id.

Do you have other rules already created?

If so, check the id of the last policy created and create it with the next available value.

**Comment by MaxxLiu22** [comment]
Hi @yamayama120 ,

Thank you for your question. You may need to set the ``schedule`` in your playbook as it is required, and GUI automatically set it with ``always`` by default. Additionally please ensure that the name is unique.
```
  - name: create policy
    fortios_firewall_policy:
      vdom: "{{ vdom }}"
      state: present
      access_token: y6mrmbQHzHmwprwws8h331H8q53s8z
      firewall_policy:
        dstaddr:
        - name: all
        dstintf:
        - name: port2
        name: asb_policy3
        policyid: '121'
        schedule: always
        service:
        - name: HTTP
        srcaddr:
        - name: all
        srcintf:
        - name: port1
```
Thanks,
Maxx
