### ISSUE TITLE
There are items that cannot be set in fortios_vpn_ssl_settings

### ISSUE THREAD

**Issue by yamayama120** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#369]
Target: FortiGate v7.4.4

I used fortios_vpn_ssl_settings and was able to configure some of the settings,
However, there are two points that cannot be set.

<Point1>
In the GUI, the parameter “source_interface” is not set in the connection settings > interface to listen,
Is the parameter “source_interface” correct?
When I try to execute with this parameter, an error occurs.
I could not find a parameter to set this part.

<Point 2>
In the GUI, the Authentication/Portal Mapping > Portal settings for all other users/groups
Is the parameter “default_portal” correct?
I don't get any errors when I specify this parameter,
No changes are made to any part of the portal.

```
---
- hosts: Forti
  gather_facts: no
  collections:
    - fortinet.fortios
  tasks:
  - name: create policy
    fortios_vpn_ssl_settings:
      vdom: "{{ vdom }}"
      access_token: "{{ access_token }}"
      vpn_ssl_settings:
        status: "enable"
        source_interface:
          - name: "WAN"
        port: "{{ own_port }}"
        authentication_rule:
          - groups:
              - name: "{{ user }}"
            portal: "{{ portal }}"
            id: 1
        servercert: "{{ own_cert }}"
        default_portal: "{{ own_portal }}"
```

**Comment by MaxxLiu22** [comment]
Hi @yamayama120 ,

Thank you for your question. Are you looking for his playbook? The source_interface and portal are under the "authentication_rule" block. Please note that the argument names may differ between the GUI and Ansible.
```
  tasks:
  - name: create policy
    fortios_vpn_ssl_settings:
      vdom: root
      vpn_ssl_settings:
        authentication_rule:
          - id: 1
            source_interface:
              - name: "port2"
            source_address:
              - name: "SSLVPN_TUNNEL_ADDR1"
            users:
              - name: "guest"
            portal: "full-access"
```
Thanks,
Maxx

**Comment by yamayama120** [comment]
@MaxxLiu22 
My previous question was interrupted, sorry.
Since your answer did not solve my problem, I will describe my question again.
I would like to hear what the parameters are for setting.

＜1>
I would like to change the following settings in the GUI screen
VPN>SSL-VPN setting>Connection setup>Listening interface
※The names of the items may be different because I am translating them.

Please let me know the parameters to configure this setting.

<2>
I would like to change the following settings on the GUI screen.
VPN>SSL-VPN setting>Authentication/Portal Mapping > Portal (settings for all other users/groups)
※The item names may be different because I am translating.

**Comment by MaxxLiu22** [comment]
Hi @yamayama120 ,

Thank you for your clarification. After some testing, I found that GUI "VPN > SSL-VPN Settings > Connection Setup > Listening Interface" corresponds to ``source_interface`` under module vpn_ssl_settings. The only universal setting for GUI all other users/groups is ``default_portal`` under module vpn_ssl_settings.

Before specifying these settings, you need to set ``source_address`` and ``source_address6`` under module vpn_ssl_settings to "all." This allows the Ansible to locate other users/groups in the GUI, which can be a bit confusing. The way the GUI presents this logic differs slightly from the underlying data structure. I configured these settings through the GUI and verified their relationships via the CLI
```
FGT-VM-103 (settings) # show
config vpn ssl settings
    set banned-cipher SHA1 SHA256 SHA384
    set servercert ''
    set auth-timeout 28801
    set port 443
    set source-interface "port3"
    set source-address "all"
    set source-address6 "all"
    set default-portal "web-access"
    config authentication-rule
        edit 1
            set source-interface "port3"
            set source-address "SSLVPN_TUNNEL_ADDR1"
            set users "guest"
            set portal "full-access"
        next
    end
end
```
```
  tasks:
    - name: create policy
      fortios_vpn_ssl_settings:
        vdom: root
        vpn_ssl_settings:
          source_interface:
            - name: "port3"  # <------ VPN>SSL-VPN setting>Connection setup>Listening interface
          default_portal: "web-access"  # < ------VPN>SSL-VPN setting>Authentication/Portal Mapping > Portal (settings for all other users/groups)
          source_address:
            - name: "all"    # < ------ specify to "all" coorespdonding to All Other Users/Groups on GUI
          source_address6:
            - name: "all"    # < ------ specify to "all" coorespdonding to All Other Users/Groups on GUI
          authentication_rule:
            - id: 1
              source_address:
                - name: "SSLVPN_TUNNEL_ADDR1"
              users:
                - name: "guest"
              portal: "full-access"
```

Thanks,
Maxx
