### ISSUE TITLE
 No able to configure new vlan with fortios_system_interface

### ISSUE THREAD

**Issue by lvrfrc87** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#37]
SUMMARY

I am trying to create a new interface on FortiGate 3100D using fortios_system_interface but all I can get is:

MSG:

Error in repo

Most probably the way I am writing the playbook is wrong but the error message is not very meaningful.
This bug report might be also useful for future reference.
ISSUE TYPE

    Bug Report

COMPONENT NAME

fortios_system_interface
ANSIBLE VERSION

ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/local/lib/python3.6/site-packages/tm_merger/modules', '/usr/local/lib/python3.6/site-packages/pyateos/modules', '/usr/local/lib/python3.6/site-packages/git_acp/modules', '/usr/local/lib/python3.6/site-packages/napalm_ansible/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

STEPS TO REPRODUCE

- hosts: localhost
  tasks:
  - name: Configure interfaces.
    fortios_system_interface:
      host:  '10.76.34.42'
      username: 'user'
      password: 'password'
      vdom:  'root'
      state: 'present'
      ssl_verify: 'False'
      system_interface:
        interface: 'ag1_int'
        type: 'vlan'
        name: 'prod_red_tran_t10_vl1910'
        alias: 'prod_red_tran_t10_vl1910'
        vlanid: '1910'
        vdom: 'RED'
        ip: '10.76.101.26 255.255.255.248'
        allowaccess: 'ping'

ACTUAL RESULTS

fatal: [localhost]: FAILED! => {
    "changed": false,
    "meta": {
        "build": 1637,
        "error": -54,
        "http_method": "POST",
        "http_status": 500,
        "name": "interface",
        "old_revision": "44c31cc52b74d74eff3002455db52070",
        "path": "system",
        "revision": "d80b69b42683ca6922f0466ddb46e7e9",
        "revision_changed": true,
        "serial": "FGT31D3Z15800162",
        "status": "error",
        "vdom": "root",
        "version": "v6.4.1"
    }
}

MSG:

Error in repo

**Comment by chillancezen** [comment]
hi @lvrfrc87 , 

I can not reproduce your issue, the following playbook works find for my testbed(6.4.0):
please run the playbook with FortiOS Galaxy Collection : https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/install.html 
```
$cat hosts
[fortigates]
fortigate01 ansible_host=192.168.190.137 ansible_user="admin" ansible_password="<your own password>"

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios
```

```
$cat interface_vlan.yml
- hosts: fortigate01
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
   - name: Create a VLAN subinterface
     fortios_system_interface:
        vdom:  "{{ vdom }}"
        state: "present"
        system_interface:
            interface: 'port1'
            name: 'vlanport01'
            alias: 'vlanport01'
            type: 'vlan'
            vlanid: 100
            vdom: 'root'
            ip: '10.76.101.26 255.255.255.248'
            allowaccess: 'ping'
```

then run it: `$ansible-playbook -i hosts -vvv interface_vlan.yml`


for further debug, could you login to FortiGate shell and turn on debugging options by entering:
```
diagnose debug enable
diagnose debug cli 8
diagnose debug application httpsd -1
```

and share the output after running your playbook ?


btw, I see you gave the values for the two options, could you try other values for them?
```
interface: 'ag1_int'
vdom: 'RED'
```

thanks,
LIn
