### ISSUE TITLE
Unable to create vdom with fortios_system_vdom

### ISSUE THREAD

**Issue by yamayama120** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#370]
Target: FortiGate v7.4.4

I get an error when I try to create a new vdom in fortios_system_vdom.

In the GUI, though, the VDOM creation operation can only be performed under the global VDOM,
When using fortios_system_vdom, do I have to specify global for the vdom parameter as well?
I have tried specifying global, but I am getting an error here as well.

```
---
- hosts: Forti
  gather_facts: no
  collections:
    - fortinet.fortios
  tasks:
  - name: create vdom
    fortios_system_vdom:
      vdom: "{{ vdom }}"
      state: "present"
      access_token: "{{ access_token }}"
      system_vdom:
        name: "NEW-VDOM"
```

**Comment by MaxxLiu22** [comment]
Hi @yamayama120 ,

Thank you for your question. You may specify your VDOM as "root" or simply ignore this argument. Before creating a VDOM, please ensure that the "multi-vdom" mode is enabled in the global settings. This playbook works well on my FOS 7.4.4
```
  tasks:
  - name: enable multi-vdom mode
    fortios_system_global:
      system_global:
        vdom_mode: multi-vdom
      vdom: '{{vdom}}'
    
  - name: Sleep for 20 seconds for reboot
    ansible.builtin.wait_for:
      timeout: 20
    delegate_to: localhost

  - name: create a vdom
    fortios_system_vdom:
      state: '{{state}}'
      # vdom: root
      system_vdom:
        name: ansible102
```
Thanks,
Maxx
