### ISSUE TITLE
How to change a password user and disable user Admin

### ISSUE THREAD

**Issue by net-luis-santana** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#371]
I need a way to change the admin user password and disable it in the firewall

**Comment by MaxxLiu22** [comment]
Hi @net-luis-santana ,

Thank you for your question. You can use fortios_monitor and select system.change-password to change your user's password. Other administrator settings can be updated using the [fortios_system_admin](https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_system_admin.html) module.

You mentioned disabling it in the firewall—could you provide more details about your specific scenario? Admin users are primarily used to manage FortiOS (FOS). If you need to restrict access, you can create a user with fewer permissions. However, if your goal is to control user traffic through the firewall, you may need to define users under "User & Authentication(fortios_user_* related modules), and apply them in your Source section under firewall policy.
```
  tasks:
   -  name: Change password
      fortios_monitor:
        vdom: "root"
        selector: system.change-password
        params:
            mkey: test_admin
            old_password: apassword
            new_password: apassword2
```

Thanks,
Maxx
