### ISSUE TITLE
how to create a new vdom_link

### ISSUE THREAD

**Issue by yamayama120** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#373]
I would like to create a new vdom_link.
In the GUI, under the vdom of global, the following is the setting content of the following location.
Interface>NewCreate>Vdom_link 

Which module should I use to configure Interface0 and Interface1?

**Comment by MaxxLiu22** [comment]
Hi @yamayama120 ,

Thank you for your question. After checking through the CLI, I found that FortiOS creates two separate interface objects to manage the VDOM link. Therefore, you may need to define two fortios_system_interface models to manage Interface0 and Interface1 after creating a VDOM link. Let me know if that is not what you are looking for:
```
  tasks:
    - name: create a vdom link
      fortios_system_vdom_link:
        vdom: root
        state: present
        system_vdom_link:
            name: "vdom_link1"
            type: "ppp"
            vcluster: "vcluster1"
    - name: edit vdom_link10 interface
      fortios_system_interface:
        state: '{{state}}'
        system_interface:
          allowaccess:
          - ping
          - ssh
          - https
          name: "vdom_link10"
          vdom: root
        vdom: root
    - name: edit vdom_link11 interface
      fortios_system_interface:
        state: '{{state}}'
        system_interface:
          allowaccess:
          - ping
          - ssh
          - https
          name: "vdom_link11"
          vdom: ansible100
        vdom: root
```
Thanks,
Maxx
