### ISSUE TITLE
Error re-running fortios_router_static

### ISSUE THREAD

**Issue by yamayama120** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#374]
I created a PlayBook using fortios_router_static to configure a static route.
The new creation succeeds, but the re-run fails.

My assumption was that the execution would succeed while maintaining power equality as "ok", not as "failed".
In some of the other modules the re-run does not cause an error.

This is because I plan to set several items from PlayBook at a time,
I need to take into account the possibility that each configuration item will be re-run.
Please let me know the cause.

```
- name: create staticroute
  fortios_router_static:
    vdom: "{{ vdom }}"
    state: present
    access_token: "{{ access_token }}"
    router_static:
      dst: "{{ dst }}"
      device: "{{ device }}"
      gateway:"{{ gateway }}"
```
