### ISSUE TITLE
How to display GUI screen for SSL-VPN settings

### ISSUE THREAD

**Issue by yamayama120** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#377]
The SSL-VPN configuration screen is not displayed in GUI by default.

We are aware that the following command will allow it to be displayed in the GUI.

```
config system settings
  set gui-sslvpn enable
end
```
＜Question＞
Is it possible to configure this setting from an ansible module function?
If there is no dedicated module available,
What is the module to execute this CLI command from ansible?

**Comment by MaxxLiu22** [comment]
Hi @yamayama120 ,

You can use the following script to enable your GUI SSL VPN settings. The second task will create a one-time CLI command object under "system auto-script." This script will run immediately after the object is created.

If you would like more details on usage, feel free to check the Ansible FortiOS documentation [here](https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/gen/fortios_system_auto_script.html).
```
  tasks:
    - name: Configure system settings.
      fortios_system_settings:
        vdom: "{{ vdom }}"
        system_settings:
          gui_sslvpn: enable
    - name: Create a CLI script and run once immediately.
      fortios_system_auto_script:
        vdom: "{{ vdom }}"
        state: present
        system_auto_script:
          name: disable_gui_sslvpn2
          script: "config system settings\n
            set gui-sslvpn disable\n
            set ike-tcp-port 4502\n
            end"
          start: auto
          repeat: 1

```
```
FGT-VM-103 # config system auto-script 

FGT-VM-103 (auto-script) # show
config system auto-script
    edit "disable_gui_sslvpn2"
        set start auto
        set script "config system settings
 set gui-sslvpn disable
 set ike-tcp-port 4502
 end"
    next
end
```
Thanks,
Maxx
