### ISSUE TITLE
fortios_system_accprofile: cli-* invalid

### ISSUE THREAD

**Issue by Txalamar** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#381]
Hello,

I'm getting a :

`Command fail. Return code -672`

if I use parameters cli_ of the module fortios_system_accprofile.

In Fortigate CLI I have to use "cli-", not "cli_". May this be the cause?

```

...
cli-diagnose             Enable/disable permission to run diagnostic commands.
...
```

Fortigate firmware version : 7.4.5
Ansible : fortinet.fortios 2.3.9

Regards.

**Comment by MaxxLiu22** [comment]
Hi @Txalamar ,

Thank you for your question. We replace argument names with "-" using "_" to comply with Ansible community development requirements. As a result, cli_diagnoe should be converted to cli-diagnoe at the backend when sending an API request.

In my FOS 7.4.5 setup, Ansible FOS 2.3.9 successfully creates the accprofile with the correct settings using the script below. I was wondering if you are using user credentials with the appropriate permissions to create an accprofile. I am using admin credentials. If that is not the issue, you may consider enabling the debug function on FOS to collect more information.
```
  tasks:
  - fortios_system_accprofile:
      state: present
      system_accprofile:
        name: admin_no_access25
        cli_get: enable
        cli_diagnose: enable
```
```
diagnose debug cli 8
diagnose debug application httpsd -1
diagnose debug enable
```
Thanks,
Maxx
