### ISSUE TITLE
fortios_switch_controller_managed_switch: Trunk is removed when adding 'description' to a member interface

### ISSUE THREAD

**Issue by PieterL75** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#383]
I have an MLAG trunk interface, with a member on 2 different fortiswitches
```
    edit "swcore-01"
        config ports
            edit "port52"
                set port-owner "TRUNK1"
                set speed auto-module
                set lldp-profile "default"
                set export-to "root"
            next
            edit "TRUNK1"
                set vlan "_default"
                set allowed-vlans "quarantine"
                set untagged-vlans "quarantine"
                set type trunk
                set mode lacp-active
                set mclag enable
                set members "port52"
            next
        end
    next
    edit "swcore-02"
        config ports
            edit "port52"
                set port-owner "TRUNK1"
                set speed auto-module
                set lldp-profile "default"
                set export-to "root"
            next
            edit "TRUNK1"
                set vlan "_default"
                set allowed-vlans "quarantine"
                set untagged-vlans "quarantine"
                set type trunk
                set mode lacp-active
                set mclag enable
                set members "port52"
            next
        end
```
When I run this playbook, I get an error, and the TRUNK1 interface is deleted
```
- name: ManagedSwitches
  fortinet.fortios.fortios_switch_controller_managed_switch:
    vdom: "root"
    access_token: "{{ host_access_tokens[fortios_switchcontroller] }}"
    state: present
    switch_controller_managed_switch:
    - name: swcore-01
      switch_id: swcore-01
      ports:
        - port_name: "port52"
          description: "UPLINK:sw1:port1"
    - name: swcore-02
      switch_id: swcore-02
      ports:
        - port_name: "port52"
          description: "UPLINK:sw2:port1"
```

The error I get is `Read-only reference to trunk interface when port is a member of a trunk.`

Is there anything I'm doing wrong ?

**Comment by MaxxLiu22** [comment]
Hi @PieterL75,

Thank you for bringing this issue to our attention. This may occur when editing an inner block of a module, as Ansible FOS treats the entire block (ports) as a single object. Consequently, it uses the PUT method to overwrite the existing configuration.

Since ports 1–52 are predefined and non-deletable interfaces in FOS, the backend prevents the PUT request from deleting them, ensuring their configuration remains intact. However, "TRUNK1" is a deletable interface and can be overwritten by Ansible FOS.

To address this issue, we provide the member operation, which allows you to modify only the specified block. However, please note that there are known issues with the member operation in version 2.3.9, causing it to fail at the moment. Our development team is actively working on a resolution.

If the member operation were functioning correctly, the script would look like this, this would only edit the port1 config and keep other ports' config:

```
  - name: ManagedSwitches
    fortinet.fortios.fortios_switch_controller_managed_switch:
      vdom: "root"
      state: present
      member_state: present
      member_path: "ports:port_name"
      switch_controller_managed_switch:
        name: swcore-01
        fsw_wan1_peer: fortilink
        switch_id: S548DN4K16000129
        ports:
          - port_name: "port1"
            description: "UPLINK:sw1:port1"
```
In the meantime, as a workaround, you may need to explicitly define the "TRUNK1" port in your playbook alongside your other ports to prevent it from being deleted during the next Ansible execution. Please let me know if that doesn't solve your question.

Thank,
Maxx
