### ISSUE TITLE
Issue with ansible module: fortios_system_admin

### ISSUE THREAD

**Issue by merijndk90** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#387]
With the ansible module: fortios_system_admin, I try to add a remote group but get the error: 

```json
"meta": {
        "action": "",
        "build": 3462,
        "cli_error": [
            "password must be set",
            "object set operator error, -204 discard the setting",
            "Command fail. Return code -204"
        ],
        "error": -204,
        "http_method": "POST",
        "http_status": 500,
        "name": "admin",
        "path": "system",
        "revision": "xxxx",
        "revision_changed": false,
        "serial": "xxxx",
        "status": "error",
        "vdom": "root",
        "version": "v7.6.2"
    }
```

Ansible module version is: 2.4.0
Fortigate Version is: 7.6.2

The module parameters are:

```yaml
fortinet.fortios.fortios_system_admin:
      state: present
      system_admin:
        name: "admin_test"
        accprofile: "super_admin"
        remote_auth: enable
        remote_group: "admin_test_group"
        two_factor: disable
        wildcard: disable
        vdom:
        - name: root
```

When I set the parameter password it creates a type of Remote User and not a type of Remote. Any idea what I'm doing wrong?
