### ISSUE TITLE
Configure system zone return error when try to attach to interface.

### ISSUE THREAD

**Issue by lvrfrc87** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#39]
I am trying to configure a security zone and attach to an existing interface. I can create only the security zone successful. When I try to attach the security zone to and existing and available interface, I get `Error in repo`. From GUI I can successfully configure zone and attach to interface.

```
      - name: CONFIG | Configure security zone.
        fortios_system_zone:
          host: "{{ inventory_hostname }}"
          username: "{{ username }}"
          password: "{{ password }}"
          vdom:  "BLUE"
          state: "{{ state }}"
          ssl_verify: "{{ ssl_verify }}"
          system_zone:
            interface:
              - interface_name: "b_t666_vl1666"
            name: "z_blue_t666"
```
 return:

```
TASK [CONFIG | Configure security zone.] ***************************************
fatal: [fw1a_prd_r3b15_ams7.nee.tmcs]: FAILED! => {
    "changed": false,
    "meta": {
        "build": 1637,
        "error": -5,
        "http_method": "POST",
        "http_status": 500,
        "name": "zone",
        "path": "system",
        "revision": "e47aa13fdc1bc94ad77fbbf3a6ed9bea",
        "revision_changed": false,
        "serial": "FGT31D3Z15800162",
        "status": "error",
        "vdom": "BLUE",
        "version": "v6.4.1"
    }
}

MSG:

Error in repo
```

<img width="853" alt="Screenshot 2020-07-21 at 16 49 46" src="https://user-images.githubusercontent.com/15066806/88069821-42769780-cb72-11ea-82b3-1d39930dacda.png">

**Comment by JieX19** [comment]
Hi @lvrfrc87,

I noticed you used the old ansible modules not Fortios Galaxy Collection.  Could you try the following playbook with Fortios Galaxy Collection? 

It works perfectly for my testbed of 6.0.0 and 6.2.3.
```
- hosts: fortigates
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    vdom: "root"
  tasks:
  - name: Configure security zone
    fortios_system_zone:
      vdom: "{{ vdom }}"
      state: "present"
      system_zone:
        interface:
          - interface_name: "port1"
        name: "zone_test"
```

Please let me know if you have any questions.
Thanks,
Jie
