### ISSUE TITLE
Change system admin password forbidden

### ISSUE THREAD

**Issue by dimitrimestdag** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#393]
Hello,
I'm trying to create a playbook based on ticket #126. Here it is:

```
- name: Change Admin password on FortiGate
  hosts: fgt30e
  gather_facts: no
  connection: httpapi
  vars:
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    vdom: root
  collections:
    - fortinet.fortios

  tasks:
    - name: Generate password
      set_fact:
        generated_password: "{{ lookup('community.general.random_string', length=12, min_lower=1, min_upper=1, min_numeric=1, min_special=1, override_special='-_=+!#$()[]') }}"

    - name: Verify the generate password
      debug:
        var: generated_password

    - name: Configure access profiles for system administrators.
      fortinet.fortios.fortios_system_accprofile:
          vdom: "{{ vdom }}"
          state: "present"
          access_token: "{{ fortios_access_token }}"
          system_accprofile:
            name: "admin"
            secfabgrp: "read-write"
            ftviewgrp: "read-write"
            authgrp: "read-write"
            sysgrp: "read-write"
            netgrp: "read-write"
            loggrp: "read-write"
            fwgrp: "read-write"
            vpngrp: "read-write"
            utmgrp: "read-write"
            wifi: "read-write"


    - name: "Delete User"
      fortios_system_admin:
        vdom:  "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        state: absent
        system_admin:
          name: "admin"
    
    - name: Configure admin password
      fortios_system_admin:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        state: present
        system_admin:
           name: "admin"
           accprofile: "admin"
           password: generated_password
```
but I have this error at the 3rd task : 
```
TASK [Delete User] ***********************************************************************************************************
fatal: [FGT30E]: FAILED! => {"changed": false, "meta": {"build": 1740, "cli_error": "delete table entry enova unset oper error ret=1\nCommand fail. Return code 1\n", "error": 1, "http_method": "DELETE", "http_status": 500, "mkey": "admin", "name": "admin", "path": "system", "revision": "c9d4d60e2fb5340929c55b39db49b012", "revision_changed": false, "serial": "FGT60XXX", "status": "error", "vdom": "root", "version": "v7.2.11"}, "msg": "Error in repo"}
```
Have you ever had the problem?

**Comment by MaxxLiu22** [comment]
Hi @dimitrimestdag ,

Thank you for your question.

It appears that user #129 attempted to change the password of a non-admin user(admin is undeletable). At that time, there might have been an issue with the password change API, leading them to use a workaround by recreating the user to update the password.

However, in the latest release of the Ansible Fortinet FortiOS collection (version 2.4.0), the password change API has been updated and should function as expected. You might consider utilizing this version for your tasks.

If you're aiming to test your script, assigning a non-admin user for password change operations could be work. Let me know if that doesn't solve your question.
```
- hosts: fortigates
  collections:
  - fortinet.fortios
  connection: httpapi
  gather_facts: 'no'
  vars:
    vdom: root
    ansible_httpapi_use_ssl: 'yes'
    ansible_httpapi_validate_certs: 'no'
    ansible_httpapi_port: 443
  tasks:
  - fortios_monitor:
      params:
        mkey: admin
        old_password: fortinet
        new_password: fortinet
      selector: system.change-password
      vdom: '{{vdom}}'
    name: Test fortios_monitor
```

Thanks,
Maxx
