### ISSUE TITLE
Unsupported parameters for (fortios_firewall_policy) module: inspection_mode found in firewall_policy

### ISSUE THREAD

**Issue by mbdraks** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#43]
Hi,

I've got the following error:

<pre>
TASK [fos_core : config firewall policy]
************************************************************************
fatal: [fg_core]: FAILED! => {"changed": false, "msg": <b>"Unsupported
parameters for (fortios_firewall_policy) module: inspection_mode found
in firewall_policy</b>. Supported parameters include: action, app_category,
app_group, application, application_list, auth_cert, auth_path,
auth_redirect_addr, av_profile, block_notification,
captive_portal_exempt, capture_packet, comments, custom_log_fields,
delay_tcp_npu_session, devices, diffserv_forward, diffserv_reverse,
diffservcode_forward, diffservcode_rev, disclaimer, dlp_sensor,
dnsfilter_profile, dscp_match, dscp_negate, dscp_value, dsri, dstaddr,
dstaddr_negate, dstintf, firewall_session_dirty, fixedport, fsso,
fsso_agent_for_ntlm, global_label, groups, icap_profile,
identity_based_route, inbound, internet_service,
internet_service_custom, internet_service_id, internet_service_negate,
internet_service_src, internet_service_src_custom,
internet_service_src_id, internet_service_src_negate, ippool,
ips_sensor, label, learning_mode, logtraffic, logtraffic_start,
match_vip, name, nat, natinbound, natip, natoutbound, ntlm,
ntlm_enabled_browsers, ntlm_guest, outbound, per_ip_shaper,
permit_any_host, permit_stun_host, policyid, poolname, profile_group,
profile_protocol_options, profile_type, radius_mac_auth_bypass,
redirect_url, replacemsg_override_group, rsso, rtp_addr, rtp_nat,
scan_botnet_connections, schedule, schedule_timeout, send_deny_packet,
service, service_negate, session_ttl, spamfilter_profile, srcaddr,
srcaddr_negate, srcintf, ssh_filter_profile, ssl_mirror,
ssl_mirror_intf, ssl_ssh_profile, state, status, tcp_mss_receiver,
tcp_mss_sender, tcp_session_without_syn, timeout_send_rst,
traffic_shaper, traffic_shaper_reverse, url_category, users, utm_status,
uuid, vlan_cos_fwd, vlan_cos_rev, vlan_filter, voip_profile, vpntunnel,
waf_profile, wanopt, wanopt_detection, wanopt_passive_opt, wanopt_peer,
wanopt_profile, wccp, webcache, webcache_https, webfilter_profile,
wsso"}
</pre>

I investigated this module: [fortios_firewall_policy.py](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/blob/fos_v6.2.0/galaxy_1.0.10/plugins/modules/fortios_firewall_policy.py) but I was not able to discover the root cause.

The parameter exists on fields and option_list so it must be some validation before that step (but that's just my guess).

If I comment that parameter the play works fine.

Environment:

- FOS 6.2.4 b1112

```bash
root@9cec4923cc62:/ansible# ansible --version
ansible 2.9.11
  config file = /ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.5 (default, Apr 19 2020, 20:18:17) [GCC 9.2.1 20191008]
```
I create this environment with a Dockerfile:
```Dockerfile
FROM ubuntu:19.10

RUN set -x && \
    \
    echo "==> Installing python3 and dependencies..."  && \
    apt update && \
    apt install python3-pip --yes && \
    \
    echo "==> Installing Ansible..."  && \
    pip3 install wheel setuptools && \
    pip3 install pywinrm && \
    pip3 install ansible && \
    \
    echo "==> Installing Ansible collections..."  && \
    echo "==> specific for FortiOS 6.2..."  && \
    ansible-galaxy collection install fortinet.fortios:1.0.10

WORKDIR /ansible
```
And this is the task (I'm building a role so this is only the task file):

```yaml
# tasks/config_firewall_policy.yml
---
- name: config firewall policy
  fortios_firewall_policy:
    state: present
    vdom: root
    firewall_policy:
      policyid: 100
      name: INET
      srcintf: 
        - name: port3
      dstintf: 
        - name: WAN_Zone
      srcaddr: 
        - name: all
      dstaddr: 
        - name: all
      service: 
        - name: ALL
      action: accept
      schedule: always
      nat: enable
      ssl_ssh_profile: certificate-inspection
      inspection_mode: flow
      # http_policy_redirect: 'enable'
```

Note that the same error occurs with the parameter `http_policy_redirect`.

**Comment by mbdraks** [comment]
FYI, [ansible-fortios-generic](https://github.com/fortinet/ansible-fortios-generic) is a possible workaround while this issue is not fixed.

```yaml
# tasks/config_firewall_policy_generic_dict.yml
---
- name: config firewall policy
  fortios_json_generic:
    vdom: '{{ vdom }}'
    json_generic:
      method: 'POST'
      path: '/api/v2/cmdb/firewall/policy'
      dictbody:
        policyid: 100
        name: INET
        srcintf: 
          - name: port3
        dstintf: 
          - name: WAN_Zone
        srcaddr: 
          - name: all
        dstaddr: 
          - name: all
        service: 
          - name: ALL
        action: accept
        schedule: always
        nat: enable
        ssl-ssh-profile: certificate-inspection
        inspection-mode: proxy
        http-policy-redirect: enable
  register: info

- name: display vars
  debug: msg='{{ info }}'
```
