### ISSUE TITLE
fortios_vpn_ipsec_phase1_interface and phase2  proposal artificially limited

### ISSUE THREAD

**Issue by thomnico** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#5]
Hello,

Trying to create VPN access with the module the proposal field is badly limited by the Ansible module (not the API).

The default when using the wizard for expl is: "aes128-sha256 aes256-sha256 aes128-sha1 aes256-sha1" the module only accept lower encryption des-XXX and only one proposal.

This prevents to properly configure VPN as expected and supported by the API.

Please allow any string and let the API handle the accepted values

**Comment by chillancezen** [comment]
@thomnico thanks Nicolas for the issue.
Yes current Galaxy collection only supports one algorithm in limited option range. 

we will release next build which  support full list and multiple algorithms one time.
please let me know if you really need this very urgently, I can give you a pre-release build.

thanks,
Link

**Comment by thomnico** [comment]
If not putting anything in proposal but setting the wizard type it works and align with the default of Forticlient which is great.

I can wait for next release and have the bug as a tracker

**Comment by chillancezen** [comment]
hi @thomnico ,

these issue have been fixed in latest release, you can find all these algorithms in online doc:

https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-1.0.9/gen/fortios_vpn_ipsec_phase1_interface.html

https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-1.0.9/gen/fortios_vpn_ipsec_phase2_interface.html

it has been verified via following playbook:
```
- hosts: fortigate01
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   phase1_name: 'foo_phase1'
   phase2_name: 'foo_phase2'
  tasks:
   - name: configure phase1 interface
     fortios_vpn_ipsec_phase1_interface:
        vdom:  "{{ vdom }}"
        state: 'present'
        vpn_ipsec_phase1_interface:
            name: '{{ phase1_name }}'
            interface: 'port1'
            net_device: 'disable'
            proposal:
                - 'des-md5'
                - 'des-sha1'
                - 'des-sha512'
            remote_gw: '1.1.1.1'
            psksecret: 'no secret'
   - name: configure phase2 interface
     fortios_vpn_ipsec_phase2_interface:
        vdom:  "{{ vdom }}"
        state: 'present'
        vpn_ipsec_phase2_interface:
            name: '{{ phase2_name }}'
            phase1name: '{{ phase1_name }}'
            proposal:
                - "null-md5"
                - "3des-md5"
```

install the latest galaxy collection: 
```
$ansible-galaxy collection install fortinet.fortios -f
```

I now resolve this issue to be fixed, please reopen it and let me know if there is anything I can do to help.

thanks,
Link
