### ISSUE TITLE
First time VPN deployment using Ansible

### ISSUE THREAD

**Issue by shariaty59** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#51]
Hi, I'm trying to do the simplest way to implement a VPN. I have a playbook named 'test.yml' as below:

```
- hosts: fortigates
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
  - name: Configure Phase1 Interface
    fortios_vpn_ipsec_phase1_interface:
      vdom:  "{{ vdom }}"
      vpn_ipsec_phase1_interface:
        interface: 'port1'
        name: 'VPN_TEST'
        net_device: 'disable'
        proposal:  'des-md5'
        peertype: 'any'
        wizard_type: 'custom'
        remote_gw: '22.33.44.201'
        psksecret: 'foo-password'
        dhgrp: '2'
        ike_version: '2'
        dpd: 'on-idle'
        dpd_retryinterval: '5'
        comments: 'test vpn ansible'

  - name: Configure Phase2 Interface
    fortios_vpn_ipsec_phase2_interface:
      vdom:  "{{ vdom }}"
      vpn_ipsec_phase2_interface:
        name: 'phase2_test'
        phase1name: 'VPN_TEST'
        proposal: 'des-sha512'
        dhgrp: '2'
        auto_negotiate: 'enable'
        keylife_type: 'seconds'
        keylifeseconds: '28800'
        dst_addr_type: 'subnet'
        dst_subnet: '173.43.165.131 255.255.255.255'
        src_addr_type: 'subnet'
        src_subnet: '10.10.20.80 255.255.255.255'
```

I am running it against the 'hosts' file as below:
```
[fortigates]
my_dev_fw ansible_host=192.168.1.10 ansible_user="admin" ansible_password="password"

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios
```

and get this error message when running the playbook:
`TypeError: 'NoneType' object has no attribute '__getitem__'\n"`

Please kindly advise what I am doing wrong.
Thank you in advanced.

**Comment by JieX19** [comment]
Hi @shariaty59 

TypeError: 'NoneType' object has no attribute '_getitem_'\n" usually means it tries to read a parameter but not found.

You missed a key variable: **state**.

Example as below:
```
tasks:
  - name: Configure Phase1 Interface
    fortios_vpn_ipsec_phase1_interface:
      state: "present"
      vdom:  "{{ vdom }}"
      vpn_ipsec_phase1_interface:
        interface: 'port1'
```

**Comment by shariaty59** [comment]
worked like a charm :) one last question, Do you know a way I pass the user name and password when I run it each time? instead of having it in the hosts file.

**Comment by JieX19** [comment]
@shariaty59,

Yes, you can pass the params ansible_user and ansible_password as below:

```
- hosts: fortigates
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    ansible_user: "admin"
    ansible_password: "123"
  tasks:
  - name: Configure Phase1 Interface
```

The hosts file should be like this:

[fortigates]
fortigate01 ansible_host=10.160.21.160

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios
