### ISSUE TITLE
fortios_user_group fails to add an LDAP group -- CLI err -56

### ISSUE THREAD

**Issue by freddygfy** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#54]
Trying to add a user group to match an LDAP group, and it is failing.

Task:
```
- name: Add Group
  fortios_user_group:
    vdom: "root"
    state: "present"
    user_group:
      name: "{{ fw_ldap_group_name }}"
      group_type: "firewall"
      member: 
       - name: "{{ fw_ldap_server_name }}"
      match:
       - server_name: "{{ fw_ldap_server_name }}"
         group_name: "{{ ldapadmin_group }}"
         id: 1
```

CLI Debug while task was running: 
```
0: config vdom
0: edit root
0: config user group
0: edit "<group name>"
0: set member "<member>" 
0: end
0: end
0: config vdom
0: edit root
0: config user group
0: edit "<group name>"
0: config match
0: edit 1
-56: end
```

httpsd debug:

```
[httpsd 6521 - 1599853964     info] cmdb_save_with_children[269] -- appended main node (nret=0, is_new=0)
[httpsd 6521 - 1599853964     info] cmdb_save_with_children[269] -- appended main node (nret=-56, is_new=1)
[httpsd 6521 - 1599853964    error] cmdb_save_with_children[275] -- saving failed for main node: 'match' (err=-56)
[httpsd 6521 - 1599853964    error] cmdb_commit_from_json[1335] -- error saving request object to CLI (-56)
[httpsd 6521 - 1599853964    error] _api_cmdb_v2_config[1023] -- error editing object (nret=-56)
[httpsd 6521 - 1599853964    error] api_return_http_result[567] -- API error -56 raised

(cut for brevity)

[httpsd 6521 - 1599853964     info] handle_cli_req_v2_vdom[1804] -- new CMDB API request (vdom='root',user=<user>)
[httpsd 6521 - 1599853964     info] api_cmdb_request_init_by_path[1197] -- new CMDB query (path='user',name='group')
[httpsd 6521 - 1599853964     info] api_return_cmdb_revision[699] -- ETag check for user.group
[httpsd 6521 - 1599853964     info] _api_cmdb_v2_config[1009] -- editing CLI object (append=1, auto_key=0, path=user, name=group, mkey=(null), flags=0)
[httpsd 6521 - 1599853964    error] cmdb_commit_from_json[1291] -- object already exists (mkey='<group_name>')
[httpsd 6521 - 1599853964    error] _api_cmdb_v2_config[1023] -- error editing object (nret=-5)
[httpsd 6521 - 1599853964    error] api_return_http_result[567] -- API error -5 raised
[httpsd 6521 - 1599853964     info] ap_invoke_handler[606] -- request completed (handler='api_cmdb_v2-handler' result==0)
[httpsd 6134 - 1599853964     info] ap_invoke_handler[583] -- new request (handler='logout-handler', uri='/logout', method='POST')
[httpsd 6134 - 1599853964     info] ap_invoke_handler[587] -- User-Agent: Python-urllib/3.6
[httpsd 6134 - 1599853964     info] ap_invoke_handler[590] -- Source: <myip>:<port> Destination: <fw_ip:port>
[httpsd 6134 - 1599853964     info] ap_invoke_handler[606] -- request completed (handler='logout-handler' result==0)

```

I've attempted on FortiOS 5.6.7 and 6.0.7, both encounter the same issue.  Attempted both with Galaxy Modules 1.0.9, 1.0.13, and 1.0.15.  It appears that it comes down to the "end" being sent on an empty config match group. 

Repeating these same commands in CLI gives the following:

```
cmd_clean_context 1, abort=0
Attribute 'server-name' MUST be set.
Command fail. Return code -56

```

**Comment by JieX19** [comment]
Hi @freddygfy,

Fortios collection supports version6 but not v5. I cannot reproduce the error on my side with FOS6.0.7m 6.2.3 and 6.4.0.

Can you please try the following playbook? Let's try the simple one and see what the errors are. Please make sure to create the members/users before setting user_group.

```
- hosts: fortigates
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    vdom: "root"
  tasks:
  - name: Configure user group
    fortios_user_group:
      vdom: "{{ vdom }}"
      state: "present"
      user_group:
        name: "Firewall_group_test"
        group_type: "firewall"
        member:
          - name: "firewall_user_1"
```
