### ISSUE TITLE
fortios_router_prefix_list treats each rule as exclusive

### ISSUE THREAD

**Issue by freddygfy** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#56]
This was encountered on FortiOS 6.2.5 using modules 1.0.10.  Please let me know if this may have been fixed in a different release.

When looping over fortios_router_prefix_list, or when running the play multiple times against different lists, only the last rule entered gets stored.  Any other rules that existed, or were added by previous plays, or previous invocations of the loop, get deleted.

This behavior was observed per prefix-list.  If more than one prefix-list was stated, but they contained more than one rule, the last rule/invocation in each prefix-list would remain and the others would be deleted.

Example task:
```
- name: Configure Prefix Lists
  fortios_router_prefix_list:
    vdom: "{{ item[0].vdom }}"
    state: "{{ item[1].state }}"
    router_prefix_list:
      name: "{{ item[0].name }}"
      rule:
        - action: "{{ item[1].action }}"
          ge: "{{ item[1].ge }}"
          le: "{{ item[1].le }}"
          prefix: "{{ item[1].prefix }}"
          id: "{{ item[1].id }}"
  with_subelements: 
    - "{{ prefix_list }}"
    - rule
  when: prefix_list is defined
```

Example Vars: 
```
prefix_list: 
  - name: "LOCAL_NETS"
    vdom: "data_vdom"
    rule: 
      - id: "1"
        action: "permit"
        prefix: "10.10.10.0/24"
        ge: ""
        le: ""
        state: "present"
      - id: "2"
        action: "permit"
        prefix: "10.10.255.10/32"
        ge: ""
        le: ""
        state: "present"        
  - name: "EXTERNAL_NETS"
    vdom: "data_vdom"
    rule:
      - id: "1"
        action: "permit"
        prefix: "0.0.0.0/0"
        ge: ""
        le: "" 
        state: "present"               
```

Diag debug CLI loop 1 (this play had run previously and I hadn't cleaned up before running it again):

```
0: config vdom
0: edit data_vdom
0: config router prefix-list
0: edit "LOCAL_NETS"
0: end
0: end
0: config vdom
0: edit data_vdom
0: config router prefix-list
0: edit "LOCAL_NETS"
0: config rule
0: delete 2
0: end
0: end
0: end
0: config vdom
0: edit data_vdom
0: config router prefix-list
0: edit "LOCAL_NETS"
0: config rule
0: edit 1
0: unset prefix
0: set prefix 10.10.10.0 255.255.255.0
0: unset ge
0: unset le
0: end
0: end
0: end
```

Loop 2: 

```
0: config vdom
0: edit data_vdom
0: config router prefix-list
0: edit "LOCAL_NETS"
0: end
0: end
0: config vdom
0: edit data_vdom
0: config router prefix-list
0: edit "LOCAL_NETS"
0: config rule
0: delete 1
0: end
0: end
0: end
0: config vdom
0: edit data_vdom
0: config router prefix-list
0: edit "LOCAL_NETS"
0: config rule
0: edit 2
0: unset prefix
0: set prefix 10.10.255.10 255.255.255.255
0: unset ge
0: unset le
0: end
0: end
0: end

```

Loop 3: 

```
0: config vdom
0: edit data_vdom
0: config router prefix-list
0: edit "EXTERNAL_NETS"
0: end
0: end
0: config vdom
0: edit data_vdom
0: config router prefix-list
0: edit "EXTERNAL_NETS"
0: config rule
0: edit 1
0: unset prefix
0: set prefix 0.0.0.0 0.0.0.0
0: unset ge
0: unset le
0: end
0: end
0: end
```

Finish state:

```
config router prefix-list
    edit "LOCAL_NETS"
        config rule
            edit 2
                set prefix 10.10.255.10 255.255.255.255
                unset ge
                unset le
            next
        end
    next
    edit "EXTERNAL_NETS"
        config rule
            edit 1
                set prefix 0.0.0.0 0.0.0.0
                unset ge
                unset le
            next
        end
    next
end
```

Desired state: 

```
config router prefix-list
    edit "LOCAL_NETS"
        config rule
            edit 2
                set prefix 10.10.255.10 255.255.255.255
                unset ge
                unset le
            next
            edit 1
                set prefix 10.10.10.0 255.255.255.0
                unset ge
                unset le
            next
        end
    next
    edit "EXTERNAL_NETS"
        config rule
            edit 1
                set prefix 0.0.0.0 0.0.0.0
                unset ge
                unset le
            next
        end
    next
end
```

I had also run this task multiple times with different var sets and with_item but had the same results.

```
prefix_list01: 
  - name: "LOCAL_NETS"
    vdom: "data_vdom"
    id: "1"
    action: "permit"
    prefix: "10.10.10.0/24"
    ge: ""
    le: ""
    state: "present"
    
prefix_list02:
  - name: "LOCAL_NETS"
    vdom: "data_vdom"
    id: "2"
    action: "permit"
    prefix: "10.10.255.10/32"
    ge: ""
    le: ""
    state: "present"        

- name: Configure Prefix Lists
  fortios_router_prefix_list:
    vdom: "{{ item.vdom }}"
    state: "{{ item.state }}"
    router_prefix_list:
      name: "{{ item.name }}"
      rule:
        - action: "{{ item.action }}"
          ge: "{{ item.ge }}"
          le: "{{ item.le }}"
          prefix: "{{ item.prefix }}"
          id: "{{ item.id }}"
  with_items: 
    - "{{ prefix_list01 }}"
  when: prefix_list01 is defined

- name: Configure Prefix Lists
  fortios_router_prefix_list:
    vdom: "{{ item.vdom }}"
    state: "{{ item.state }}"
    router_prefix_list:
      name: "{{ item.name }}"
      rule:
        - action: "{{ item.action }}"
          ge: "{{ item.ge }}"
          le: "{{ item.le }}"
          prefix: "{{ item.prefix }}"
          id: "{{ item.id }}"
  with_items: 
    - "{{ prefix_list02 }}"
  when: prefix_list02 is defined
```

**Comment by chillancezen** [comment]
hi @freddygfy,  thank you for the issue,

 **note the `state` is for the object router.prefix-list, not for the rule.**  you should not set state to `absent` unless you really wang to delete the whole router.prefix-list object.

despite that you can delete a single rule in CLI,  the rules in API design is not incrementally updated, this means each time you have to specify the **whole** rule set when you are creating/updating the router.prefix-list object. 

here is your example , always remember to give the whole ruleset.

```
- hosts: fortigate01
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
   prefix_list:
   - name: "LOCAL_NETS"
     vdom: "root"
     state: 'present' # 'absent' is to delete the whole LOCAL_NETS rulesets, not a single rule, always set to 'present'
     rule:
      - id: "1"
        action: "permit"
        prefix: "10.10.10.0/24"
        ge: ""
        le: ""
        removed: 'yes' # any value will be ok, because we only examine whether this field is defined
      - id: "2"
        action: "permit"
        prefix: "10.10.255.10/32"
        ge: ""
        le: ""
        #removed: 'no, must be commentted out'
   - name: "EXTERNAL_NETS"
     vdom: "root"
     state: 'present' # ditto
     rule:
      - id: "1"
        action: "permit"
        prefix: "0.0.0.0/0"
        ge: ""
        le: ""

  tasks:
    - name: Configure Prefix Lists
      fortios_router_prefix_list:
        vdom: "{{ item.vdom }}"
        state: "{{ item.state }}"
        router_prefix_list:
            name: "{{ item.name }}"
            rule: "{{ item.rule | rejectattr('removed', 'defined') | list }}"
      with_items:
            - "{{ prefix_list }}"
      when: prefix_list is defined
```

for more filters, please see https://docs.ansible.com/ansible/latest/user_guide/complex_data_manipulation.html

thanks,
Link.
