### ISSUE TITLE
fortios_system_interface - interface type emac-vlan is not supported

### ISSUE THREAD

**Issue by nicosalvadore** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#6]
Hello,

Trying to add an interface with the type _emac-vlan_ throws a fatal error on the task.

```
[...]
      system_interface:
        name: "port2.2999-{{ vdom }}"
        type: emac-vlan
        vdom: "{{ vdom }}"
        role: lan
        ip: "{{ mgmt_ip }}/23"
        interface: "port2.2999"
        alias: "mgmt-{{ vdom }}"
        allowaccess: ping
```

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of type must be one of: physical, vlan, aggregate, redundant, tunnel, vdom-link, loopback, switch, hard-switch, vap-switch, wl-mesh, fext-wan, vxlan, hdlc, switch-vlan, got: emac-vlan found in system_interface"}
`

As far as I can see in the module documentation, this interface type is not supported right now.
![image](https://user-images.githubusercontent.com/12870725/79733912-24409780-82f6-11ea-939c-dc3d9180cc14.png)

Will this feature be soon implemented in the ansible module ?
Thank you !
