### ISSUE TITLE
Enable to specify multiple day in fortios_firewall_schedule_recurring module

### ISSUE THREAD

**Issue by defus** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#65]
##### SUMMARY
I cannot use multiple days in the **fortios_firewall_schedule_recurring** module as the documentation says.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

- **fortios_firewall_schedule_recurring**

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /tmp/cib/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 15 2020, 01:53:50) [GCC 9.3.0]
```

##### CONFIGURATION
```
COLLECTIONS_PATHS(/tmp/cib/ansible.cfg) = ['/tmp/cib']
DEFAULT_ROLES_PATH(/tmp/cib/ansible.cfg) = ['/tmp/cib/roles']
GALAXY_SERVER_LIST(/tmp/cib/ansible.cfg) = ['awb_galaxy']
```

##### OS / ENVIRONMENT
- molecule docker image :  **quay.io/ansible/molecule:3.0.8**

##### STEPS TO REPRODUCE
```yaml
fortios_firewall_schedule_recurring:
  host:  "{{ provider.server }}"
  username: "{{ provider.user }}"
  password: "{{ provider.password }}"
  vdom:  "{{ provider.vdom }}"
  https: "{{ provider.https }}"
  ssl_verify: "{{ provider.ssl_verify }}"
  state: "present"
  firewall_schedule_recurring:
    name: "always-TODELETE"
    day: "monday tuesday wednesday thursday friday saturday sunday"
    start: "00:00"
    end: ""
```

##### EXPECTED RESULTS
Create schedule with multiple dates

##### ACTUAL RESULTS
```
 "msg": "value of day must be one of: sunday, monday, tuesday, wednesday, thursday, friday, saturday, none, got: ['monday', 'tuesday'] found in firewall_schedule_recurring"
```
