### ISSUE TITLE
Issue trying to delete a firewall policy using fortios_firewall_policy module

### ISSUE THREAD

**Issue by greenspartan** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#67]
Hello,

I would like to delete a particular firewall rule using **fortios_firewall_policy** module.
Here's below my playbook and also our environement details :
```

---

- hosts: localhost
  connection: httpapi
  collections:
  - fortinet.fortios
  gather_facts: False
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    fw_host: xxxxxxx
	username: xxxxxxx
	password: xxxxxxx
	vdom: root
  tasks:
    - name: Delete IPv4 policy on firewall
      fortios_firewall_policy: 
        host:  "{{ fw_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vdom:  "{{ vdom }}"
        ssl_verify: False
        state: "absent"
        firewall_policy:
          action: "accept"
          name: "NAT to Internet"
          dstaddr:
           - name: "all"
          dstintf:                    
           - name: "WAN1"
          ippool: "enable"
          nat: "enable"
          policyid: "0"
          poolname:
           - name: "PUBLIC-POOL"
          schedule: "always"
          service:
           - name: "ALL"
          srcaddr:
           - name: "SOURCE-ADDRESS"
          srcintf:
           - name: "port1"

```

Environment variables:

```
Tower = 3.6.3
ansible version = 2.9P3
Python = 3.6
fortiosapi = 1.0.5
pyfg = 0.5
```

Issue is that when I execute this playbook I have an error related to certificate : 

```
"module_stderr": "/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/urllib3/connectionpool.py:1004: 
	InsecureRequestWarning: Unverified HTTPS request is being made to host 'xx.xx.xx.xx'. Adding certificate verification is strongly advised.

```
For info this policy is already existing in the firewall.

Strange thing, is that if I replace state parameter with "present" instead of "absent", then the playbook executes correctly without any error and the policy is created correctly on the firewall.

It seems that the state parameter to absent causes this issue.

Do you have any idea ?

Thanks and have a good day ! 

Adrien
