### ISSUE TITLE
unable to load API plugin for network_os fortinet.fortios

### ISSUE THREAD

**Issue by greenspartan** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#68]
Hello,

I am trying to execute a playbook that simply create an object in the fortigate, using httpapi connection method, but it ends with error:

```
{
    "msg": "unable to load API plugin for network_os fortinet.fortios.fortios",
    "_ansible_no_log": false
}
```

Here's my playbook  : 

```
---

- hosts: fortigate
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    vdom: "root"
    object_name: "TEST"                                         
    object_ip: "200.200.200.200"
    object_comment: "TEST"
  tasks:
    - name: Create object on AMS Fortigate
      fortios_firewall_address:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_address:                                                           
          name: "{{ object_name }}"                                             
          subnet: "{{ object_ip }} "
          comment: "{{ object_comment }}"
```

Here's my inventory

```
[FORTIGATE]
ams_fortigate ansible_network_os=fortinet.fortios.fortios ansible_host=10.10.10.10 ansible_user="admin" ansible_password="password"
```

Here's my env variables : 

```
Tower = 3.6.3
ansible version = 2.9P3
Python = 3.6
fortiosapi = 1.0.5
pyfg = 0.5
```

I have of course install fortinet.fortios collection using command line in my 2.9P3 venv : 
`ansible-galaxy collection install fortinet.fortios`

For info it's working perfectly fine on the same firewall when I am not using httpapi connection method nor fortinet.fortios collection, with below playbook :  

```
---

- hosts: localhost
  gather_facts: False
  vars: 
    username: "admin"                                                              
    password: "password"  
    vdom: "root"
    fortigate_ip: "10.10.10.10"
  tasks:
    - name: CREATE OBJECT ON FORTIGATE
      fortios_firewall_address:
      host: "{{ fortigate_ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom: "{{ vdom }}"
      https: "True"
      state: "present"
      firewall_address:                                                           
        name: "TEST"                                             
        subnet: "200.200.200.200"
        comment: "TEST"
```

I will be more than happy if you have any idea ;)

Thanks !

Adrien

**Comment by chillancezen** [comment]
hi @greenspartan ,

sorry that I cannot reproduce your issue even with your playbook and inventory, so it must a setup issue.

could you help confirm what Ansible version it is:
```
$ansible --version
ansible 2.10.2
  config file = None
  configured module search path = ['/home/linky/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/linky/.local/lib/python3.6/site-packages/ansible
  executable location = /home/linky/.local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```


and whether the fortios collection is installed:
`~/.ansible/collections/ansible_collections/fortinet/fortios/` is normally the location whether our collection is going to be installed in.
```
$ls -l ~/.ansible/collections/ansible_collections/fortinet/fortios/
total 168
-rw-r--r-- 1 linky linky 106093 Oct 29 15:24 FILES.json
-rw-r--r-- 1 linky linky   1171 Oct 29 15:24 MANIFEST.json
-rw-r--r-- 1 linky linky  49274 Oct 29 15:24 README.md
drwxr-xr-x 3 linky linky   4096 Oct 29 15:24 examples
drwxr-xr-x 6 linky linky   4096 Oct 29 15:24 plugins
```

Thanks,
Link

**Comment by greenspartan** [comment]
Hi Link,

Thanks a lot for your reply !
Sure, here below the output of ansible --version 👍 

```
$ansible -- version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ldapuser/greenspartan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/ansible
  executable location = ./ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

However I can see that fortios collections have not been installed at the right location.
Using the command `ansible-galaxy collection install fortinet.fortios:1.0.15` it has been installed in my local directory `/home/greenspartan/.ansible/collections/ansible_collections`
and not in my appropriate tower venv which is located here:
`/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/ansible/`

How can I install the fortios collections at the appropriate place ? Should i move `ansible_collections` directory from `/home/greenspartan/.ansible/collections/ansible_collections` to  `/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/ansible/collections/ansible_collections` ?

Thanks !

Best Regards,

Adrien

**Comment by greenspartan** [comment]
Hi Link,

For info i just copy ansible_collections into `/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/ansible/collections/ansible_collections` 
but unfortunately I still got same error message : 

`"msg": "unable to load API plugin for network_os fortinet.fortios.fortios"`

Thus I can see the fortios collections modules are located here : 
`/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/ansible/collections/ansible_collections/fortinet/fortios/plugins/modules`

while the modules used by Ansible are here : 

`/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/ansible/modules/network/fortios`

How can I make Ansible/Tower using fortios modules located into `/opt/my-envs/Ansible2.9P3/lib/python3.6/site-packages/ansible/collections/ansible_collections/fortinet/fortios/plugins/modules` ?

Sorry for this noob question, I am network engineer and linux is not by far my best asset :) !

Adrien

**Comment by chillancezen** [comment]
Don't worry Adrien, 
I am going to seek help from Ansible core team, hoping they know the answer when using Ansible Tower.

Thanks,
Link

**Comment by chillancezen** [comment]
hi Adrien @greenspartan,

the core team doesn't have a response for my question. 

so could you use a python virtual environment to run your playbooks? I mean you use pure Ansible, not Ansible Tower.

here are some reference commands:
```
$pip3 install virtualenv
$python3 -m virtualenv mysandbox
$source mysandbox/bin/activate

$pip3 install ansible==2.9.10
$ansible --version
ansible 2.9.10
  config file = None
  configured module search path = ['/home/linky/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/linky/ansible/fortios_playbooks/mysandbox/lib/python3.6/site-packages/ansible
  executable location = /home/linky/ansible/fortios_playbooks/mysandbox/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]


$ansible-galaxy collection install fortinet.fortios -f



```
note these commands above have no any side effect, you can be free to use them.
each time you enter the python virtualized environment, you have to run `$source mysandbox/bin/activate`. 
quitting the virtual environment is simply close your shell.

thanks,
Link

**Comment by greenspartan** [comment]
Hi Link,

Thanks for your feedback.
I did exactly what you advised and I created a new virtualenv.
Then I entered the venv using the source command.

```
(Ansible2.9.10) [greenspartan@net-v-tower opt]$ ansible-galaxy collection install fortinet.fortios -f
/opt/my-envs/Ansible2.9.10/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
Process install dependency map
Starting collection install process
Installing 'fortinet.fortios:1.0.15' to '/home/greenspartan/.ansible/collections/ansible_collections/fortinet/fortios'
Skipping 'ansible.netcommon' as it is already installed
```

However, even after entering the venv via source command, fortios collections is still installed in my home directory rather than in the venv :(   

```
$ /opt/my-envs/Ansible2.9.10/bin/ansible-galaxy collection install fortinet.fortios -f
/opt/my-envs/Ansible2.9.10/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
Process install dependency map
Starting collection install process
Installing 'fortinet.fortios:1.0.15' to '/home/greenspartan/.ansible/collections/ansible_collections/fortinet/fortios'
Skipping 'ansible.netcommon' as it is already installed
```

Is there any parameter that we can use with **ansible-galaxy collection install fortinet.fortios** commands so it installs into venv ?

Thanks again for your support, that's very nice from you ;)

Best Regards,

Adrien

**Comment by chillancezen** [comment]
> Is there any parameter that we can use with ansible-galaxy collection install fortinet.fortios commands so it installs into venv ?

It's OK that virtual env and default env share the same collection installation path, my testbed has same behavior,and even in virtual env the collection can be found.
please let us know whether virtual env is viable.

thanks,
Link

**Comment by greenspartan** [comment]
Hi Link,

No it's still not working but I have a different issue using that new venv : 

```
/opt/my-envs/Ansible2.9.10/lib/python2.7/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature
ERROR! Unexpected Exception, this is probably a bug: No module named psutil
to see the full traceback, use -vvv
```

It seems now that Ansible/tower is not happy about Python version 2.7 and is waiting for higher version.
Do you know how I can upgrade Python version within the venv ?

Thanks !

Best Regards,

Adrien

**Comment by chillancezen** [comment]
hi Adrien:
you should use python3 to create a virtual env.
As far as I know, it's hard(at least of no benefit) to upgrade python2 to python3 in a virtual env. 
the direct way is::
```
$pip3 install virtualenv
$python3 -m virtualenv mysandbox
$source mysandbox/bin/activate
```
in your case, you may resolve error by installing missing packages:`pip install psutil `


note python3 is always preferred with Anisble.

thanks,
Link

**Comment by greenspartan** [comment]
Hi Link,

Thanks for your feedback.
I have installed a new venv using pip3 command and indeed this time I can see it's running Python3.6

```
(Ansible2.9.10P3) $ ansible --version
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/greenspartan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/my-envs/Ansible2.9.10P3/lib/python3.6/site-packages/ansible
  executable location = /opt/my-envs/Ansible2.9.10P3/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
(Ansible2.9.10P3) $ 

```
However, executing the playbook, I have still the following issue : 

```
{
    "msg": "unable to load API plugin for network_os fortinet.fortios.fortios",
    "_ansible_no_log": false
}
```

With former venv I had to install fortiosapi and pyfg python libraries.

Is it still needed with the new fortios collection ? Do I have also to install these two Python libraries (for info I have already installed psutils).

Best Regards,

Adrien

**Comment by chillancezen** [comment]
> Hi Link,
> 
> Thanks for your feedback.
> I have installed a new venv using pip3 command and indeed this time I can see it's running Python3.6
> 
> ```
> (Ansible2.9.10P3) $ ansible --version
> ansible 2.9.10
>   config file = /etc/ansible/ansible.cfg
>   configured module search path = ['/home/greenspartan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
>   ansible python module location = /opt/my-envs/Ansible2.9.10P3/lib/python3.6/site-packages/ansible
>   executable location = /opt/my-envs/Ansible2.9.10P3/bin/ansible
>   python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
> (Ansible2.9.10P3) $ 
> ```
> 
> However, executing the playbook, I have still the following issue :
> 
> ```
> {
>     "msg": "unable to load API plugin for network_os fortinet.fortios.fortios",
>     "_ansible_no_log": false
> }
> ```
> 
> With former venv I had to install fortiosapi and pyfg python libraries.
> 
> Is it still needed with the new fortios collection ? Do I have also to install these two Python libraries (for info I have already installed psutils).
> 
> Best Regards,
> 
> Adrien

that's so weird. I've never met this Ansible problem before. are you able to find a clean Linux machine (centos/ubuntu....). and try it (better with python3&pip3)again? core team still has no feedback. 

thanks,
Link

**Comment by greenspartan** [comment]
Hi Link,

Thanks for your feedback. For info I have open a ticket to RedHat support. I will let you know the outcome.

However I have an additional question : 
With the lastest fortios collections, do we still need to install additional python library like fortiosapi or pyFG ?
Indeed, installation of those libraries, was a prerequisites for former fortios modules.

Thanks in advance for your clarification.

Best Regards,

Adrien

**Comment by greenspartan** [comment]
Hi Link,

By the way, i did a new test getting rid of Tower completely, and just using Ansible in CLI.
Interesting stuff is that error is different.

Using below playbook, in virtual env 2.9.10 / Python 3.6.8

**playbook.yml**

 
```
---

- hosts: ams_fortigate
  collections:
   - fortinet.fortios
  connection: httpapi
  vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    vdom: "root"
    object_name: "TEST-TEST"
    object_ip: "200.200.200.200"
    object_comment: "TEST-TEST"
  tasks:
    - name: CREATE OBJECT ON FORTIGATE
      fortios_firewall_address:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_address:
          name: "{{ object_name }}"
          subnet: "{{ object_ip }} "
          comment: "{{ object_comment }}"
```

**hosts file**

```
ams_fortigate ansible_host=1.1.1.1 ansible_user="admin" ansible_password="xxxxxxx"

[fortigate:vars]
ansible_network_os=fortinet.fortios.fortios
```

I have the below error : 

```
(Ansible2.9.10P3) $ ansible-playbook -i hosts playbook.yml

PLAY [ams_fortigate] *************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************
ok: [ams_fortigate]

TASK [CREATE OBJECT ON FORTIGATE] ************************************************************************************************************************
fatal: [ams_fortigate]: FAILED! => {"changed": false, "meta": {"build": 272, "error": -9, "http_method": "POST", "http_status": 500, "name": "address", "path": "firewall", "revision": "779.0.908.15559452495731406834.1599132550", "serial": "FG240D3913800266", "status": "error", "vdom": "root", "version": "v6.0.6"}, "msg": "Error in repo"}

PLAY RECAP ***********************************************************************************************************************************************
ams_fortigate              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

(Ansible2.9.10P3) [abomble@net-v-tower bin]$ 
```

It's interesting as I can see that there's communication between ansible and the fortigate as the playbook retrieves SN, version...
but still ends with **error -9**.

Do you know what this **error -9** is related too ?

Thanks !

Best Regards,

Adrien
