### ISSUE TITLE
Isnt possible on fortinet.fortios.fortios_facts include vdom-link?

### ISSUE THREAD

**Issue by sergioolovrap** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#69]
Hi,
I need to get the vdom-link for verifying if there just existed to create a new.
Is it possible?
Thanks You
Sergio

**Comment by sergioolovrap** [comment]
> Hi,
> I need to get the vdom-link for verifying if there just existed to create a new.
> Is it possible?
> Thanks You
> Sergio

- hosts: EDC-FGT
   collections:
     - fortinet.fortios
   connection: httpapi
   vars:
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 4434
    ansible_user: olovrap
    ansible_network_os: fortios
   tasks:
     - name: fortios_facts
       fortios_facts:
         vdom: "root"
         gather_subset:
           - fact: "system_interface_select"
             filters:
               - include_vlan: true

It's possible to add a filter for vdom-link instead vlan?

**Comment by JieX19** [comment]
@sergioolovrap,

Thanks for your question! Parameter 'include_vlan' is a filter for system_interface, retrieving vdom-link info is not related to this module. fortios_facts module does not support vdom-link feature currently. We are developing a new module of fortios_facts, which will handle the 'Get' feature for all of the modules. 

Thanks,
Jie

**Comment by chillancezen** [comment]
selector: `system_vdom-link`
param: `name` type: `str`

**Comment by chillancezen** [comment]
hi @sergioolovrap 
latest galaxy FOS collection has supported this:https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_configuration_fact.html
please install latest collection with command below:
```
$ansible-galaxy collection install -f fortinet.fortios
$cat fact.yml
- hosts: fortigate04
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:

   - name: fact gathering
     fortios_configuration_fact:
        vdom: "{{ vdom }}"
        #access_token: "{{ fortios_access_token }}"
        selector: 'system_vdom-link'
        params:
            name: '<your vdom link name>'
```

I mark this `closed`,  please let us know if you have any problem in resolving the results.
Thanks,
Link
