### ISSUE TITLE
fortios_router_bgp http_method 'POST'

### ISSUE THREAD

**Issue by ZackovichZ** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#71]
Hello, 
I want to POST method for a given module, how can I do that? I don't want to reload the list of neighbors every time.

**Comment by chillancezen** [comment]
hi @ZackovichZ, 

the method behind Ansible is:

1. try to `GET` an object.
2. if the object exists, `PUT` to update the object. 
3. otherwise, `POST` to create an object.


the semantics for `POST` is to create an object, could you help tell why you need to use `POST` for an URL? if possible, could you provide an example of your issue?

thanks,
Link

**Comment by ZackovichZ** [comment]
@chillancezen Hi, 


I need to run a workflow where new neighbors will be constantly added. Currently, when I add a new neighbor - all old peers are removed. The option when I have to add old neighbors is not very convenient for me.

**Comment by ZackovichZ** [comment]
@chillancezen 
Look: 


`2020-11-23 12:43:51 cmd=config vdom
edit "VDOM"
config router bgp
config neighbor
**_delete 10.10.30.11_**
end
end
 
2020-11-23 12:43:51 cmd=end
 
2020-11-23 12:43:51 [cli_exec_cli_command]0: edit "10.10.30.10"
 
2020-11-23 12:43:51 [cli_exec_cli_command]0: set description "test"
 
2020-11-23 12:43:51 [cli_exec_cli_command]0: set remote-as 65333
 
2020-11-23 12:43:51 [cli_exec_cli_command]0: end
 
2020-11-23 12:43:51 [cli_exec_cli_command]0: end
 
2020-11-23 12:43:51 cmd=config vdom
edit "VDOM"
config router bgp
config neighbor
edit 10.10.30.10
set description test
set remote-as 65333
end
end`


**First, it removes the existing neighbor, then adds a new one.
If I understood you correctly, then this should not work.**

**Comment by chillancezen** [comment]
hi @ZackovichZ,

I see you concern, but I am afraid `POST` will not resolve this issue for reasons:

1.  `router/bgp` is a global object, no `POST` method is exported to users. API reference: https://fndn.fortinet.net/index.php?/fortiapi/1-fortios/705/1/router/
![Screen Shot 2020-11-24 at 09 18 46](https://user-images.githubusercontent.com/10312789/100034490-3c9e0500-2e37-11eb-9081-4da77c1672ba.png)
2. only `PUT` is available to update the global object, to be precise, non-incrementally update the global object `router/bgp`.

the mechanism `non-incremental update` is enforced by Fortigate API backend, Ansible can not break the limitation, so API consumers(including Ansible) may enumerate all neighbors and add new neighbors to update the object... and  it's the only way. 

as for querying the `router/bgp` and 
its neighbors officially, we are going to support this in next few weeks. 

thanks,
Link

**Comment by chillancezen** [comment]
> querying the router/bgp and its neighbors officially.

we have now support for this: https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/fortios_configuration_fact.html

please install latest FOS collection:
```
$ansible-galaxy collection install -f fortinet.fortios
```

the selector is `router_bgp `,
one example might be:
```
$cat fact.yml
- hosts: fortigate04
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:

   - name: fact gathering
     fortios_configuration_fact:
        vdom: "{{ vdom }}"
        #access_token: "{{ fortios_access_token }}"
        selector: 'router_bgp'
```

I now mark this issue `closed`, please feel free to reopen it in case of any issues which need support. 
thanks,
Link
