### ISSUE TITLE
Request for enhancement: fortios_reboot

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#73]
Please consider tweaking the generator to create a module that performs an `execute reboot` action. I think the webUI uses `/api/v2/monitor/system/os/reboot`.

**Comment by JonTheNiceGuy** [comment]
I have a temporary work-around for this:

```yaml
  - name: Get FortiGate Session
    when: ha_master
    delegate_to: localhost
    uri:
      url: "https://{{ ansible_host }}:{{ ansible_httpapi_port | default(443) }}/logincheck"
      validate_certs: no
      method: POST
      body_format: form-urlencoded
      body:
        username: "{{ ansible_user }}"
        secretkey: "{{ ansible_password }}"
    register: auth

  - name: "Reboot"
    when: auth.set_cookie is defined and ha_master
    delegate_to: localhost
    uri:
      url: "https://{{ ansible_host }}:{{ ansible_httpapi_port | default(443) }}/api/v2/monitor/system/os/reboot"
      validate_certs: no
      method: POST
      return_content: yes
      headers:
        Cookie: "{{ auth.set_cookie }}"
        "X-CSRFTOKEN": "{{ auth.cookies.ccsrftoken | regex_replace('\\\"', '') }}"
      body_format: json
      body:
        event_log_message: "Reboot"

  - name: Wait for reboot action to execute
    ansible.builtin.wait_for:
      timeout: 10
    delegate_to: localhost
  
  - name: Resume FortiGate Session
    when: ha_master
    delegate_to: localhost
    uri:
      url: "https://{{ ansible_host }}:{{ ansible_httpapi_port | default(443) }}/logincheck"
      validate_certs: no
      method: POST
      body_format: form-urlencoded
      body:
        username: "{{ ansible_user }}"
        secretkey: "{{ ansible_password }}"
    register: auth
    until: auth.failed == false
    retries: 240 # retry X times
    delay: 5 # pause for X sec b/w each call
```
