### ISSUE TITLE
fortios_firewall_address: unabled to add name with '/'

### ISSUE THREAD

**Issue by s0x00** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#8]
Trying to add an address object which name includes a slash '/' character e.g. 'FOO/BAR'.
Which raises "Error in repo" in Ansible or "API error 400 raised" on Fortigate.

api debug:

```
[httpsd 9937 - 1588700016     info] cmdb_generate_schema[1037] -- generating schema for firewall.address
[httpsd 9937 - 1588700016     info] handle_cli_req_v2_vdom[1965] -- returning to original vdom "root"
[httpsd 9937 - 1588700016     info] ap_invoke_handler[616] -- request completed (handler='api_cmdb_v2-handler' result==0)
[httpsd 9937 - 1588700016     info] ap_invoke_handler[593] -- new request (handler='api_cmdb_v2-handler', uri='/api/v2/cmdb/firewall/address/FOO/BAR?vdom=<VD>', method='PUT')
[httpsd 9937 - 1588700016     info] ap_invoke_handler[597] -- User-Agent: python-requests/2.22.0
[httpsd 9937 - 1588700016     info] ap_invoke_handler[600] -- Source: x.x.x.x:49496 Destination: y.y.y.y:443
[httpsd 9937 - 1588700016     info] api_cmdb_v2_handler[2055] -- received api_cmdb_v2_request from 'x.x.x.x'
[httpsd 9937 - 1588700016     info] aps_init_process_vdom[1195] -- initialized process vdom to 'root' (cookie='(null)')
[httpsd 9937 - 1588700016     info] api_store_parameter[227] -- add API parameter 'vdom': '"<VD>"' (type=string)
[httpsd 9937 - 1588700016     info] api_store_parameter[227] -- add API parameter 'subnet': '"1.1.1.1 255.255.255.255"' (type=string)
[httpsd 9937 - 1588700016     info] api_store_parameter[227] -- add API parameter 'type': '"ipmask"' (type=string)
[httpsd 9937 - 1588700016     info] api_store_parameter[227] -- add API parameter 'name': '"FOO\/BAR"' (type=string)
[httpsd 9937 - 1588700016     info] handle_cli_req_v2_vdom[1954] -- attempting to change from vdom "root" to vdom "<VD>"
[httpsd 9937 - 1588700016     info] handle_cli_req_v2_vdom[1957] -- new CMDB API request (vdom='<VD>',user='admin')
[httpsd 9937 - 1588700016     info] api_cmdb_request_init_by_path[1360] -- new CMDB query (path='firewall',name='address')
[httpsd 9937 - 1588700016     info] api_cmdb_request_init_by_path[1389] -- querying CMDB entry (mkey='FOO')
[httpsd 9937 - 1588700016     info] api_cmdb_request_init_by_path[1393] -- unable to find 'FOO' in table 'firewall.address'
[httpsd 9937 - 1588700016     info] api_cmdb_request_init[1488] -- new CMDB child query for 'firewall.address:BAR'
[httpsd 9937 - 1588700016    error] api_cmdb_request_init[1494] -- unable to create child query
[httpsd 9937 - 1588700016    error] api_return_http_result[631] -- API error 400 raised
[httpsd 9937 - 1588700016     info] handle_cli_req_v2_vdom[1965] -- returning to original vdom "root"
```

```
$ansible --vers
ansible 2.9.6
```

```
$ pip freeze | grep fortios
fortiosapi==1.0.1

```

Thanks in advance.

**Comment by chillancezen** [comment]
hi @s0x00 ,

thanks for your issue, it has been fixed but not released, I will keep you updated util next release is done soon.

thanks,
Link

**Comment by chillancezen** [comment]
hi @s0x00 ,
please re-install your fortios galaxy collection with latest `1.0.9`

```
$ ansible-galaxy collection install fortinet.fortios:1.0.9 -f
```

here is an example that use non-regular characters in primary key:
```
- hosts: fortigate01
  connection: httpapi 
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
   - name: Configure global attributes.
     fortios_firewall_address:
        vdom:  "{{ vdom }}"
        state: "present"
        firewall_address:
            name: 'FW/ADDRESS? with escape letters'
```

I mark this issue as `closed `.
please reopen it and let me know  if there is anything I could do to help.

thanks,
Link

**Comment by s0x00** [comment]
Hi Link,

I've upated the collection to 1.0.9. Unfortunatly im getting the same error.

```
[httpsd 5119 - 1591195498     info] cmdb_generate_schema[1037] -- generating schema for firewall.address
[httpsd 5119 - 1591195498     info] handle_cli_req_v2_vdom[1965] -- returning to original vdom "root"
[httpsd 5119 - 1591195498     info] ap_invoke_handler[616] -- request completed (handler='api_cmdb_v2-handler' result==0)
[httpsd 5119 - 1591195498     info] ap_invoke_handler[593] -- new request (handler='api_cmdb_v2-handler', uri='/api/v2/cmdb/firewall/address/FOO/BAR?vdom=ANS', method='PUT')
[httpsd 5119 - 1591195498     info] ap_invoke_handler[597] -- User-Agent: python-requests/2.22.0
[httpsd 5119 - 1591195498     info] ap_invoke_handler[600] -- Source: x.x.x.x:36648 Destination: y.y.y.y:443
[httpsd 5119 - 1591195498     info] api_cmdb_v2_handler[2055] -- received api_cmdb_v2_request from 'x.x.x.x'
[httpsd 5119 - 1591195498     info] aps_init_process_vdom[1195] -- initialized process vdom to 'root' (cookie='(null)')
[httpsd 5119 - 1591195498     info] api_store_parameter[227] -- add API parameter 'vdom': '"ANS"' (type=string)
[httpsd 5119 - 1591195498     info] api_store_parameter[227] -- add API parameter 'subnet': '"1.1.1.1 255.255.255.255"' (type=string)
[httpsd 5119 - 1591195498     info] api_store_parameter[227] -- add API parameter 'type': '"ipmask"' (type=string)
[httpsd 5119 - 1591195498     info] api_store_parameter[227] -- add API parameter 'name': '"FOO\/BAR"' (type=string)
[httpsd 5119 - 1591195498     info] handle_cli_req_v2_vdom[1954] -- attempting to change from vdom "root" to vdom "ANS"
[httpsd 5119 - 1591195498     info] handle_cli_req_v2_vdom[1957] -- new CMDB API request (vdom='ANS',user='admin')
[httpsd 5119 - 1591195498     info] api_cmdb_request_init_by_path[1360] -- new CMDB query (path='firewall',name='address')
[httpsd 5119 - 1591195498     info] api_cmdb_request_init_by_path[1389] -- querying CMDB entry (mkey='FOO')
[httpsd 5119 - 1591195498     info] api_cmdb_request_init_by_path[1393] -- unable to find 'FOO' in table 'firewall.address'
[httpsd 5119 - 1591195498     info] api_cmdb_request_init[1488] -- new CMDB child query for 'firewall.address:BAR'
[httpsd 5119 - 1591195498    error] api_cmdb_request_init[1494] -- unable to create child query
[httpsd 5119 - 1591195498    error] api_return_http_result[631] -- API error 400 raised
[httpsd 5119 - 1591195498     info] handle_cli_req_v2_vdom[1965] -- returning to original vdom "root"
[httpsd 5119 - 1591195498     info] ap_invoke_handler[616] -- request completed (handler='api_cmdb_v2-handler' result==0)
[httpsd 3157 - 1591195498     info] ap_invoke_handler[593] -- new request (handler='logout-handler', uri='/logout', method='POST')
[httpsd 3157 - 1591195498     info] ap_invoke_handler[597] -- User-Agent: python-requests/2.22.0
[httpsd 3157 - 1591195498     info] ap_invoke_handler[600] -- Source: x.x.x.x:36650 Destination: y.y.y.y:443
[httpsd 3157 - 1591195498     info] ap_invoke_handler[616] -- request completed (handler='logout-handler' result==0)
```

BR

**Comment by chillancezen** [comment]
hi @s0x00 , 

did you use collection via the following statement?
```
  connection: httpapi 
  collections:
  - fortinet.fortios
```
could you please share the playbook and host inventory ?

thanks,
Link

**Comment by s0x00** [comment]
Hi Link,

I'm using the collection in the playbook:

**playbook:**
``` 
- hosts: localhost
  connection: httpapi
  collections:
  - fortinet.fortios

  vars:
    vd: "ANS"
    host: "x.x.x.x"
 
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    ansible_httpapi_password: "xxxx"
    ansible_user: "xxxx"

  tasks:
    - name: add adresses.
      include_tasks: ./tasks/fos_addr.yml
```

**task:**
```
- name: Configure IPv4 addresses.
  fortios_firewall_address:
    host:  '{{ host }}'
    username: '{{ username }}'
    password: '{{ password }}'
    vdom:  '{{ vd }}'
    https: yes
    ssl_verify: no
    state: 'present'
    firewall_address:
      name: 'FOO/BAR'
      type: 'ipmask'
      subnet: '1.1.1.1 255.255.255.255'
```

Thanks and br.
