### ISSUE TITLE
some Modules replacing all vs adding configuration

### ISSUE THREAD

**Issue by wmclendon** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#85]
hello,

i'm fairly new to the FortiOS ansible modules, and i've come across a few modules that behave unexpectedly (at least to me) where instead of adding for example a BGP neighbor, it replaces the entire BGP neighbor configuration.  it may indeed be user error, but hoping for feedback / guidance.  this is on FortiOS 6.4 with a 200F using v1.1.7 of the collection.

for example, I have the following task in a playbook:

```
    - name: Configure BGP - Configure Neighbors
      fortinet.fortios.fortios_router_bgp:
        vdom: "{{ vdom }}"
        router_bgp:
          as: "{{ local_bgp_asn }}"
          neighbor:
            - ip: "{{ item.tunnel_prefix | ansible.netcommon.ipaddr('2') | ansible.netcommon.ipaddr('address') }}"
              interface: "{{ item.name }}"
              description: "{{ item.name }}"
              passive: enable
              remote_as: "{{ item.asn }}"
              maximum_prefix: "{{ bgp_neighbor_max_prefixes }}"
              route_map_out: "FOO-RM-OUT"
              route_map_in: "FOO-RM-IN"
      loop: "{{ bgp_sites }}"
      when: item.asn is defined
```

instead of iterating over and creating a new BGP neighbor for each entry, it is instead replacing the neighbor configuration each time and I end up with only the last BGP neighbor configured.

for now i'm working around this by creating a list of dictionaries that will then get passed to the module in one call, however that could lead to an 'oops' moment if another playbook ever needs to create a BGP neighbor -- it has to know about all of the other neighbors first.

Thanks,

Will

**Comment by robennis** [comment]
I am experiencing the same problem with fortios_firewall_addrgrp. I want to append member entries, not replace the entire group. 

Re-writing the BGP neighbor config instead of appending sounds like a terrible thing to have to do on a production system!

Does anyone know the correct way to deal with this behavior? It must be a common requirement.

**Comment by SkyIsOverTLT** [comment]
I have problems with fortios_firewall_addrgrp, fortios_firewall_policy modules too. They just replace the whole config instead of fixing parts of the config.
Ansible shows that idempotency is good, but we can't use it and it's terrible.
I haven't found a workaround yet.

**Comment by wmclendon** [comment]
the way ive dealt with that is either a custom filter or a task to set a fact to combine all the addrgrp members into a list of the proper format for the module

**Comment by chillancezen** [comment]
hi @wmclendon, @robennis, @SkyIsOverTLT ,

**1: To Replace/Create All:**
please use module `fortios_router_bgp ` and enumerate all neighbors in your playbook, mainly because FortiOS RestAPI does not allow *incremental* update:
 ```
- name: Configure BGP - Configure Neighbors
      fortinet.fortios.fortios_router_bgp:
        vdom: "{{ vdom }}"
        router_bgp:
          as: "{{ local_bgp_asn }}"
          neighbor:
            - ip: ...
            - ip: ...
            - ip: ...
            - ip: ...
            - ip: ...	   
 
```
**2: Add A Neighbour:** 
use raw CLI commands, doc: https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-work-with-raw-fotios-cli.
```
- hosts: localhost
  vars:
    fgt_host: '192.168.190.171'
    fgt_user: 'admin'
    fgt_pass: 'ca\$hc0w'

    neighbors_added:
      - neighbor: '1.1.1.1'
        remote_as: '65111'
      - neighbor: '1.1.1.2'
        remote_as: '65112'
      - neighbor: '1.1.1.3'
        remote_as: '65113'
    script_path: '/tmp/fgt.shell.task'
  tasks:
   - name: Prepare The Shell Scrit Template.
     raw: |
            cat > {{script_path }} << EOF_OUTER
            sshpass -p '{{ fgt_pass }}' ssh -o StrictHostKeyChecking=no {{ fgt_user }}@{{ fgt_host }} <<EOF
            a
            # ====================== Edit Your Commands Below =============================================
            config router bgp
            config neighbor
            edit '\$1'
            set remote-as '\$2'
            end
            end
            # ==============================================================================================
            EOF
            EOF_OUTER


   - name: Add The Neighbors, This will not impact existing neighbors
     raw: |
            chmod +x {{ script_path }} && {{ script_path }} "{{ item['neighbor'] }}" "{{ item['remote_as'] }}"
     args:
       executable: /bin/bash
     loop: "{{ neighbors_added }}"
```

to inspect newly added neighbors:
```
FGVM02TM20012347 # show router bgp
config router bgp
    config neighbor
        edit "2.0.0.1"
            set remote-as 65111
        next
        edit "1.1.1.1"
            set remote-as 65111
        next
        edit "1.1.1.2"
            set remote-as 65112
        next
        edit "1.1.1.3"
            set remote-as 65113
        next
    end
```
**Note `2.0.0.1 ` are not replaced.**

**3: Delete A Neighbour:** 
```
- hosts: localhost
  vars:
    fgt_host: '192.168.190.171'
    fgt_user: 'admin'
    fgt_pass: 'ca\$hc0w'

    script_path: '/tmp/fgt.shell.task'
  tasks:
   - name: Prepare The Shell Scrit Template.
     raw: |
            cat > {{script_path }} << EOF_OUTER
            sshpass -p '{{ fgt_pass }}' ssh -o StrictHostKeyChecking=no {{ fgt_user }}@{{ fgt_host }} <<EOF
            a
            # ====================== Edit Your Commands Below =============================================
            config router bgp
            config neighbor
            delete '\$1'
            end
            end
            # ==============================================================================================
            EOF
            EOF_OUTER


   - name: Add The Neighbors, This will not impact existing neighbors
     raw: |
            chmod +x {{ script_path }} && {{ script_path }} "2.0.0.1"
     args:
       executable: /bin/bash
```

**Comment by chillancezen** [comment]
> the way ive dealt with that is either a custom filter or a task to set a fact to combine all the addrgrp members into a list of the proper format for the module

this is not kind of viable as as you must fill out every non-empty fields of existing members.

**Comment by chillancezen** [comment]
> I have problems with fortios_firewall_addrgrp, fortios_firewall_policy modules too. They just replace the whole config instead of fixing parts of the config.
> Ansible shows that idempotency is good, but we can't use it and it's terrible.
> I haven't found a workaround yet.

@robennis @SkyIsOverTLT 
could you also consider the raw CLI way https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/faq.html#how-to-work-with-raw-fotios-cli for your cases?

**Comment by robennis** [comment]
For my project I have now moved away from Ansible completely and simply written my own API functions in Python. For what I'm trying to achieve, Ansible seems like the wrong solution. 

In the API, PUT is normally used for updates, however I found that using /firewall/addrgrp/{name} overwrites member[] with the member being added. What does work is use of a POST to post "name": "address to add" to /firewall/addrgrp/{group name}/member. This inserts a "address to add" in member[].

**Comment by chillancezen** [comment]
dynamically appending member is great!
This feature will be consolidated in the future!

**Comment by jantari** [comment]
Isn't this exactly what ansibles' newer "Network Resource Modules" do with their support for more states than just "present" and "absent"? See: https://docs.ansible.com/ansible/latest/network/user_guide/network_resource_modules.html#network-resource-module-states

I would think the fortios collection is going to support this resource-module approach sometimes soon maybe hopefully?

**Comment by JieX19** [comment]
Hi @wmclendon @jantari @robennis,

Please try our new release 2.1.3, which allows to do a member operation on an object. 

**ansible-galaxy collection install fortinet.fortios:2.1.3**





Below is an example to illustrate this feature:

**Task1 will add two members for the group named foogrp:**

```
- hosts: fortigate01
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
   - name: create a address group object
     fortios_firewall_addrgrp:
       access_token: "{{ fortios_access_token }}"
        vdom: "{{ vdom }}"
        state: present
        firewall_addrgrp:
            name: foogrp
            member:
                - name: login.microsoftonline.com
                - name: wildcard.google.com
``` 

**Task 2 will add a new member to it.**

```
   - name: create a address group object
     fortios_firewall_addrgrp:
        vdom: "{{ vdom }}"
        member_path: 'member:name'
        member_state: present
        state: present
        firewall_addrgrp:
            name: foogrp
            member:
                - name: login.windows.net
```

**There should be three members in this group.**
