### ISSUE TITLE
the connection fails when using a https port that is not 443

### ISSUE THREAD

**Issue by RobVerduijn** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#88]
Hello,

I'm trying to get this collection to work.
However, even with the most basic example to gather some facts it fails.
In the verbose output I see the play trying to connect on port 443 even though I explicitly stated that it should use 80443
inventory:
```
all:
  hosts:
     fortitest:
        ansible_host: 1.2.3.4
```

playbook:
```
---
- name: fact_test
  hosts: fortitest
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "mytestvdom"
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80443
  tasks:
  - name: gather basic system status facts
    fortios_facts:
       host: "{{ inventory_hostname }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_password }}"
       vdom: "{{ vdom }}"
       gatherr_subset:
           - fact: 'system_status_select'
```

**Comment by chillancezen** [comment]
hi @RobVerduijn ,

port 80443 is invalid.

valid range is [1, 2^16-1], i.e. the maximum port is 65535

thanks,
Link

**Comment by RobVerduijn** [comment]
hi,
duh,...

silly me... not thinking

however also gives the same issue with 54321

Rob

**Comment by chillancezen** [comment]
oh I see, 
`ansible_httpapi_port ` only applies to `httpapi` mode. legacy `fortiosapi` is  not supported anymore. 
please refer to https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/playbook.html#prepare-host-inventory for more. 

here is my playbook:
```
- hosts: fortigate03
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 54321
  tasks:

   - name: fact gathering
     fortios_facts:
        #host: "{{ inventory_hostname }}"
        #username: "{{ ansible_user }}"
        #password: "{{ ansible_password }}"
        gather_subset:
            - fact: system_ha-checksums_select
```

no `password`, `username` or `host`.

**Comment by chillancezen** [comment]
![1611833587328](https://user-images.githubusercontent.com/10312789/106133074-bd62df80-619f-11eb-9496-0bb02a898e40.jpg)

**Comment by sandi91** [comment]
Same issue on our Lab env.
port 8443 is configured on fortinet as https port.
when we try this simple playbook:

---
- name: fact_test
  hosts: 192.168.0.1
  collections:
  - fortinet.fortios
  connection: httpapi
  vars:
    vdom: "root"
    ansible_network_os: fortinet.fortios.fortios
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443
  tasks:
  - name: gather basic system status facts
    fortios_facts:
       host: "{{ inventory_hostname }}"
       vdom: "{{ vdom }}"
       gather_subset:
           - fact: 'system_status_select'

it gives an error like this:

raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='192.168.0.1', port=443): Max retries exceeded with url: /logincheck (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7bace7274290>, 'Connection to 192.168.0.1 timed out. (connect timeout=12)'))

Could someone help with this please?

**Comment by RobVerduijn** [comment]
> oh I see,
> `ansible_httpapi_port ` only applies to `httpapi` mode. legacy `fortiosapi` is not supported anymore.
> please refer to https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/playbook.html#prepare-host-inventory for more.
> 
> here is my playbook:
> 
> ```
> - hosts: fortigate03
>   connection: httpapi
>   collections:
>   - fortinet.fortios
>   vars:
>    vdom: "root"
>    ansible_httpapi_use_ssl: yes
>    ansible_httpapi_validate_certs: no
>    ansible_httpapi_port: 54321
>   tasks:
> 
>    - name: fact gathering
>      fortios_facts:
>         #host: "{{ inventory_hostname }}"
>         #username: "{{ ansible_user }}"
>         #password: "{{ ansible_password }}"
>         gather_subset:
>             - fact: system_ha-checksums_select
> ```
> 
> no `password`, `username` or `host`.

Sorry, forgot to post my reply
Your answer was working for me, took me a couple reads before I realized there was a tiny but obviously significant difference between our examples.

Rob

**Comment by sandi91** [comment]
@RobVerduijn  Sorry, Rob, was it working for you with different port than 443?

**Comment by RobVerduijn** [comment]
@sandi91 yes, i used a high port in the unprivileged port range
removing this line helped:
```
ansible_network_os: fortinet.fortios.fortios
```
could it be it is somewhere set else in your play ? (in a group_var or host_var or inventory)

**Comment by sandi91** [comment]
@RobVerduijn, in that case it throws this error: - 
"msg": "Unable to automatically determine host network os. Please manually configure ansible_network_os value for this host"

**Comment by chillancezen** [comment]
> @RobVerduijn, in that case it throws this error: -
> "msg": "Unable to automatically determine host network os. Please manually configure ansible_network_os value for this host"

@sandi91 , could you have a try with the example  to define network os in https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.0/playbook.html#prepare-host-inventory.

**Comment by sandi91** [comment]
When I try to use a different port by setting ansible_httpapi_port: 8443 and ansible_network_os: fortinet.fortios.fortios it is still trying to connect to port 443 instead of configured one, without  variable ansible_network_os it says I should provide that variable. Not sure what's wrong...

**Comment by RobVerduijn** [comment]
@sandi91 
Hi,

A bit late, but we got a new test environment in which we got the same symptoms as you did.
I used the example that @chillancezen used, and got the same error you did.
after adding the fqcn it started to work for us.
ie ansible was still using the old version and not the collections version.

so the example  that works for me now looks like: (the importent change being: fortinet.fortios.fortios_system_global)
and yes also the 'ansible_network_os: true' was required

```
- hosts: fortigate03
  connection: httpapi
  collections:
  - fortinet.fortios
  vars:
   vdom: "root"
   ansible_network_os: fortinet.fortios.fortios
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
   - name: Configure global attributes.
     fortinet.fortios.fortios_system_global:
        vdom:  "{{ vdom }}"
        access_token: "{{ fortios_access_token }}" #if you prefer access token based authentication, add this line.
        system_global:
            hostname: 'CustomHostName'
```
