### ISSUE TITLE
FortiOS_firewall_addrgrp exclude members

### ISSUE THREAD

**Issue by taylorjt2** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#92]
I have need to create an address group that excludes member, but it doesn't appear this is an option.  The raw config is:
```
edit "INTERNET-ACCESS"
 set member "all"
 set exclude enable
 set color 18
 set exclude-member "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16"
next
```
Is there a way to do this?

**Comment by mbdraks** [comment]
Yes, just use the v2.0.0 modules: https://ansible-galaxy-fortios-docs.readthedocs.io/en/galaxy-2.0.0/gen/fortios_firewall_addrgrp.html

**Comment by taylorjt2** [comment]
I'm struggling to figure out how to install 2.0.0.  I don't see it listed as one of the options on the FortiOS collection page, and when I issue the Ansible-galaxy collection install command for 2.0.0 it says it can't find that collection.  Has it been released, or is there a different way to get it via dev release or something?

**Comment by mbdraks** [comment]
It's not yet released to ansible galaxy but you can use it by installing directly from the repo:

```
ansible-galaxy collection install git+https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection.git,fos_v6.0.0/galaxy_2.0.0 -f```

**Comment by taylorjt2** [comment]
Okay, I have installed 2.0.0 and tried creating an address group with exclude members.  It will create the group, however, it will not enable exclude members nor add any members to exclude.  Here is what I am using:
```
- name: Configure IPv4 address group internet-access
  fortios_firewall_addrgrp:
    vdom:  "{{ vdom }}"
    state: present
    firewall_addrgrp:
      name: internet-access
      member:
        - name: 0.0.0.0_0
      exclude: enable
      exclude_member:
        - name: "rfc1918-networks"
        - name: "internal-public-networks"
      allow_routing: enable
      color: 18
      comment: "Internet address object"
```

And this is the resulting output:
```
TASK [addresses : Configure IPv4 address group internet-access] **********************************************************************
ok: [10.99.250.250] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_token": null,
            "enable_log": null,
            "firewall_addrgrp": {
                "allow_routing": "enable",
                "color": 18,
                "comment": "Internet address object",
                "exclude": "enable",
                "exclude_member": [
                    {
                        "name": "rfc1918-networks"
                    },
                    {
                        "name": "internal-public-networks"
                    }
                ],
                "fabric_object": null,
                "member": [
                    {
                        "name": "0.0.0.0_0"
                    }
                ],
                "name": "internet-access",
                "state": null,
                "tagging": null,
                "type": null,
                "uuid": null,
                "visibility": null
            },
            "state": "present",
            "vdom": "FG-traffic"
        }
    },
    "meta": {
        "build": 1803,
        "http_method": "PUT",
        "http_status": 200,
        "mkey": "internet-access",
        "name": "addrgrp",
        "path": "firewall",
        "revision": "28885b3b9a002c15acc1a49d770b9df9",
        "revision_changed": false,
        "serial": "FGVM00TM21000287",
        "status": "success",
        "vdom": "FG-traffic",
        "version": "v6.4.4"
    }
}
```

This is all that is created on the firewall:
```
    edit "internet-access"
        set uuid 6fa6a840-6ccf-51eb-a528-30320ab86a44
        set member "0.0.0.0_0"
        set comment "Internet address object"
        set color 18
        set allow-routing enable
    next
```

I am not sure why it is saying successful when the exclude is not applied.
