### ISSUE TITLE
fortios_addreses_policy use some srcinf or srcaddr

### ISSUE THREAD

**Issue by SkyIsOverTLT** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#99]
Hi, I have a question. Can I specify more than one network or service in the fortios_addreses_policy module? 
I use ansible 2.10.7 and fortinet.fortios:1.1.6 from [galaxy](https://galaxy.ansible.com/fortinet/fortios).
my task:
```
- name: Configure IPv4 policies.
  fortios_firewall_policy:
    state: "present"
    firewall_policy:
      action: "{{ item.policy_item.action }}"
      name: "{{ item.policy_item.name }}"
      schedule: "{{ item.policy_item.schedule }}"
      nat: "{{ item.policy_item.nat }}"
      status: "{{ item.policy_item.status }}"
      policyid: "{{ item.policy_item.policyid }}"
      dstaddr:
       -
         name: "{{ item.policy_item.dstaddr }}"
      dstintf:
       -
         name: "{{ item.policy_item.dstintf }}"
      srcaddr:
       -
         name: "{{ item.policy_item.srcaddr }}"
      srcintf:
       -
         name: "{{ item.policy_item.srcintf }}"
      service:
       -
         name: "{{ item.policy_item.service }}"
  with_items: "{{ fortios_addreses_policy }}"
  when: fortios_addreses_policy is defined
  tags: [ "fortios_policy"]
```
  and my vars:
  ```
fortios_addreses_policy:
  - policy_item:
      name: "allow all to webserver"
      policyid: "1"
      srcintf:
        - "vlan1"
      dstintf: "vlan10"
      srcaddr: "all"
      dstaddr: "local_webserver"
      action: "accept"
      schedule: "always"
      service: "HTTPS"
      nat: "disable"
```
in this case everything is fine, the rule is created. 
But I would like to write that from several networks you can have access:
```
srcintf:
        - '"vlan1" "vlan2"'
```

Ansible warns me that it is impossible to do this and crashes with an error. Ok, i agree that you need to provide a list in srcinf.
But even if I do this:
```
srcintf:
        - "vlan1"
        - "vlan2"
```
and change task as:
```
srcintf:
       -
         name: "{{ item }}"
         with_items: "{{ item.policy_item.srcintf }}"
```
No one of my attempts have been successful. 
So far I see only one option, to create groups of addresses and interfaces and operate with them.
Who knows how to specify multiple interfaces or multiple services in a rule?
